/* RunTheHouse, the skill tree and the archetype resolver.
 *
 * Headless and dependency-free. Browser: window.RH_TREE. Node: require.
 *
 * GDD §4 and §6. Two things live here and it matters that it is one file:
 *
 *   1. The tree the player spends tokens in.
 *   2. The function that reads a set of purchased nodes and names an archetype.
 *
 * The AI are generated by WALKING THE SAME TREE (see generate.js), so an
 * opponent is a real build and not a bag of rolled numbers with a label stapled
 * on. That is what lets a player learn to read the house: "high Comp Game,
 * nothing in Floor" looks the same coming from an opponent as it does coming
 * from your own screen, because it is the same data structure and the same
 * resolver.
 *
 * THE RULE THAT GOVERNS EVERY NODE, from GDD §6: a node may grant attributes.
 * A node may not grant behavior. Version 0.1 of the design doc listed things
 * like "Competitor becomes a target by week 5" as archetype rules, which is an
 * outcome the threat model is supposed to PRODUCE. If the sim does not produce
 * it, the sim is wrong and the fix goes in engine.js, never here.
 */

'use strict';

/* WRAPPED IN AN IIFE, and it is not optional.
 *
 * These are plain <script> tags, not modules, so every file shares one global
 * scope in the browser. Unwrapped, `const api` in seven files, `const E` in
 * comps.js and run.js, `const T` in generate.js and run.js and `const BY_ID` in
 * tree.js and comps.js all collide, and a colliding top-level const does not
 * warn: the whole file fails to parse and its global is simply never defined.
 * Measured symptom was six of seven modules missing and the page rendering
 * nothing. football/engine.js hit the same wall and name-spaced its way out;
 * a closure is the version that does not need policing as files grow.
 */
(function () {


// ─── attributes ──────────────────────────────────────────────────────────────

const COMP_ATTRS = ['physical', 'mental', 'precision', 'luck'];
const SOCIAL_ATTRS = ['charisma', 'deception', 'perception', 'loyalty', 'paranoia', 'ambition', 'volatility'];
const ALL_ATTRS = COMP_ATTRS.concat(SOCIAL_ATTRS);

/*
 * Everyone starts here, level 1 or level 60. 30 is deliberately low enough that
 * an unspent account is visibly a rookie and high enough that they are not
 * unplayable: the Move In Night dialogue (GDD §4) is the on-ramp, not the tree.
 *
 * paranoia and volatility START HIGHER THAN THEY END. They are the two
 * attributes where less is better, so the tree spends tokens reducing them. A
 * new account is jumpy and a veteran build can buy composure. That asymmetry is
 * the only place in the tree where progression reads as "calming down" rather
 * than "getting stronger", and it is worth keeping for exactly that reason.
 */
const BASE_ATTRS = {
  physical: 30, mental: 30, precision: 30, luck: 50,
  charisma: 30, deception: 30, perception: 30, loyalty: 45,
  paranoia: 55, volatility: 50, ambition: 35,
};

/* luck sits at 50 and no node touches it. It is the 15% of every comp that
   build cannot buy, which is what keeps a maxed account from sweeping. */
const UNBUYABLE = ['luck'];

const ATTR_MIN = 1;
const ATTR_MAX = 100;

// ─── the tree ────────────────────────────────────────────────────────────────

const TRUNKS = {
  comp:  { id: 'comp',  name: 'Comp Game',  blurb: 'Win your way through.' },
  floor: { id: 'floor', name: 'Floor Game', blurb: 'Be liked enough that nobody moves.' },
  long:  { id: 'long',  name: 'Long Game',  blurb: 'Control what the house believes.' },
};

/*
 * Branch specs. Six tiers each, expanded into nodes by buildTree() below.
 *
 * `primary` takes the full grant at every tier. `secondary` takes half, rounded
 * down, and only from tier 2 up, so the first node in a branch is unambiguous
 * about what it is for. Negative grants reduce the attribute; see BASE_ATTRS.
 */
const TIER_COST  = [2, 3, 4, 6, 8, 10];
const TIER_GRANT = [4, 5, 5, 6, 7, 8];

const BRANCHES = [
  // Comp Game
  { id: 'workhorse',  trunk: 'comp',  name: 'Workhorse',  primary: 'physical',   secondary: 'precision' },
  { id: 'technician', trunk: 'comp',  name: 'Technician', primary: 'precision',  secondary: 'mental' },
  { id: 'scholar',    trunk: 'comp',  name: 'Scholar',    primary: 'mental',     secondary: 'perception' },
  // Floor Game
  { id: 'recruiter',  trunk: 'floor', name: 'Recruiter',  primary: 'charisma',   secondary: 'ambition' },
  { id: 'confidant',  trunk: 'floor', name: 'Confidant',  primary: 'loyalty',    secondary: 'charisma' },
  { id: 'host',       trunk: 'floor', name: 'Host',       primary: 'perception', secondary: 'charisma' },
  // Long Game
  { id: 'reader',     trunk: 'long',  name: 'Reader',     primary: 'perception', secondary: 'mental' },
  { id: 'illusionist',trunk: 'long',  name: 'Illusionist',primary: 'deception',  secondary: 'charisma' },
  { id: 'broker',     trunk: 'long',  name: 'Broker',     primary: 'ambition',   secondary: 'deception' },
];

/*
 * Composure nodes hang off two branches rather than forming their own, because
 * a whole branch spent on "do not do anything stupid" is not a fantasy anyone
 * buys into. Attached where they read as character: a Confidant steadies, a
 * Broker keeps their nerve.
 */
const COMPOSURE = {
  confidant: { attr: 'paranoia', per: -4 },
  broker:    { attr: 'volatility', per: -5 },
};

function buildTree() {
  const nodes = [];

  for (const t of Object.keys(TRUNKS)) {
    nodes.push({
      id: `${t}.root`, trunk: t, branch: null, tier: 0, cost: 1,
      name: TRUNKS[t].name, note: TRUNKS[t].blurb,
      requires: [], grants: rootGrant(t),
    });
  }

  for (const b of BRANCHES) {
    for (let tier = 1; tier <= 6; tier++) {
      const grants = {};
      grants[b.primary] = TIER_GRANT[tier - 1];
      if (tier >= 2) {
        const half = Math.floor(TIER_GRANT[tier - 1] / 2);
        grants[b.secondary] = (grants[b.secondary] || 0) + half;
      }
      const comp = COMPOSURE[b.id];
      if (comp && tier >= 3) grants[comp.attr] = (grants[comp.attr] || 0) + comp.per;

      nodes.push({
        id: `${b.trunk}.${b.id}.${tier}`,
        trunk: b.trunk, branch: b.id, tier,
        cost: TIER_COST[tier - 1],
        name: `${b.name} ${'I'.repeat(Math.min(tier, 3))}${tier > 3 ? ` ${tier}` : ''}`.trim(),
        requires: [tier === 1 ? `${b.trunk}.root` : `${b.trunk}.${b.id}.${tier - 1}`],
        grants,
      });
    }
  }

  /* Trunk capstones need depth in TWO branches of the trunk, so the cheapest
     route to a capstone is not "dump everything in one line". */
  for (const t of Object.keys(TRUNKS)) {
    const bs = BRANCHES.filter((b) => b.trunk === t);
    nodes.push({
      id: `${t}.capstone`, trunk: t, branch: null, tier: 7, cost: 12,
      name: `${TRUNKS[t].name} Mastery`,
      requiresAny: bs.map((b) => `${t}.${b.id}.4`), requiresAnyCount: 2,
      requires: [`${t}.root`],
      grants: capstoneGrant(t),
    });
  }

  /* Cross-trunk capstones. These are the hybrid archetypes' natural home and
     the reason spending in two trunks is a plan rather than a mistake. */
  const PAIRS = [['comp', 'floor'], ['comp', 'long'], ['floor', 'long']];
  for (const [a, b] of PAIRS) {
    nodes.push({
      id: `hybrid.${a}_${b}`, trunk: null, branch: null, tier: 7, cost: 12,
      name: `${TRUNKS[a].name} and ${TRUNKS[b].name}`,
      requires: [`${a}.root`, `${b}.root`],
      requiresAny: BRANCHES.filter((x) => x.trunk === a || x.trunk === b).map((x) => `${x.trunk}.${x.id}.4`),
      requiresAnyCount: 2,
      grants: mergeGrants(capstoneGrant(a), capstoneGrant(b), 0.5),
    });
  }

  return nodes;
}

function rootGrant(trunk) {
  if (trunk === 'comp')  return { physical: 3, mental: 3, precision: 3 };
  if (trunk === 'floor') return { charisma: 3, loyalty: 3, perception: 2 };
  return { deception: 3, ambition: 3, perception: 2 };
}

function capstoneGrant(trunk) {
  if (trunk === 'comp')  return { physical: 6, mental: 6, precision: 6 };
  if (trunk === 'floor') return { charisma: 8, loyalty: 5, paranoia: -6 };
  return { deception: 8, ambition: 5, volatility: -6 };
}

function mergeGrants(a, b, scale) {
  const out = {};
  for (const k of Object.keys(a)) out[k] = Math.round(a[k] * (scale || 1));
  for (const k of Object.keys(b)) out[k] = Math.round((out[k] || 0) + b[k] * (scale || 1));
  return out;
}

const NODES = buildTree();
const BY_ID = new Map(NODES.map((n) => [n.id, n]));
const TREE_TOTAL_COST = NODES.reduce((s, n) => s + n.cost, 0);

// ─── spending ────────────────────────────────────────────────────────────────

/**
 * Can this node be bought given what is already owned? Prerequisites are two
 * shapes: `requires` is all-of, `requiresAny` with a count is n-of. Capstones
 * use both.
 */
function canBuy(owned, id) {
  const n = BY_ID.get(id);
  if (!n || owned.has(id)) return false;
  for (const r of n.requires) if (!owned.has(r)) return false;
  if (n.requiresAny) {
    const have = n.requiresAny.filter((r) => owned.has(r)).length;
    if (have < (n.requiresAnyCount || 1)) return false;
  }
  return true;
}

/** Every node buyable right now. Used by the tree UI and by AI generation. */
function available(owned) {
  return NODES.filter((n) => canBuy(owned, n.id));
}

const spend = (owned) => {
  let t = 0;
  for (const id of owned) t += (BY_ID.get(id) || { cost: 0 }).cost;
  return t;
};

/**
 * Purchased nodes to final attributes. Clamped, and `luck` is never touched no
 * matter what a grant says, which is enforced here rather than trusted to the
 * node data.
 */
function deriveAttributes(owned) {
  const attrs = Object.assign({}, BASE_ATTRS);
  for (const id of owned) {
    const n = BY_ID.get(id);
    if (!n) continue;
    for (const k of Object.keys(n.grants)) {
      if (UNBUYABLE.indexOf(k) !== -1) continue;
      attrs[k] = (attrs[k] || 0) + n.grants[k];
    }
  }
  for (const k of Object.keys(attrs)) {
    attrs[k] = Math.max(ATTR_MIN, Math.min(ATTR_MAX, Math.round(attrs[k])));
  }
  return attrs;
}

/** Split into the two groups the rest of the engine reads. */
function splitAttributes(attrs) {
  const comp = {}, social = {};
  for (const k of COMP_ATTRS) comp[k] = attrs[k];
  for (const k of SOCIAL_ATTRS) social[k] = attrs[k];
  return { comp, social };
}

// ─── archetypes ──────────────────────────────────────────────────────────────

const BASE_NAME = { comp: 'Competitor', floor: 'Anchor', long: 'Operator' };

/* Dominant trunk first. Reading down the left column: what you mostly are.
   Across: what you also are. */
const HYBRID = {
  comp:  { floor: 'Frontrunner', long: 'Analyst' },
  floor: { comp: 'Favorite',     long: 'Mastermind' },
  long:  { comp: 'Closer',       floor: 'Puppeteer' },
};

const BRANCH_NAME = {};
for (const b of BRANCHES) BRANCH_NAME[b.id] = b.name;

const SHARE = {
  /* Below this much total spend nobody has a shape worth naming. */
  MIN_SPEND: 8,
  /* No trunk above this means the spending has no centre of gravity. */
  DRIFTER_TOP: 0.45,
  /* Second trunk at or above this is a real second commitment, not a dip. */
  HYBRID_SECOND: 0.30,
  /* Branch share WITHIN its trunk needed to earn the specialist name. */
  SPECIALIST: 0.50,
  /* Floor share at or below this, with a Comp Game lead, is somebody who never
     came out of their room. */
  LONE_WOLF_FLOOR: 0.08,
};

/**
 * Name a build. Pure function of purchased nodes plus the attributes they
 * produce. Returns the name plus the shares it was derived from, because the
 * post-game recap shows the player why the house read them the way it did.
 *
 * Order of precedence, and the order matters:
 *   Newcomer  -> nothing bought worth naming
 *   Wildcard  -> volatility overrides any plan you thought you had
 *   Loudmouth -> so does being liked and disloyal at the same time
 *   Lone Wolf -> comps and nothing else
 *   Drifter   -> no centre of gravity, Chameleon if it is deliberate
 *   Hybrid    -> two real commitments
 *   Specialist/Base
 *
 * Wildcard and Loudmouth sit above the structural names on purpose. A player
 * whose volatility is through the roof does not get to be called a Mastermind
 * by the house, whatever their spending says, because that is not how the house
 * experiences them. This is the one place where derived attributes beat
 * spending shape, and it is why both AI and player run through it.
 */
function resolveArchetype(owned, attrs) {
  const a = attrs || deriveAttributes(owned);
  const total = spend(owned);

  const trunkSpend = { comp: 0, floor: 0, long: 0 };
  const branchSpend = {};
  for (const id of owned) {
    const n = BY_ID.get(id);
    if (!n) continue;
    if (n.trunk) trunkSpend[n.trunk] += n.cost;
    if (n.branch) branchSpend[n.branch] = (branchSpend[n.branch] || 0) + n.cost;
  }
  const structural = trunkSpend.comp + trunkSpend.floor + trunkSpend.long;
  const shares = {
    comp:  structural ? trunkSpend.comp / structural : 0,
    floor: structural ? trunkSpend.floor / structural : 0,
    long:  structural ? trunkSpend.long / structural : 0,
  };

  const order = ['comp', 'floor', 'long'].sort((x, y) => shares[y] - shares[x]);
  const top = order[0], second = order[1];

  const out = (name, why) => ({
    name, why, shares, trunkSpend, branchSpend, spend: total,
    topTrunk: top, topBranch: topBranchOf(branchSpend, top),
  });

  if (total < SHARE.MIN_SPEND) return out('Newcomer', 'nothing committed yet');
  if (a.volatility >= 70) return out('Wildcard', 'volatility overrides the plan');
  if (a.loyalty <= 25 && a.charisma >= 60) return out('Loudmouth', 'liked and unreliable');
  if (shares.comp >= 0.55 && shares.floor <= SHARE.LONE_WOLF_FLOOR) {
    return out('Lone Wolf', 'comps and nothing else');
  }
  if (shares[top] < SHARE.DRIFTER_TOP) {
    return out(a.deception >= 60 ? 'Chameleon' : 'Drifter', 'no centre of gravity');
  }
  if (shares[second] >= SHARE.HYBRID_SECOND) {
    return out(HYBRID[top][second], 'two real commitments');
  }

  const tb = topBranchOf(branchSpend, top);
  if (tb && trunkSpend[top] && (branchSpend[tb] / trunkSpend[top]) >= SHARE.SPECIALIST) {
    return out(BRANCH_NAME[tb], 'specialised inside one trunk');
  }
  return out(BASE_NAME[top], 'broad within one trunk');
}

function topBranchOf(branchSpend, trunk) {
  let best = null, bestV = 0;
  for (const b of BRANCHES) {
    if (b.trunk !== trunk) continue;
    const v = branchSpend[b.id] || 0;
    if (v > bestV) { bestV = v; best = b.id; }
  }
  return best;
}

// ─── generation ──────────────────────────────────────────────────────────────

/**
 * Walk the tree on a budget. Used to build every AI in the house, and available
 * to the UI as an "auto-spend" for players who do not want to plan a build.
 *
 * `intent` biases which branches get the money. Without it, a random walk
 * produces fifteen Drifters, because uniform spending across a three-trunk tree
 * is definitionally centreless. The house needs shapes, so every AI is handed a
 * plan before it starts spending.
 */
function randomBuild(rng, budget, intent) {
  const owned = new Set();
  let left = budget;
  const want = intent || {};

  /* Roots first for whichever trunks the intent touches. Cheap, and without
     them nothing else in the trunk is reachable. */
  const trunkOrder = ['comp', 'floor', 'long']
    .filter((t) => (want[t] || 0) > 0)
    .sort((x, y) => (want[y] || 0) - (want[x] || 0));
  for (const t of trunkOrder) {
    if (left >= 1) { owned.add(`${t}.root`); left -= 1; }
  }
  if (!owned.size) { owned.add('comp.root'); left -= 1; }

  let guard = 400;
  while (left > 0 && guard-- > 0) {
    const opts = available(owned).filter((n) => n.cost <= left);
    if (!opts.length) break;
    /* Weight by intent for the node's trunk, and lean toward cheap nodes so a
       small budget buys breadth rather than stalling in front of one tier-5. */
    const weights = opts.map((n) => {
      const w = n.trunk ? (want[n.trunk] || 0.05) : 0.4;
      return w * (10 / (n.cost + 4));
    });
    const pick = rng.weighted(opts, weights);
    owned.add(pick.id);
    left -= pick.cost;
  }
  return owned;
}

/** A random plan for one AI: one trunk they mean it about, one they dabble in. */
function randomIntent(rng) {
  const ts = rng.shuffle(['comp', 'floor', 'long'].slice());
  const lead = rng.range(0.5, 0.8);
  const secondShare = rng.range(0.05, 1 - lead);
  const intent = {};
  intent[ts[0]] = lead;
  intent[ts[1]] = secondShare;
  intent[ts[2]] = Math.max(0.02, 1 - lead - secondShare);
  return intent;
}

// ─── levels ──────────────────────────────────────────────────────────────────

const LEVEL_CAP = 60;

/* XP to reach level n from level 1. Quadratic, so early levels come fast enough
   that a first session pays out and late levels are a real commitment. */
function xpForLevel(n) {
  if (n <= 1) return 0;
  return Math.round(60 * (n - 1) + 8 * (n - 1) * (n - 1));
}

function levelForXp(xp) {
  let lv = 1;
  while (lv < LEVEL_CAP && xp >= xpForLevel(lv + 1)) lv++;
  return lv;
}

/* One token a level, two more at every fifth. 84 tokens at cap against a tree
   that costs TREE_TOTAL_COST, which is the "you can never buy the tree"
   property from GDD §4. The simulator prints the ratio; if this file changes,
   read it there rather than trusting this comment. */
function tokensForLevel(lv) {
  return lv + Math.floor(lv / 5) * 2;
}

const FINISH_XP = [0, 500, 425, 375, 340, 300, 265, 225, 200, 175, 150, 125, 100, 75, 60, 40, 25];

/** XP for a finishing position, 1 is the winner and 16 is the first evicted. */
function xpForFinish(place) {
  return FINISH_XP[Math.max(1, Math.min(16, place))] || 25;
}

const api = {
  COMP_ATTRS, SOCIAL_ATTRS, ALL_ATTRS, BASE_ATTRS, UNBUYABLE, ATTR_MIN, ATTR_MAX,
  TRUNKS, BRANCHES, NODES, BY_ID, TREE_TOTAL_COST, TIER_COST, TIER_GRANT,
  canBuy, available, spend, deriveAttributes, splitAttributes,
  resolveArchetype, BASE_NAME, HYBRID, BRANCH_NAME, SHARE,
  randomBuild, randomIntent,
  LEVEL_CAP, xpForLevel, levelForXp, tokensForLevel, xpForFinish,
};

if (typeof module !== 'undefined' && module.exports) module.exports = api;
if (typeof window !== 'undefined') window.RH_TREE = api;

})();
