/* Run The Arcade — Daily Crossword puzzles.
 * GENERATED by scripts/generate.mjs from data/baseball.json — do not hand-edit.
 * Pipeline: extraction (GDD §5) -> template clues (§4) -> fill (§6) -> difficulty (§7).
 * Every entry is a baseball answer whose clue is generated from the dataset row.
 * 7 daily puzzles; the UI serves today's by date (falls back to the first).
 */
window.RTG_PUZZLES = {
  version: 2,
  sport: "baseball",
  puzzles: [
  {
    "id": "2026-07-22",
    "date": "2026-07-22",
    "size": 5,
    "rows": [
      "BERRA",
      "A###A",
      "STARR",
      "E###O",
      "SABAN"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "BERRA",
        "clue": "Yankees Hall of Famer, a catcher famous for his malaprops"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "BASES",
        "clue": "There are three of them to round"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "AARON",
        "clue": "Braves Hall of Famer, the longtime home run king with 755"
      },
      {
        "num": 3,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "STARR",
        "clue": "Packers Hall of Famer, a 1960s star"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "SABAN",
        "clue": "LSU coach Nick ___"
      }
    ],
    "difficulty": 2.6,
    "sport": "baseball"
  },
  {
    "id": "2026-07-23",
    "date": "2026-07-23",
    "size": 5,
    "rows": [
      "S#F#R",
      "MIAMI",
      "I#V#L",
      "TORRE",
      "H#E#Y"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "SMITH",
        "clue": "Cowboys great, a 2000s star"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "FAVRE",
        "clue": "Packers great, a 2000s star"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "RILEY",
        "clue": "Lakers coach Pat ___"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "MIAMI",
        "clue": "ACC school, the Hurricanes"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 3,
        "c": 0,
        "answer": "TORRE",
        "clue": "Yankees manager Joe ___"
      }
    ],
    "difficulty": 2.4,
    "sport": "baseball"
  },
  {
    "id": "2026-07-24",
    "date": "2026-07-24",
    "size": 5,
    "rows": [
      "WHITE",
      "A#R#L",
      "L#V#W",
      "S#I#A",
      "HENRY"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "WHITE",
        "clue": "Eagles Hall of Famer, a 1990s star"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "WALSH",
        "clue": "49ers coach Bill ___"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "IRVIN",
        "clue": "Cowboys Hall of Famer, a 1990s star"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "ELWAY",
        "clue": "Broncos Hall of Famer, a 1990s star"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "HENRY",
        "clue": "Titans standout, nicknamed \"King Henry\""
      }
    ],
    "difficulty": 3,
    "sport": "baseball"
  },
  {
    "id": "2026-07-25",
    "date": "2026-07-25",
    "size": 5,
    "rows": [
      "#USC#",
      "B#P#O",
      "YOUNT",
      "U#R#T",
      "#LSU#"
    ],
    "theme": 6,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 1,
        "answer": "USC",
        "clue": "Big Ten school, the Trojans"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "SPURS",
        "clue": "San Antonio's NBA team"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 1,
        "c": 0,
        "answer": "BYU",
        "clue": "Big 12 school, the Cougars"
      },
      {
        "num": 4,
        "dir": "D",
        "r": 1,
        "c": 4,
        "answer": "OTT",
        "clue": "Giants Hall of Famer, a 500-home-run outfielder"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "YOUNT",
        "clue": "Brewers Hall of Famer, a two-time AL MVP"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 4,
        "c": 1,
        "answer": "LSU",
        "clue": "SEC school, the Tigers"
      }
    ],
    "difficulty": 2.33,
    "sport": "baseball"
  },
  {
    "id": "2026-07-26",
    "date": "2026-07-26",
    "size": 5,
    "rows": [
      "SPURS",
      "#L#U#",
      "WALSH",
      "#T#S#",
      "TEXAS"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "SPURS",
        "clue": "San Antonio's NBA team"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "PLATE",
        "clue": "Home ___ (where runs score)"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 3,
        "answer": "RUSSA",
        "clue": "White Sox manager Tony La ___"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "WALSH",
        "clue": "49ers coach Bill ___"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "TEXAS",
        "clue": "SEC school, the Longhorns"
      }
    ],
    "difficulty": 2,
    "sport": "baseball"
  },
  {
    "id": "2026-07-27",
    "date": "2026-07-27",
    "size": 5,
    "rows": [
      "#SLAM",
      "K#E#A",
      "ELWAY",
      "R#I#S",
      "ROSE#"
    ],
    "theme": 6,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 1,
        "answer": "SLAM",
        "clue": "Grand ___ (bases-loaded homer)"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "LEWIS",
        "clue": "Ravens Hall of Famer, a 2000s star"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "MAYS",
        "clue": "Giants Hall of Famer, the 'Say Hey Kid'"
      },
      {
        "num": 4,
        "dir": "D",
        "r": 1,
        "c": 0,
        "answer": "KERR",
        "clue": "Warriors coach Steve ___"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "ELWAY",
        "clue": "Broncos great, a 1990s star"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "ROSE",
        "clue": "Reds star, baseball's all-time hits leader with 4,256"
      }
    ],
    "difficulty": 2.83,
    "sport": "baseball"
  },
  {
    "id": "2026-07-28",
    "date": "2026-07-28",
    "size": 5,
    "rows": [
      "BAT#B",
      "E#WAR",
      "A#I#E",
      "RUN#T",
      "S#SET"
    ],
    "theme": 6,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "BAT",
        "clue": "Louisville Slugger, e.g."
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "BEARS",
        "clue": "Chicago's NFL team"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "TWINS",
        "clue": "Minnesota's AL team"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "BRETT",
        "clue": "Royals great, a lifetime .305 hitter"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 2,
        "answer": "WAR",
        "clue": "Stat-line shorthand: wins above replacement"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 3,
        "c": 0,
        "answer": "RUN",
        "clue": "It scores when you cross the plate"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.29,
    "sport": "baseball"
  }
],
  get daily() {
    var today = new Date().toISOString().slice(0, 10);
    return this.puzzles.find(function (p) { return p.id === today; }) || this.puzzles[0];
  },
};
