/* =============================================================================
 * RunTheGrid — spec-corpus importer
 *
 *   node grid/import-corpus.js [path]     (default grid/data/corpus.json)
 *
 * Converts a design-spec-schema corpus (entity_type/attributes/fame_tier, all
 * values as arrays — §3 of the spec) into the compact entity format the Daily
 * Match generator loads (grid/match/entities.js). Resolves team ids to display
 * names, maps position codes to readable names, and carries the axes the corpus
 * actually populates: teams, jersey, position, decades active, nationality,
 * Hall of Fame, name-is-also, plus awards/draft/milestones when present.
 *
 * Wordplay (surname/initials/alliterative) is derived from the name by the
 * generator, so it isn't copied here.
 * ========================================================================== */
'use strict';
var fs = require('fs'), path = require('path');
var SRC = process.argv[2] || path.join(__dirname, 'data', 'corpus.json');
var OUT = path.join(__dirname, 'match', 'entities.js');

var corpus = JSON.parse(fs.readFileSync(SRC, 'utf8'));

// team id -> display name
var teamName = {};
corpus.forEach(function (e) { if (e.entity_type === 'team') teamName[e.id] = e.display_name; });

// position code -> readable, per sport (codes collide across sports)
var POS = {
  NBA: { PG: 'Point Guard', SG: 'Shooting Guard', SF: 'Small Forward', PF: 'Power Forward', C: 'Center', G: 'Guard', F: 'Forward' },
  WNBA: { PG: 'Point Guard', SG: 'Shooting Guard', SF: 'Small Forward', PF: 'Power Forward', C: 'Center', G: 'Guard', F: 'Forward' },
  NFL: { QB: 'Quarterback', RB: 'Running Back', FB: 'Fullback', WR: 'Wide Receiver', TE: 'Tight End', OL: 'Offensive Lineman', OT: 'Offensive Lineman', OG: 'Offensive Lineman', C: 'Center', DL: 'Defensive Lineman', DE: 'Defensive Lineman', DT: 'Defensive Lineman', LB: 'Linebacker', CB: 'Cornerback', S: 'Safety', SS: 'Safety', FS: 'Safety', DB: 'Defensive Back', K: 'Kicker', P: 'Punter' },
  MLB: { P: 'Pitcher', SP: 'Pitcher', RP: 'Pitcher', C: 'Catcher', '1B': 'First Baseman', '2B': 'Second Baseman', '3B': 'Third Baseman', SS: 'Shortstop', LF: 'Outfielder', CF: 'Outfielder', RF: 'Outfielder', OF: 'Outfielder', DH: 'Designated Hitter' },
  NHL: { C: 'Center', LW: 'Left Wing', RW: 'Right Wing', W: 'Winger', D: 'Defenseman', G: 'Goaltender' }
};
function readablePos(sport, code) { return (POS[sport] && POS[sport][code]) || null; }

function first(arr) { return Array.isArray(arr) && arr.length ? arr[0] : null; }
function arr(a) { return Array.isArray(a) ? a : []; }

var players = corpus.filter(function (e) { return e.entity_type === 'player' || e.entity_type === 'athlete'; });
var out = [];
players.forEach(function (p) {
  var a = p.attributes || {};
  var e = { id: p.id, name: p.display_name, sport: p.sport, f: p.fame_tier };

  var teams = arr(a.teams).map(function (id) { return teamName[id] || null; }).filter(Boolean);
  if (teams.length) e.t = teams;

  var jerseys = arr(a.jersey_number).filter(function (n) { return typeof n === 'number'; });
  if (jerseys.length) e.j = jerseys;

  var pos = readablePos(p.sport, first(a.primary_position));
  if (pos) e.pos = pos;

  var decs = arr(a.decades_active).filter(function (n) { return typeof n === 'number'; });
  if (decs.length) e.decade = decs;

  var nat = first(a.nationality);
  if (nat) e.nat = nat;

  if (first(a.hall_of_fame) === true) e.hof = true;

  var na = arr(a.name_is_also).filter(Boolean);
  if (na.length) e.na = na;

  // achievement/stat axes — carried through for when the corpus fills them in
  if (arr(a.awards).length) e.aw = arr(a.awards);
  if (arr(a.milestones).length) e.ml = arr(a.milestones);
  if (first(a.draft_position) === 1) e.dp = 1;
  var dy = first(a.draft_year); if (typeof dy === 'number') e.dy = dy;

  out.push(e);
});

var header = '/* GENERATED by grid/import-corpus.js from grid/data/corpus.json — DO NOT EDIT BY HAND. */\n';
var body = '(function (root, factory) {\n' +
  '  var mod = factory();\n' +
  '  if (typeof module !== "undefined" && module.exports) module.exports = mod;\n' +
  '  else root.GRID_ENTITIES = mod;\n' +
  '})(typeof self !== "undefined" ? self : this, function () {\n' +
  '  "use strict";\n  return ' + JSON.stringify(out) + ';\n});\n';
fs.writeFileSync(OUT, header + body);

// report
function dist(list, f) { var d = {}; list.forEach(function (x) { var k = f(x); d[k] = (d[k] || 0) + 1; }); return d; }
console.log('=== import-corpus ===');
console.log('  players imported: ' + out.length);
console.log('  by sport: ' + JSON.stringify(dist(out, function (e) { return e.sport; })));
console.log('  with teams: ' + out.filter(function (e) { return e.t; }).length +
  ', jersey: ' + out.filter(function (e) { return e.j; }).length +
  ', position: ' + out.filter(function (e) { return e.pos; }).length +
  ', decades: ' + out.filter(function (e) { return e.decade; }).length +
  ', HOF: ' + out.filter(function (e) { return e.hof; }).length +
  ', name_is_also: ' + out.filter(function (e) { return e.na; }).length +
  ', awards: ' + out.filter(function (e) { return e.aw; }).length);
console.log('  -> wrote ' + out.length + ' entities to match/entities.js');
