/* RunTheGrid — Daily Crossword puzzles.
 * GENERATED by scripts/generate.mjs from data/baseball.json — do not hand-edit.
 * Pipeline: extraction (GDD §5) -> template clues (§4) -> fill (§6) -> difficulty (§7).
 * Every entry is a baseball answer whose clue is generated from the dataset row.
 * 7 daily puzzles; the UI serves today's by date (falls back to the first).
 */
window.RTG_PUZZLES = {
  version: 2,
  sport: "baseball",
  puzzles: [
  {
    "id": "2026-07-22",
    "date": "2026-07-22",
    "size": 5,
    "rows": [
      "ERA##",
      "REND#",
      "RATIO",
      "#DENT",
      "##SET"
    ],
    "theme": 2,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERA",
        "clue": "Box-score abbr. for earned run average"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "ERR",
        "clue": "Slip up"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "READ",
        "clue": "Peruse a book"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ANTES",
        "clue": "Pot starters"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "REND",
        "clue": "Tear apart"
      },
      {
        "num": 5,
        "dir": "D",
        "r": 1,
        "c": 3,
        "answer": "DINE",
        "clue": "Have supper"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "RATIO",
        "clue": "Proportion"
      },
      {
        "num": 7,
        "dir": "D",
        "r": 2,
        "c": 4,
        "answer": "OTT",
        "clue": "Giants great Mel ___"
      },
      {
        "num": 8,
        "dir": "A",
        "r": 3,
        "c": 1,
        "answer": "DENT",
        "clue": "Fender ding"
      },
      {
        "num": 9,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.9,
    "sport": "baseball"
  },
  {
    "id": "2026-07-23",
    "date": "2026-07-23",
    "size": 5,
    "rows": [
      "ERA##",
      "RENT#",
      "RATIO",
      "#DENT",
      "##SET"
    ],
    "theme": 2,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERA",
        "clue": "Box-score abbr. for earned run average"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "ERR",
        "clue": "Slip up"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "READ",
        "clue": "Peruse a book"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ANTES",
        "clue": "Pot starters"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "RENT",
        "clue": "Monthly payment"
      },
      {
        "num": 5,
        "dir": "D",
        "r": 1,
        "c": 3,
        "answer": "TINE",
        "clue": "Fork point"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "RATIO",
        "clue": "Proportion"
      },
      {
        "num": 7,
        "dir": "D",
        "r": 2,
        "c": 4,
        "answer": "OTT",
        "clue": "Mel ___, a 500-home-run outfielder"
      },
      {
        "num": 8,
        "dir": "A",
        "r": 3,
        "c": 1,
        "answer": "DENT",
        "clue": "Fender ding"
      },
      {
        "num": 9,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.9,
    "sport": "baseball"
  },
  {
    "id": "2026-07-24",
    "date": "2026-07-24",
    "size": 5,
    "rows": [
      "ERA##",
      "RENT#",
      "RATIO",
      "#DENT",
      "##SET"
    ],
    "theme": 2,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERA",
        "clue": "Stat-line shorthand: earned run average"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "ERR",
        "clue": "Slip up"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "READ",
        "clue": "Peruse a book"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ANTES",
        "clue": "Pot starters"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "RENT",
        "clue": "Monthly payment"
      },
      {
        "num": 5,
        "dir": "D",
        "r": 1,
        "c": 3,
        "answer": "TINE",
        "clue": "Fork point"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "RATIO",
        "clue": "Proportion"
      },
      {
        "num": 7,
        "dir": "D",
        "r": 2,
        "c": 4,
        "answer": "OTT",
        "clue": "Hall of Famer Mel ___"
      },
      {
        "num": 8,
        "dir": "A",
        "r": 3,
        "c": 1,
        "answer": "DENT",
        "clue": "Fender ding"
      },
      {
        "num": 9,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.9,
    "sport": "baseball"
  },
  {
    "id": "2026-07-25",
    "date": "2026-07-25",
    "size": 5,
    "rows": [
      "ERA##",
      "REND#",
      "RATIO",
      "#DENT",
      "##SET"
    ],
    "theme": 2,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERA",
        "clue": "Box-score abbr. for earned run average"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "ERR",
        "clue": "Slip up"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "READ",
        "clue": "Peruse a book"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ANTES",
        "clue": "Pot starters"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "REND",
        "clue": "Tear apart"
      },
      {
        "num": 5,
        "dir": "D",
        "r": 1,
        "c": 3,
        "answer": "DINE",
        "clue": "Have supper"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "RATIO",
        "clue": "Proportion"
      },
      {
        "num": 7,
        "dir": "D",
        "r": 2,
        "c": 4,
        "answer": "OTT",
        "clue": "Hall of Famer Mel ___"
      },
      {
        "num": 8,
        "dir": "A",
        "r": 3,
        "c": 1,
        "answer": "DENT",
        "clue": "Fender ding"
      },
      {
        "num": 9,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.9,
    "sport": "baseball"
  },
  {
    "id": "2026-07-26",
    "date": "2026-07-26",
    "size": 5,
    "rows": [
      "ERA##",
      "RENT#",
      "RATIO",
      "#DENT",
      "##SET"
    ],
    "theme": 2,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERA",
        "clue": "Stat-line shorthand: earned run average"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "ERR",
        "clue": "Slip up"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "READ",
        "clue": "Peruse a book"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ANTES",
        "clue": "Pot starters"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "RENT",
        "clue": "Monthly payment"
      },
      {
        "num": 5,
        "dir": "D",
        "r": 1,
        "c": 3,
        "answer": "TINE",
        "clue": "Fork point"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "RATIO",
        "clue": "Proportion"
      },
      {
        "num": 7,
        "dir": "D",
        "r": 2,
        "c": 4,
        "answer": "OTT",
        "clue": "Hall of Famer Mel ___"
      },
      {
        "num": 8,
        "dir": "A",
        "r": 3,
        "c": 1,
        "answer": "DENT",
        "clue": "Fender ding"
      },
      {
        "num": 9,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.9,
    "sport": "baseball"
  },
  {
    "id": "2026-07-27",
    "date": "2026-07-27",
    "size": 5,
    "rows": [
      "ERA##",
      "RENT#",
      "RATIO",
      "#DENT",
      "##SET"
    ],
    "theme": 2,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERA",
        "clue": "Stat-line shorthand: earned run average"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "ERR",
        "clue": "Slip up"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "READ",
        "clue": "Peruse a book"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ANTES",
        "clue": "Pot starters"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "RENT",
        "clue": "Monthly payment"
      },
      {
        "num": 5,
        "dir": "D",
        "r": 1,
        "c": 3,
        "answer": "TINE",
        "clue": "Fork point"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "RATIO",
        "clue": "Proportion"
      },
      {
        "num": 7,
        "dir": "D",
        "r": 2,
        "c": 4,
        "answer": "OTT",
        "clue": "Mel ___, a 500-home-run outfielder"
      },
      {
        "num": 8,
        "dir": "A",
        "r": 3,
        "c": 1,
        "answer": "DENT",
        "clue": "Fender ding"
      },
      {
        "num": 9,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.9,
    "sport": "baseball"
  },
  {
    "id": "2026-07-28",
    "date": "2026-07-28",
    "size": 5,
    "rows": [
      "ERA##",
      "REND#",
      "RATIO",
      "#DENT",
      "##SET"
    ],
    "theme": 2,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERA",
        "clue": "Stat-line shorthand: earned run average"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "ERR",
        "clue": "Slip up"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "READ",
        "clue": "Peruse a book"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ANTES",
        "clue": "Pot starters"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "REND",
        "clue": "Tear apart"
      },
      {
        "num": 5,
        "dir": "D",
        "r": 1,
        "c": 3,
        "answer": "DINE",
        "clue": "Have supper"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "RATIO",
        "clue": "Proportion"
      },
      {
        "num": 7,
        "dir": "D",
        "r": 2,
        "c": 4,
        "answer": "OTT",
        "clue": "Mel ___, a 500-home-run outfielder"
      },
      {
        "num": 8,
        "dir": "A",
        "r": 3,
        "c": 1,
        "answer": "DENT",
        "clue": "Fender ding"
      },
      {
        "num": 9,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "SET",
        "clue": "Tennis-match division"
      }
    ],
    "difficulty": 2.9,
    "sport": "baseball"
  }
],
  get daily() {
    var today = new Date().toISOString().slice(0, 10);
    return this.puzzles.find(function (p) { return p.id === today; }) || this.puzzles[0];
  },
};
