/* RunTheGrid — Daily Crossword puzzles.
 * GENERATED by scripts/generate.mjs from data/baseball.json — do not hand-edit.
 * Pipeline: extraction (GDD §5) -> template clues (§4) -> fill (§6) -> difficulty (§7).
 * Every entry is a baseball answer whose clue is generated from the dataset row.
 * 7 daily puzzles; the UI serves today's by date (falls back to the first).
 */
window.RTG_PUZZLES = {
  version: 2,
  sport: "baseball",
  puzzles: [
  {
    "id": "2026-07-22",
    "date": "2026-07-22",
    "size": 5,
    "rows": [
      "BERRA",
      "A###A",
      "STARR",
      "E###O",
      "SABAN"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "BERRA",
        "clue": "Yogi ___, a catcher famous for his malaprops"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "BASES",
        "clue": "There are three of them to round"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "AARON",
        "clue": "Hank ___, the longtime home run king with 755"
      },
      {
        "num": 3,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "STARR",
        "clue": "Packers great Bart ___"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "SABAN",
        "clue": "NCAA coach Nick ___"
      }
    ],
    "difficulty": 2.6,
    "sport": "baseball"
  },
  {
    "id": "2026-07-23",
    "date": "2026-07-23",
    "size": 5,
    "rows": [
      "T#W#T",
      "OLAVE",
      "R#L#X",
      "RUSSA",
      "E#H#S"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "TORRE",
        "clue": "MLB coach Joe ___"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "WALSH",
        "clue": "NFL coach Bill ___"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "TEXAS",
        "clue": "SEC school, the Longhorns"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 0,
        "answer": "OLAVE",
        "clue": "Chris ___, a 2020s star"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 3,
        "c": 0,
        "answer": "RUSSA",
        "clue": "MLB coach Tony La ___"
      }
    ],
    "difficulty": 2.4,
    "sport": "baseball"
  },
  {
    "id": "2026-07-24",
    "date": "2026-07-24",
    "size": 5,
    "rows": [
      "SUGGS",
      "T#A#H",
      "A#T#U",
      "R#E#L",
      "RUSSA"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "SUGGS",
        "clue": "Terrell ___, a 2000s star"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "STARR",
        "clue": "Hall of Famer Bart ___"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "GATES",
        "clue": "Antonio ___, a 2000s star"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "SHULA",
        "clue": "NFL coach Don ___"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "RUSSA",
        "clue": "MLB coach Tony La ___"
      }
    ],
    "difficulty": 2.8,
    "sport": "baseball"
  },
  {
    "id": "2026-07-25",
    "date": "2026-07-25",
    "size": 5,
    "rows": [
      "#ERA#",
      "H#I#L",
      "BULLS",
      "P#E#U",
      "#BYU#"
    ],
    "theme": 6,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 1,
        "answer": "ERA",
        "clue": "Stat-line shorthand: earned run average"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "RILEY",
        "clue": "NBA coach Pat ___"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 1,
        "c": 0,
        "answer": "HBP",
        "clue": "Box-score abbr. for hit by pitch"
      },
      {
        "num": 4,
        "dir": "D",
        "r": 1,
        "c": 4,
        "answer": "LSU",
        "clue": "SEC school, the Tigers"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "BULLS",
        "clue": "Chicago's NBA team"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 4,
        "c": 1,
        "answer": "BYU",
        "clue": "Big 12 school, the Cougars"
      }
    ],
    "difficulty": 2,
    "sport": "baseball"
  },
  {
    "id": "2026-07-26",
    "date": "2026-07-26",
    "size": 5,
    "rows": [
      "SPURS",
      "#L#U#",
      "WALSH",
      "#T#S#",
      "TEXAS"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "SPURS",
        "clue": "San Antonio's NBA team"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 1,
        "answer": "PLATE",
        "clue": "Home ___ (where runs score)"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 3,
        "answer": "RUSSA",
        "clue": "MLB coach Tony La ___"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "WALSH",
        "clue": "NFL coach Bill ___"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "TEXAS",
        "clue": "SEC school, the Longhorns"
      }
    ],
    "difficulty": 2,
    "sport": "baseball"
  },
  {
    "id": "2026-07-27",
    "date": "2026-07-27",
    "size": 5,
    "rows": [
      "#REID",
      "S#L#A",
      "LEWIS",
      "A#A#H",
      "MAYE#"
    ],
    "theme": 5,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 1,
        "answer": "REID",
        "clue": "NFL coach Andy ___"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "ELWAY",
        "clue": "Hall of Famer John ___"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "DASH",
        "clue": "Short sprint race"
      },
      {
        "num": 4,
        "dir": "D",
        "r": 1,
        "c": 0,
        "answer": "SLAM",
        "clue": "Grand ___ (bases-loaded homer)"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 2,
        "c": 0,
        "answer": "LEWIS",
        "clue": "Ravens great Ray ___"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 4,
        "c": 0,
        "answer": "MAYE",
        "clue": "Patriots star Drake ___"
      }
    ],
    "difficulty": 2.83,
    "sport": "baseball"
  },
  {
    "id": "2026-07-28",
    "date": "2026-07-28",
    "size": 5,
    "rows": [
      "ERS#K",
      "U#WAR",
      "R#I#A",
      "OPS#F",
      "S#HIT"
    ],
    "theme": 6,
    "entries": [
      {
        "num": 1,
        "dir": "A",
        "r": 0,
        "c": 0,
        "answer": "ERS",
        "clue": "San Francisco's NFL team"
      },
      {
        "num": 1,
        "dir": "D",
        "r": 0,
        "c": 0,
        "answer": "EUROS",
        "clue": "Soccer trophy"
      },
      {
        "num": 2,
        "dir": "D",
        "r": 0,
        "c": 2,
        "answer": "SWISH",
        "clue": "All-net basket"
      },
      {
        "num": 3,
        "dir": "D",
        "r": 0,
        "c": 4,
        "answer": "KRAFT",
        "clue": "Patriots owner Robert ___"
      },
      {
        "num": 4,
        "dir": "A",
        "r": 1,
        "c": 2,
        "answer": "WAR",
        "clue": "Box-score abbr. for wins above replacement"
      },
      {
        "num": 5,
        "dir": "A",
        "r": 3,
        "c": 0,
        "answer": "OPS",
        "clue": "Stat-line shorthand: on-base plus slugging"
      },
      {
        "num": 6,
        "dir": "A",
        "r": 4,
        "c": 2,
        "answer": "HIT",
        "clue": "Single, double, or triple"
      }
    ],
    "difficulty": 2.14,
    "sport": "baseball"
  }
],
  get daily() {
    var today = new Date().toISOString().slice(0, 10);
    return this.puzzles.find(function (p) { return p.id === today; }) || this.puzzles[0];
  },
};
