/* PACK A GENERATED DATA FILE SO THE PHONE DOES LESS WORK OPENING IT.
 *
 * The arcade's generated datasets are written as JavaScript object literals,
 * one object per player, every field name spelled out on every row:
 *
 *   {"id":"former:nfl:00-0032889","name":"A'Shawn Robinson","sport":"NFL",
 *    "t":["Detroit Lions","Los Angeles Rams", ...],"col":"Alabama", ...}
 *
 * Across former.js's 5434 players that is 366 KB of field names and 298 KB of
 * team names re-spelled, out of a 1225 KB file. The same 170 team strings and
 * 507 college strings are written over and over.
 *
 * Packing writes the field names once as a header, each repeated string once in
 * a dictionary, and every row as an array of indices. former.js goes from
 * 1225 KB to 467 KB, and the part a browser cannot compress away goes with it.
 *
 * WHY THIS IS WORTH DOING WHEN CLOUDFLARE ALREADY COMPRESSES. Because gzip is
 * not the cost. On the wire former.js is about 171 KB either way (packed: 128).
 * The cost is PARSING: a megabyte of object literal is a megabyte the main
 * thread reads before the game can start, and compression does nothing for it.
 * Measured in Chromium, fetch and parse of the verbose file is 130 to 180 ms,
 * and of the packed file plus decoding every row back into objects is 30 to
 * 70 ms. On a mid-range phone that gap is several times larger.
 *
 * WHAT IT DOES NOT CHANGE. The global each file defines, and the objects it
 * hands out. `window.RTG_FORMER.players[0].col` is the same string it was.
 * Every consumer (data.js, the games, check-colleges.mjs) is untouched, because
 * the decoder ships INSIDE the generated file and runs before the global is
 * assigned. That is deliberate: a decoder in a separate script would be a new
 * load-order dependency on fifteen pages and a new way to ship a broken one.
 *
 * USE
 *   import { packFile } from './lib/packdata.mjs';
 *   writeFileSync('arcade/former.js', packFile({
 *     global: 'RTG_FORMER', key: 'players', rows: out,
 *     meta: { updated: today, count: out.length },
 *     banner: 'GENERATED by scripts/fetch-former.mjs. Do not edit.'
 *   }));
 *
 * The unpacker below is exported too, so a check can decode a packed file in
 * node without a browser, and so the encoder and the decoder can be asserted
 * against each other rather than trusted.
 */

/* A column is worth a dictionary when its values repeat enough to pay for the
   dictionary itself. Team names repeat 170 ways across 20000 mentions and are
   a clear yes; a player id is unique per row and is a clear no. The threshold
   is deliberately loose: the cost of dictionarying a column that did not need
   it is a few bytes, and the cost of missing one is hundreds of KB. */
const WORTH_IT = (distinct, total) => total >= 24 && distinct <= total * 0.6;

const isStr = (v) => typeof v === 'string';
const isStrArray = (v) => Array.isArray(v) && v.length > 0 && v.every(isStr);

/* Pack an array of flat objects into { k, d, a, r }.
 *
 *   k  field names, in a fixed order. Every row is an array in this order.
 *   d  colIndex -> dictionary, for columns holding a plain string.
 *   a  colIndex -> dictionary, for columns holding an array of strings.
 *   r  the rows.
 *
 * A dictionaried value is its index, or -1 for null/undefined/absent. A value
 * in no dictionary is written as it is, so numbers, booleans and arrays of
 * numbers ride through untouched.
 */
export function pack(rows) {
  const keys = [];
  const seenKey = Object.create(null);
  for (const row of rows) {
    for (const k of Object.keys(row)) {
      if (!seenKey[k]) { seenKey[k] = 1; keys.push(k); }
    }
  }

  const d = {}, a = {};
  keys.forEach((k, i) => {
    let strings = 0, strArrays = 0, present = 0, other = 0;
    const distinct = new Set();
    for (const row of rows) {
      const v = row[k];
      if (v === undefined || v === null) continue;
      present++;
      if (isStr(v)) { strings++; distinct.add(v); }
      else if (isStrArray(v)) { strArrays++; for (const s of v) distinct.add(s); }
      else other++;
    }
    if (!present || other) return;                  // mixed or non-string: leave it alone
    if (strings && strArrays) return;               // a column that is sometimes both
    const mentions = strings || rows.reduce((n, row) => n + ((row[k] || []).length || 0), 0);
    if (!WORTH_IT(distinct.size, mentions)) return;
    const table = [...distinct];
    (strings ? d : a)[i] = table;
  });

  const index = {};
  for (const col of [...Object.keys(d), ...Object.keys(a)]) {
    const m = new Map();
    const table = d[col] || a[col];
    table.forEach((s, n) => m.set(s, n));
    index[col] = m;
  }

  const r = rows.map((row) => keys.map((k, i) => {
    const v = row[k];
    if (d[i]) return (v === undefined || v === null) ? -1 : index[i].get(v);
    if (a[i]) return (v === undefined || v === null) ? [] : v.map((s) => index[i].get(s));
    return v === undefined ? null : v;
  }));

  return { k: keys, d, a, r };
}

/* The decoder, as a string, because it has to ship inside the generated file.
   Written in ES5 with no dependencies: these files load on every arcade page
   ahead of everything else, and one of them failing to parse takes the game
   with it. Kept in one place so the shape below and `unpack` below that can
   never drift from each other. */
const DECODER = `function U(P){
var k=P.k,d=P.d||{},a=P.a||{},mk=P.mk,out=(mk==null?[]:{}),i,j,n,row,o,t,key;
for(i=0;i<P.r.length;i++){
  row=P.r[i];o={};key=null;
  for(j=0;j<k.length;j++){
    t=row[j];
    if(d[j]){t=(t<0?null:d[j][t]);}
    else if(a[j]){n=[];for(var m=0;m<t.length;m++)n.push(a[j][t[m]]);t=n;}
    if(j===mk){key=t;}else{o[k[j]]=t;}
  }
  if(mk==null){out.push(o);}else{out[key]=o;}
}
return out;}`;

/* The same thing again in node, for the checks. If these two ever disagree the
   site ships data nothing verified, so check-packdata.mjs asserts that a file
   decoded by THIS function matches the file decoded by the one above, run in a
   browser-shaped sandbox. */
export function unpack(P) {
  const k = P.k, d = P.d || {}, a = P.a || {}, mk = P.mk;
  const out = mk == null ? [] : {};
  for (const row of P.r) {
    const o = {};
    let key = null;
    k.forEach((name, j) => {
      let t = row[j];
      if (d[j]) t = (t < 0 ? null : d[j][t]);
      else if (a[j]) t = t.map((n) => a[j][n]);
      if (j === mk) key = t; else o[name] = t;
    });
    if (mk == null) out.push(o); else out[key] = o;
  }
  return out;
}

/* Render the whole file: banner, packed payload, decoder, the assignment.
 *
 * `meta` is carried verbatim and spread back over the result, so a file that
 * used to expose { updated, count, players } still exposes all three. Any
 * meta key that collides with `key` would silently win or lose depending on
 * order, so it is rejected rather than resolved. */
export function packFile({ global, key, rows, meta = {}, banner = '', extra = {}, mapKey = null }) {
  if (Object.prototype.hasOwnProperty.call(meta, key)) {
    throw new Error(`meta must not carry "${key}": it is the packed array's own name`);
  }
  const P = pack(rows);
  /* `mapKey` names the field whose value becomes the object key, for the files
     that expose a lookup rather than a list (awards.js is keyed by
     "SPORT|name"). The field is dropped from the decoded object, so the shape
     on the other side is exactly what it was before packing. */
  if (mapKey != null) {
    const at = P.k.indexOf(mapKey);
    if (at < 0) throw new Error(`mapKey "${mapKey}" is not a field on these rows`);
    P.mk = at;
  }
  const head = banner ? banner.split('\n').map((l) => ' * ' + l).join('\n') : null;
  const extras = Object.keys(extra).length
    ? Object.keys(extra).map((k) => JSON.stringify(k) + ':' + JSON.stringify(extra[k])).join(',') + ','
    : '';
  return (head ? '/*\n' + head + '\n */\n' : '') +
    'window.' + global + '=(function(){\n' +
    'var P=' + JSON.stringify(P) + ';\n' +
    DECODER + '\n' +
    'var M=' + JSON.stringify(meta) + ';\n' +
    'return {' + Object.keys(meta).map((k) => JSON.stringify(k) + ':M[' + JSON.stringify(k) + ']').join(',') +
    (Object.keys(meta).length ? ',' : '') + extras +
    JSON.stringify(key) + ':U(P)};\n' +
    '})();\n';
}

/* Read a packed (or still-verbose) generated file the way a browser would, and
   hand back the global it defines. Used by the checks and by any generator
   that needs to re-pack a file it did not itself fetch. */
export function loadGlobal(source, name) {
  const box = {};
  // eslint-disable-next-line no-new-func
  new Function('window', 'self', 'globalThis', source)(box, box, box);
  return box[name];
}
