"""THE ARTIST'S ORDER SHEET, generated from the audit rather than typed.

    python3 tools/art_order.py

Writes docs/ART_ORDER.md. It is generated because a hand written order sheet
is a second copy of the audit, and the copy is the one that goes stale: the
strip gets fixed, the CSV knows, and the sheet somebody is working from does
not. Re-run it after every audit.

IT ORDERS OFF THE SECOND VERDICT, NOT THE FIRST. `classification` follows the
rule as specified, which condemns any frame touching a canvas edge. A baked
background touches both edges by definition, so that rule bills the artist for
20 strips whose art is intact behind a rectangle a flood fill removes. What is
ordered here is `classification_after_bg`, and the 20 are listed separately so
the decision is visible rather than buried.
"""
import csv
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPORTS = os.path.join(ROOT, 'reports')
DOCS = os.path.join(ROOT, 'docs')

ANIMS = ['idle', 'batting_stance', 'swing', 'pitch', 'run', 'celebrate']
FRAMES = {'idle': 2, 'batting_stance': 1, 'swing': 4, 'pitch': 4, 'run': 4, 'celebrate': 2}


def fault_line(r):
    """One plain sentence about what is wrong with this strip."""
    op = [int(x) for x in r['opaque_pixels_per_frame'].split(';')]
    bg = [int(x) for x in r['background_pixels_per_frame'].split(';')]
    x0 = [int(x) for x in r['edge_pixels_x0'].split(';')]
    x63 = [int(x) for x in r['edge_pixels_x63'].split(';')]
    bits = []
    for i in range(len(op)):
        after = op[i] - bg[i]
        if after < 200:
            bits.append('frame %d is empty (%d px of art)' % (i, max(after, 0)))
        elif x0[i] or x63[i]:
            side = 'both edges' if x0[i] and x63[i] else ('left edge' if x0[i] else 'right edge')
            bits.append('frame %d runs off the %s (%d px on the cut)'
                        % (i, side, max(x0[i], x63[i])))
    if r['identical_frame_pairs']:
        bits.append('frames %s are the same image' % r['identical_frame_pairs'])
    return '; '.join(bits) or 'see reports/audit.csv'


def main():
    rows = list(csv.DictReader(open(os.path.join(REPORTS, 'audit.csv'))))
    by_char = defaultdict(dict)
    for r in rows:
        by_char[r['character']][r['animation']] = r

    order = {c: [a for a in ANIMS
                 if a in by_char[c] and by_char[c][a]['classification_after_bg'] == 'NEEDS_ART']
             for c in sorted(by_char)}
    total = sum(len(v) for v in order.values())
    recovered = [r for r in rows if r['recovered_by_bg_removal'] == 'yes']

    omitted = []
    op = os.path.join(ROOT, 'omitted_characters.txt')
    if os.path.exists(op):
        omitted = [l.strip() for l in open(op) if l.strip()]

    out = []
    w = out.append
    w('# Art order')
    w('')
    w('Generated by `tools/art_order.py` from `reports/audit.csv`. Do not edit by')
    w('hand: re-run it after any audit, or this sheet and the measurements drift.')
    w('')
    w('## What is being asked for')
    w('')
    w('| | strips |')
    w('|---|---|')
    w('| in the pack | %d |' % len(rows))
    w('| usable after code repair | %d |' % (len(rows) - total))
    w('| **need new art** | **%d** |' % total)
    w('| characters with no strips at all | %d (%d strips)' % (len(omitted), len(omitted) * 6) + ' |')
    w('')
    w('**THE 20 STRIPS THAT LOOK BROKEN AND ARE NOT.** The brief classifies any')
    w('frame touching x=0 or x=63 as clipped past saving. That is right for a')
    w('character drawn off the canvas and wrong for one standing behind a baked')
    w('background, because a background reaches both edges by definition. These')
    w('%d strips are whole once a border flood takes the background off, so they' % len(recovered))
    w('are not on the order below. Check a few on the green contact sheet before')
    w('trusting it: they are the cells that read as a dark rectangle rather than')
    w('as green.')
    w('')
    for r in sorted(recovered, key=lambda r: r['strip']):
        w('- `%s`' % r['strip'])
    w('')
    w('## The order, by character')
    w('')
    w('A character with no row here needs nothing drawn. Frame numbers are zero')
    w('based and count from the left of the strip.')
    w('')
    for c in sorted(order):
        need = order[c]
        if not need:
            continue
        have = [a for a in ANIMS if a in by_char[c] and a not in need]
        w('### %s' % c)
        w('')
        w('%d of 6 to redraw. Still good: %s' % (len(need), ', '.join(have) if have else 'nothing'))
        w('')
        for a in need:
            r = by_char[c][a]
            w('- **%s** (%d frame%s): %s'
              % (a, FRAMES[a], '' if FRAMES[a] == 1 else 's', fault_line(r)))
        w('')

    if omitted:
        w('## Characters with no animation at all')
        w('')
        w('%d characters, %d strips. Nothing exists for these: every animation has'
          % (len(omitted), len(omitted) * 6))
        w('to be drawn from their static sprite in `source_reference/`. They are')
        w('playable meanwhile, standing still, because the runtime falls back to')
        w('that static sprite for every state.')
        w('')
        for c in omitted:
            w('- %s' % c)
        w('')

    w('## What counts as done')
    w('')
    w('Each strip is one PNG, frames laid out left to right, 64x64 each, the')
    w('character facing RIGHT. Left facing is produced by flipping at draw time,')
    w('so it must never be drawn or shipped.')
    w('')
    w('| animation | frames |')
    w('|---|---|')
    for a in ANIMS:
        w('| %s | %d |' % (a, FRAMES[a]))
    w('')
    w('Three things the audit will reject, so they are worth knowing before')
    w('drawing rather than after:')
    w('')
    w('- **Nothing may touch x=0 or x=63.** Leave a column of transparent pixels')
    w('  down both sides. A bat or a staff that reaches the edge has been cut off,')
    w('  and the missing part cannot be recovered from the file.')
    w('- **No background.** Transparent means transparent. A filled rectangle')
    w('  behind the character is removable but it hides the silhouette, and on a')
    w('  dark page nobody can see that it is there.')
    w('- **The feet land on y=62**, not y=63, so the character has a pixel of room')
    w('  under it. The repair pass shifts this, but only if there is art to shift.')
    w('')

    os.makedirs(DOCS, exist_ok=True)
    path = os.path.join(DOCS, 'ART_ORDER.md')
    open(path, 'w').write('\n'.join(out) + '\n')
    print('%d strips to draw across %d characters -> %s'
          % (total, sum(1 for v in order.values() if v), os.path.relpath(path, ROOT)))
    print('  plus %d characters with no strips at all (%d more)'
          % (len(omitted), len(omitted) * 6))
    print('  %d strips kept off the order because only a background ails them' % len(recovered))


if __name__ == '__main__':
    main()
