/* Fetch current NBA/NFL/MLB rosters from ESPN's public API and emit
 * arcade/rosters.js (window.RTG_ROSTERS). Run by .github/workflows/rosters.yml
 * on a schedule (Actions runners have open network); also runnable locally:
 *   node scripts/fetch-rosters.mjs
 */
import { writeFileSync } from 'fs';

const LEAGUES = [
  { sport: 'NBA', path: 'basketball/nba' },
  { sport: 'NFL', path: 'football/nfl' },
  { sport: 'MLB', path: 'baseball/mlb' },
];
const BASE = 'https://site.api.espn.com/apis/site/v2/sports/';

async function j(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(url + ' -> ' + r.status);
  return r.json();
}

const players = [];
const divisions = {};
for (const lg of LEAGUES) {
  const teams = (await j(BASE + lg.path + '/teams?limit=40')).sports[0].leagues[0].teams.map(t => t.team);
  for (const t of teams) {
    // division/conference via the team endpoint's standingSummary or groups
    try {
      const det = await j(BASE + lg.path + '/teams/' + t.id);
      const gp = det.team && det.team.groups;
      if (gp && gp.parent && gp.parent.name) divisions[t.displayName] = gp.parent.name;
      else if (det.team && det.team.standingSummary) divisions[t.displayName] = det.team.standingSummary.replace(/^\d+\w* in /, '');
    } catch (e) { /* division optional */ }
    const ros = await j(BASE + lg.path + '/teams/' + t.id + '/roster');
    const groups = ros.athletes || [];
    for (const g of groups) {
      for (const a of (g.items || [])) {
        players.push({
          n: a.fullName,
          s: lg.sport,
          t: t.displayName,
          p: (a.position && (a.position.displayName || a.position.name)) || null,
          j: a.jersey != null && a.jersey !== '' ? Number(a.jersey) : null,
        });
      }
    }
    await new Promise(res => setTimeout(res, 150)); // be polite
  }
  console.log(lg.sport, 'teams:', teams.length, 'players so far:', players.length);
}

const out =
  '/* GENERATED by scripts/fetch-rosters.mjs (ESPN public API). Do not edit. */\n' +
  'window.RTG_ROSTERS = ' + JSON.stringify({
    updated: new Date().toISOString().slice(0, 10),
    count: players.length,
    divisions,
    players,
  }) + ';\n';
writeFileSync('arcade/rosters.js', out);
console.log('wrote arcade/rosters.js:', players.length, 'players,', Object.keys(divisions).length, 'divisions');
