/* RunTheDrive playbook — 6 schemes x 12 plays, every stat measured from real
   football play-by-play + charting. Generated by runthedrive_playbook_builder.py;
   do not hand-edit. Browser attaches window.RTD_PLAYBOOK; Node exports it. */
(function (root, data) {
  if (typeof module === "object" && module.exports) module.exports = data;
  else root.RTD_PLAYBOOK = data;
}(typeof self !== "undefined" ? self : this,
{
  "meta": {
    "source": "nflverse pbp 2016-2025 + FTN charting 2022-2025",
    "differentiation": "per-play signatures: run gap x location, pass air-band x field location",
    "note": "every play carries its own measured numbers; no two share a row unless they share a signature"
  },
  "schemes": {
    "AIR_RAID": {
      "name": "Air Raid",
      "tagline": "Spread them out, throw it now, never huddle.",
      "box_draw": 5.8,
      "shotgun": 92,
      "backs": 1,
      "nohuddle": 45,
      "strength": "Light boxes and tempo. Quick game hums.",
      "weakness": "No under-center play action, so deep shots run a high disaster rate.",
      "plays": [
        {
          "name": "Four Verts",
          "archetype": "DEEP",
          "signature": "20+|left",
          "formation": "Shotgun",
          "tags": [
            "no_huddle"
          ],
          "success_pct": 37.1,
          "explosive_pct": 32.4,
          "disaster_pct": 25.9,
          "avg_yards": 10.67,
          "epa": 0.37,
          "turnover_pct": 4.76,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "Y-Cross",
          "archetype": "INTERMEDIATE",
          "signature": "15-19|middle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 57.1,
          "explosive_pct": 50.9,
          "disaster_pct": 20.2,
          "avg_yards": 12.14,
          "epa": 0.409,
          "turnover_pct": 5.95,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Mesh",
          "archetype": "QUICK",
          "signature": "0-4|middle",
          "formation": "Shotgun",
          "tags": [
            "motion"
          ],
          "success_pct": 49.4,
          "explosive_pct": 19.1,
          "disaster_pct": 12.7,
          "avg_yards": 5.86,
          "epa": 0.02,
          "turnover_pct": 1.4,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 62.0,
            "3-6": 53.2,
            "7-9": 43.1,
            "10+": 44.3
          }
        },
        {
          "name": "Shallow Cross",
          "archetype": "QUICK",
          "signature": "0-4|left",
          "formation": "Shotgun",
          "tags": [
            "motion"
          ],
          "success_pct": 46.9,
          "explosive_pct": 18.2,
          "disaster_pct": 12.7,
          "avg_yards": 5.23,
          "epa": 0.02,
          "turnover_pct": 1.14,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 62.0,
            "3-6": 53.2,
            "7-9": 43.1,
            "10+": 44.3
          }
        },
        {
          "name": "Stick",
          "archetype": "QUICK",
          "signature": "5-9|right",
          "formation": "Shotgun",
          "tags": [
            "no_huddle"
          ],
          "success_pct": 59.9,
          "explosive_pct": 22.7,
          "disaster_pct": 12.5,
          "avg_yards": 5.98,
          "epa": 0.249,
          "turnover_pct": 1.49,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Bubble Screen",
          "archetype": "SCREEN",
          "signature": "behind|left",
          "formation": "Shotgun",
          "tags": [
            "motion"
          ],
          "success_pct": 37.5,
          "explosive_pct": 12.1,
          "disaster_pct": 16.0,
          "avg_yards": 4.56,
          "epa": -0.206,
          "turnover_pct": 0.6,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 51.6,
            "3-6": 42.3,
            "7-9": 35.2,
            "10+": 35.2
          }
        },
        {
          "name": "Sail",
          "archetype": "INTERMEDIATE",
          "signature": "10-14|right",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 49.0,
          "explosive_pct": 34.2,
          "disaster_pct": 18.2,
          "avg_yards": 7.22,
          "epa": 0.338,
          "turnover_pct": 2.94,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Six (Post-Wheel)",
          "archetype": "DEEP",
          "signature": "20+|right",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 34.1,
          "explosive_pct": 32.9,
          "disaster_pct": 25.9,
          "avg_yards": 10.95,
          "epa": 0.329,
          "turnover_pct": 4.99,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "Quick Slant",
          "archetype": "QUICK",
          "signature": "5-9|middle",
          "formation": "Shotgun",
          "tags": [
            "no_huddle"
          ],
          "success_pct": 65.5,
          "explosive_pct": 29.6,
          "disaster_pct": 12.5,
          "avg_yards": 7.43,
          "epa": 0.249,
          "turnover_pct": 2.13,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Tunnel Screen",
          "archetype": "SCREEN",
          "signature": "behind|right",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 33.4,
          "explosive_pct": 10.9,
          "disaster_pct": 16.0,
          "avg_yards": 4.2,
          "epa": -0.226,
          "turnover_pct": 0.6,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 51.6,
            "3-6": 42.3,
            "7-9": 35.2,
            "10+": 35.2
          }
        },
        {
          "name": "QB Draw",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Shotgun",
          "tags": [
            "no_huddle"
          ],
          "success_pct": 48.1,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.67,
          "epa": 0.087,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        },
        {
          "name": "Inside Zone Read",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Shotgun",
          "tags": [
            "rpo"
          ],
          "success_pct": 40.3,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.12,
          "epa": 0.003,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        }
      ]
    },
    "WEST_COAST": {
      "name": "West Coast",
      "tagline": "Timing, rhythm, take what they give you.",
      "box_draw": 6.2,
      "shotgun": 50,
      "backs": 1,
      "nohuddle": 10,
      "strength": "Highest floor in the game. Fewest disasters.",
      "weakness": "Low explosive rate. Slow to come from behind.",
      "plays": [
        {
          "name": "Slant-Flat",
          "archetype": "QUICK",
          "signature": "5-9|left",
          "formation": "Shotgun",
          "tags": [
            "motion"
          ],
          "success_pct": 60.7,
          "explosive_pct": 25.4,
          "disaster_pct": 12.5,
          "avg_yards": 6.36,
          "epa": 0.228,
          "turnover_pct": 1.68,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Drive",
          "archetype": "QUICK",
          "signature": "5-9|middle",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 64.8,
          "explosive_pct": 29.6,
          "disaster_pct": 10.5,
          "avg_yards": 7.43,
          "epa": 0.278,
          "turnover_pct": 2.13,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Texas (RB Angle)",
          "archetype": "QUICK",
          "signature": "0-4|middle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 47.7,
          "explosive_pct": 19.1,
          "disaster_pct": 12.7,
          "avg_yards": 5.86,
          "epa": 0.0,
          "turnover_pct": 1.4,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 62.0,
            "3-6": 53.2,
            "7-9": 43.1,
            "10+": 44.3
          }
        },
        {
          "name": "Curl-Flat",
          "archetype": "INTERMEDIATE",
          "signature": "10-14|right",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 50.0,
          "explosive_pct": 34.2,
          "disaster_pct": 16.2,
          "avg_yards": 7.22,
          "epa": 0.388,
          "turnover_pct": 2.94,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Dagger",
          "archetype": "INTERMEDIATE",
          "signature": "15-19|left",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 47.4,
          "explosive_pct": 42.1,
          "disaster_pct": 20.2,
          "avg_yards": 9.79,
          "epa": 0.409,
          "turnover_pct": 4.04,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Halfback Screen",
          "archetype": "SCREEN",
          "signature": "behind|right",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 33.4,
          "explosive_pct": 10.9,
          "disaster_pct": 16.0,
          "avg_yards": 4.2,
          "epa": -0.226,
          "turnover_pct": 0.6,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 51.6,
            "3-6": 42.3,
            "7-9": 35.2,
            "10+": 35.2
          }
        },
        {
          "name": "Waggle",
          "archetype": "PLAY_ACTION",
          "signature": "10-14|left",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 60.3,
          "explosive_pct": 34.0,
          "disaster_pct": 4.3,
          "avg_yards": 9.15,
          "epa": 0.423,
          "turnover_pct": 1.67,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Naked Boot",
          "archetype": "PLAY_ACTION",
          "signature": "5-9|right",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 58.9,
          "explosive_pct": 20.2,
          "disaster_pct": 4.9,
          "avg_yards": 6.35,
          "epa": 0.217,
          "turnover_pct": 1.96,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Power O",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 39.6,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.12,
          "epa": -0.057,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        },
        {
          "name": "Inside Zone",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 41.3,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.67,
          "epa": 0.017,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        },
        {
          "name": "Toss Crack",
          "archetype": "RUN",
          "signature": "end",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 45.1,
          "explosive_pct": 13.4,
          "disaster_pct": 10.0,
          "avg_yards": 5.03,
          "epa": 0.02,
          "turnover_pct": 0.42,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 64.3,
            "3-6": 51.1,
            "7-9": 42.9,
            "10+": 41.0
          }
        },
        {
          "name": "Sneak",
          "archetype": "QB_SNEAK",
          "signature": "SNEAK",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 74.0,
          "explosive_pct": 20.0,
          "disaster_pct": 13.0,
          "avg_yards": 1.7,
          "epa": 0.3,
          "turnover_pct": 0.6,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 78.0,
            "3-6": 45.0,
            "7-9": 20.0,
            "10+": 15.0
          }
        }
      ]
    },
    "SMASH_MOUTH": {
      "name": "Smash Mouth",
      "tagline": "Two backs, downhill, dare them to stop it.",
      "box_draw": 6.9,
      "shotgun": 18,
      "backs": 2,
      "nohuddle": 5,
      "strength": "Owns short yardage. Heavy-personnel play action is elite.",
      "weakness": "Draws 7+ boxes. Slow, burns clock.",
      "plays": [
        {
          "name": "Power",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 39.6,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.12,
          "epa": -0.057,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        },
        {
          "name": "Counter Trey",
          "archetype": "RUN",
          "signature": "tackle",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 38.1,
          "explosive_pct": 8.7,
          "disaster_pct": 6.4,
          "avg_yards": 4.44,
          "epa": -0.061,
          "turnover_pct": 0.45,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 57.8,
            "3-6": 46.4,
            "7-9": 35.8,
            "10+": 33.2
          }
        },
        {
          "name": "Iso",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 39.6,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.12,
          "epa": -0.057,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        },
        {
          "name": "Duo",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 39.6,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.12,
          "epa": -0.057,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        },
        {
          "name": "Lead Draw",
          "archetype": "RUN",
          "signature": "tackle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 39.8,
          "explosive_pct": 8.7,
          "disaster_pct": 6.4,
          "avg_yards": 4.99,
          "epa": 0.013,
          "turnover_pct": 0.45,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 57.8,
            "3-6": 46.4,
            "7-9": 35.8,
            "10+": 33.2
          }
        },
        {
          "name": "QB Sneak",
          "archetype": "QB_SNEAK",
          "signature": "SNEAK",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 74.0,
          "explosive_pct": 20.0,
          "disaster_pct": 13.0,
          "avg_yards": 1.7,
          "epa": 0.3,
          "turnover_pct": 0.6,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 78.0,
            "3-6": 45.0,
            "7-9": 20.0,
            "10+": 15.0
          }
        },
        {
          "name": "Wham",
          "archetype": "RUN",
          "signature": "tackle",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 38.1,
          "explosive_pct": 8.7,
          "disaster_pct": 6.4,
          "avg_yards": 4.44,
          "epa": -0.061,
          "turnover_pct": 0.45,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 57.8,
            "3-6": 46.4,
            "7-9": 35.8,
            "10+": 33.2
          }
        },
        {
          "name": "Play Pass Post",
          "archetype": "PLAY_ACTION",
          "signature": "15-19|middle",
          "formation": "Under Center",
          "tags": [
            "heavy_pa"
          ],
          "success_pct": 72.2,
          "explosive_pct": 65.1,
          "disaster_pct": 5.4,
          "avg_yards": 15.23,
          "epa": 0.627,
          "turnover_pct": 4.77,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Boot Flood",
          "archetype": "PLAY_ACTION",
          "signature": "5-9|right",
          "formation": "Under Center",
          "tags": [
            "heavy_pa",
            "motion"
          ],
          "success_pct": 61.2,
          "explosive_pct": 20.2,
          "disaster_pct": 4.9,
          "avg_yards": 6.35,
          "epa": 0.254,
          "turnover_pct": 1.96,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Y-Leak",
          "archetype": "PLAY_ACTION",
          "signature": "10-14|left",
          "formation": "Under Center",
          "tags": [
            "heavy_pa"
          ],
          "success_pct": 59.2,
          "explosive_pct": 34.0,
          "disaster_pct": 4.3,
          "avg_yards": 9.15,
          "epa": 0.42,
          "turnover_pct": 1.67,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Hitch",
          "archetype": "QUICK",
          "signature": "5-9|right",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 57.5,
          "explosive_pct": 22.7,
          "disaster_pct": 10.5,
          "avg_yards": 5.98,
          "epa": 0.258,
          "turnover_pct": 1.49,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Max Protect Shot",
          "archetype": "DEEP",
          "signature": "20+|left",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 40.1,
          "explosive_pct": 41.0,
          "disaster_pct": 8.8,
          "avg_yards": 10.67,
          "epa": 0.562,
          "turnover_pct": 4.76,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        }
      ]
    },
    "WIDE_ZONE": {
      "name": "Wide Zone",
      "tagline": "Stretch them sideline to sideline, then hit the boot.",
      "box_draw": 6.5,
      "shotgun": 30,
      "backs": 1,
      "nohuddle": 12,
      "strength": "Best access to the under-center deep shot.",
      "weakness": "Needs the run to sell it. Predictable if you abandon it.",
      "plays": [
        {
          "name": "Outside Zone",
          "archetype": "RUN",
          "signature": "end",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 45.1,
          "explosive_pct": 13.4,
          "disaster_pct": 10.0,
          "avg_yards": 5.03,
          "epa": 0.02,
          "turnover_pct": 0.42,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 64.3,
            "3-6": 51.1,
            "7-9": 42.9,
            "10+": 41.0
          }
        },
        {
          "name": "Wide Zone Split",
          "archetype": "RUN",
          "signature": "end",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 45.1,
          "explosive_pct": 13.4,
          "disaster_pct": 10.0,
          "avg_yards": 5.03,
          "epa": 0.02,
          "turnover_pct": 0.42,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 64.3,
            "3-6": 51.1,
            "7-9": 42.9,
            "10+": 41.0
          }
        },
        {
          "name": "Zone Cutback",
          "archetype": "RUN",
          "signature": "tackle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 39.8,
          "explosive_pct": 8.7,
          "disaster_pct": 6.4,
          "avg_yards": 4.99,
          "epa": 0.013,
          "turnover_pct": 0.45,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 57.8,
            "3-6": 46.4,
            "7-9": 35.8,
            "10+": 33.2
          }
        },
        {
          "name": "Jet Sweep",
          "archetype": "RUN",
          "signature": "end",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 45.1,
          "explosive_pct": 13.4,
          "disaster_pct": 10.0,
          "avg_yards": 5.03,
          "epa": 0.02,
          "turnover_pct": 0.42,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 64.3,
            "3-6": 51.1,
            "7-9": 42.9,
            "10+": 41.0
          }
        },
        {
          "name": "Boot Over",
          "archetype": "PLAY_ACTION",
          "signature": "10-14|middle",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 70.0,
          "explosive_pct": 44.2,
          "disaster_pct": 4.3,
          "avg_yards": 11.51,
          "epa": 0.423,
          "turnover_pct": 3.04,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Naked Flood",
          "archetype": "PLAY_ACTION",
          "signature": "5-9|right",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 58.9,
          "explosive_pct": 20.2,
          "disaster_pct": 4.9,
          "avg_yards": 6.35,
          "epa": 0.217,
          "turnover_pct": 1.96,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Yankee",
          "archetype": "DEEP",
          "signature": "20+|middle",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 44.9,
          "explosive_pct": 45.1,
          "disaster_pct": 8.8,
          "avg_yards": 13.37,
          "epa": 0.562,
          "turnover_pct": 10.05,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "Deep Over",
          "archetype": "INTERMEDIATE",
          "signature": "15-19|middle",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 65.2,
          "explosive_pct": 59.5,
          "disaster_pct": 3.1,
          "avg_yards": 12.14,
          "epa": 0.662,
          "turnover_pct": 5.95,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Slide Screen",
          "archetype": "SCREEN",
          "signature": "behind|left",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 36.8,
          "explosive_pct": 12.1,
          "disaster_pct": 14.0,
          "avg_yards": 4.56,
          "epa": -0.176,
          "turnover_pct": 0.6,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 51.6,
            "3-6": 42.3,
            "7-9": 35.2,
            "10+": 35.2
          }
        },
        {
          "name": "Drift",
          "archetype": "QUICK",
          "signature": "5-9|left",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 61.7,
          "explosive_pct": 25.4,
          "disaster_pct": 10.5,
          "avg_yards": 6.36,
          "epa": 0.278,
          "turnover_pct": 1.68,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Flat-Corner",
          "archetype": "INTERMEDIATE",
          "signature": "10-14|right",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 49.0,
          "explosive_pct": 34.2,
          "disaster_pct": 18.2,
          "avg_yards": 7.22,
          "epa": 0.338,
          "turnover_pct": 2.94,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Sneak",
          "archetype": "QB_SNEAK",
          "signature": "SNEAK",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 74.0,
          "explosive_pct": 20.0,
          "disaster_pct": 13.0,
          "avg_yards": 1.7,
          "epa": 0.3,
          "turnover_pct": 0.6,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 78.0,
            "3-6": 45.0,
            "7-9": 20.0,
            "10+": 15.0
          }
        }
      ]
    },
    "VERTICAL": {
      "name": "Vertical",
      "tagline": "Take shots. Live with the swings.",
      "box_draw": 6.0,
      "shotgun": 78,
      "backs": 1,
      "nohuddle": 15,
      "strength": "Highest explosive rate. One call ends the drive.",
      "weakness": "Highest disaster and interception rate. Brutal on 3rd and long.",
      "plays": [
        {
          "name": "Go Ball",
          "archetype": "DEEP",
          "signature": "20+|left",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 33.7,
          "explosive_pct": 32.4,
          "disaster_pct": 25.9,
          "avg_yards": 10.67,
          "epa": 0.329,
          "turnover_pct": 4.76,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "Double Post",
          "archetype": "DEEP",
          "signature": "20+|middle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 38.5,
          "explosive_pct": 36.5,
          "disaster_pct": 25.9,
          "avg_yards": 13.37,
          "epa": 0.329,
          "turnover_pct": 10.05,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "Switch Verts",
          "archetype": "DEEP",
          "signature": "20+|right",
          "formation": "Shotgun",
          "tags": [
            "motion"
          ],
          "success_pct": 35.8,
          "explosive_pct": 32.9,
          "disaster_pct": 25.9,
          "avg_yards": 10.95,
          "epa": 0.349,
          "turnover_pct": 4.99,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "Deep Cross",
          "archetype": "INTERMEDIATE",
          "signature": "15-19|middle",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 63.5,
          "explosive_pct": 59.5,
          "disaster_pct": 3.1,
          "avg_yards": 12.14,
          "epa": 0.642,
          "turnover_pct": 5.95,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Dig",
          "archetype": "INTERMEDIATE",
          "signature": "15-19|left",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 47.4,
          "explosive_pct": 42.1,
          "disaster_pct": 20.2,
          "avg_yards": 9.79,
          "epa": 0.409,
          "turnover_pct": 4.04,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Deep Comeback",
          "archetype": "INTERMEDIATE",
          "signature": "15-19|right",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 45.3,
          "explosive_pct": 40.1,
          "disaster_pct": 20.2,
          "avg_yards": 9.38,
          "epa": 0.409,
          "turnover_pct": 4.05,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Post-Dig",
          "archetype": "INTERMEDIATE",
          "signature": "10-14|middle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 61.5,
          "explosive_pct": 46.5,
          "disaster_pct": 18.2,
          "avg_yards": 10.05,
          "epa": 0.338,
          "turnover_pct": 4.11,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "PA Deep Shot",
          "archetype": "PLAY_ACTION",
          "signature": "20+|left",
          "formation": "Under Center",
          "tags": [],
          "success_pct": 42.6,
          "explosive_pct": 43.3,
          "disaster_pct": 7.4,
          "avg_yards": 14.12,
          "epa": 0.598,
          "turnover_pct": 4.03,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "PA Seam",
          "archetype": "PLAY_ACTION",
          "signature": "15-19|middle",
          "formation": "Under Center",
          "tags": [
            "motion"
          ],
          "success_pct": 73.3,
          "explosive_pct": 65.1,
          "disaster_pct": 5.4,
          "avg_yards": 15.23,
          "epa": 0.63,
          "turnover_pct": 4.77,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 54.3,
            "3-6": 50.3,
            "7-9": 50.3,
            "10+": 54.0
          }
        },
        {
          "name": "Back Shoulder",
          "archetype": "INTERMEDIATE",
          "signature": "10-14|right",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 49.0,
          "explosive_pct": 34.2,
          "disaster_pct": 18.2,
          "avg_yards": 7.22,
          "epa": 0.338,
          "turnover_pct": 2.94,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Hitch-Seam",
          "archetype": "QUICK",
          "signature": "5-9|middle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 62.1,
          "explosive_pct": 29.6,
          "disaster_pct": 12.5,
          "avg_yards": 7.43,
          "epa": 0.208,
          "turnover_pct": 2.13,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Draw",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 41.3,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.67,
          "epa": 0.017,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        }
      ]
    },
    "SPREAD_OPTION": {
      "name": "Spread Option",
      "tagline": "Make the quarterback a runner and play fast.",
      "box_draw": 5.9,
      "shotgun": 95,
      "backs": 1,
      "nohuddle": 40,
      "strength": "Shotgun run bonus plus tempo.",
      "weakness": "RPOs measure slightly negative. No under-center play action.",
      "plays": [
        {
          "name": "Zone Read",
          "archetype": "RUN",
          "signature": "end",
          "formation": "Shotgun",
          "tags": [
            "no_huddle"
          ],
          "success_pct": 53.6,
          "explosive_pct": 13.4,
          "disaster_pct": 10.0,
          "avg_yards": 5.58,
          "epa": 0.164,
          "turnover_pct": 0.42,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 64.3,
            "3-6": 51.1,
            "7-9": 42.9,
            "10+": 41.0
          }
        },
        {
          "name": "QB Power",
          "archetype": "RUN",
          "signature": "guard",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 41.3,
          "explosive_pct": 7.8,
          "disaster_pct": 5.9,
          "avg_yards": 4.67,
          "epa": 0.017,
          "turnover_pct": 0.41,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 61.8,
            "3-6": 47.3,
            "7-9": 35.3,
            "10+": 32.1
          }
        },
        {
          "name": "Inverted Veer",
          "archetype": "RUN",
          "signature": "end",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 46.8,
          "explosive_pct": 13.4,
          "disaster_pct": 10.0,
          "avg_yards": 5.58,
          "epa": 0.094,
          "turnover_pct": 0.42,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 64.3,
            "3-6": 51.1,
            "7-9": 42.9,
            "10+": 41.0
          }
        },
        {
          "name": "Speed Option",
          "archetype": "RUN",
          "signature": "end",
          "formation": "Shotgun",
          "tags": [
            "no_huddle"
          ],
          "success_pct": 53.6,
          "explosive_pct": 13.4,
          "disaster_pct": 10.0,
          "avg_yards": 5.58,
          "epa": 0.164,
          "turnover_pct": 0.42,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 64.3,
            "3-6": 51.1,
            "7-9": 42.9,
            "10+": 41.0
          }
        },
        {
          "name": "Glance RPO",
          "archetype": "QUICK",
          "signature": "5-9|middle",
          "formation": "Shotgun",
          "tags": [
            "rpo"
          ],
          "success_pct": 61.1,
          "explosive_pct": 29.6,
          "disaster_pct": 12.5,
          "avg_yards": 6.88,
          "epa": 0.194,
          "turnover_pct": 2.13,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Bubble RPO",
          "archetype": "SCREEN",
          "signature": "behind|left",
          "formation": "Shotgun",
          "tags": [
            "rpo",
            "motion"
          ],
          "success_pct": 36.5,
          "explosive_pct": 12.1,
          "disaster_pct": 16.0,
          "avg_yards": 4.01,
          "epa": -0.22,
          "turnover_pct": 0.6,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 51.6,
            "3-6": 42.3,
            "7-9": 35.2,
            "10+": 35.2
          }
        },
        {
          "name": "Pop Pass",
          "archetype": "QUICK",
          "signature": "0-4|middle",
          "formation": "Shotgun",
          "tags": [
            "rpo"
          ],
          "success_pct": 46.7,
          "explosive_pct": 19.1,
          "disaster_pct": 12.7,
          "avg_yards": 5.31,
          "epa": -0.014,
          "turnover_pct": 1.4,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 62.0,
            "3-6": 53.2,
            "7-9": 43.1,
            "10+": 44.3
          }
        },
        {
          "name": "Snag",
          "archetype": "QUICK",
          "signature": "5-9|right",
          "formation": "Shotgun",
          "tags": [
            "no_huddle"
          ],
          "success_pct": 59.9,
          "explosive_pct": 22.7,
          "disaster_pct": 12.5,
          "avg_yards": 5.98,
          "epa": 0.249,
          "turnover_pct": 1.49,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 65.9,
            "3-6": 61.3,
            "7-9": 54.8,
            "10+": 59.7
          }
        },
        {
          "name": "Jet Screen",
          "archetype": "SCREEN",
          "signature": "behind|right",
          "formation": "Shotgun",
          "tags": [
            "motion"
          ],
          "success_pct": 35.1,
          "explosive_pct": 10.9,
          "disaster_pct": 16.0,
          "avg_yards": 4.2,
          "epa": -0.206,
          "turnover_pct": 0.6,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 51.6,
            "3-6": 42.3,
            "7-9": 35.2,
            "10+": 35.2
          }
        },
        {
          "name": "PA Glance",
          "archetype": "PLAY_ACTION",
          "signature": "10-14|left",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 57.3,
          "explosive_pct": 31.9,
          "disaster_pct": 4.3,
          "avg_yards": 9.15,
          "epa": 0.373,
          "turnover_pct": 1.67,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 57.1,
            "3-6": 55.8,
            "7-9": 55.1,
            "10+": 55.5
          }
        },
        {
          "name": "Shot Post",
          "archetype": "DEEP",
          "signature": "20+|middle",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 38.5,
          "explosive_pct": 36.5,
          "disaster_pct": 25.9,
          "avg_yards": 13.37,
          "epa": 0.329,
          "turnover_pct": 10.05,
          "turnover_type": "int",
          "success_by_distance": {
            "1-2": 41.2,
            "3-6": 35.5,
            "7-9": 36.5,
            "10+": 37.1
          }
        },
        {
          "name": "QB Sneak",
          "archetype": "QB_SNEAK",
          "signature": "SNEAK",
          "formation": "Shotgun",
          "tags": [],
          "success_pct": 75.7,
          "explosive_pct": 20.0,
          "disaster_pct": 13.0,
          "avg_yards": 2.25,
          "epa": 0.374,
          "turnover_pct": 0.6,
          "turnover_type": "fumble",
          "success_by_distance": {
            "1-2": 78.0,
            "3-6": 45.0,
            "7-9": 20.0,
            "10+": 15.0
          }
        }
      ]
    }
  }
}));
