/* The sample sheet's cast. Every name here is invented for this game, and none
   of these looks copies a real performer's gear, paint or mask design. They are
   here to be judged before the full sprite system is built (PLAN.md). */
window.RTR_SAMPLES = [
  { name: 'Cometa Azul', tag: 'Cruiserweight · Face · Luchador', pose: 'flex',
    look: { build: 'cruiser', skin: 4, hair: 'short', mask: 'lucha', bottom: 'tights', boots: 'tall', wrists: 'tape', gear: '#1f8fb8', trim: '#f2d27a', mood: 'grin' } },
  { name: 'Big Hoss Mercer', tag: 'Super Heavyweight · Heel · Brawler', pose: 'stance',
    look: { build: 'super', skin: 1, hair: 'bald', facial: 'longbeard', hc: 3, bottom: 'singlet', boots: 'low', wrists: 'bands', gear: '#23252d', trim: '#c6392c', mood: 'scowl', tattoo: 'sleeve' } },
  { name: 'Kenji Arata', tag: 'Athletic · Tweener · Strong style', pose: 'stance',
    look: { build: 'athletic', skin: 2, hair: 'short', hc: 0, bottom: 'trunks', boots: 'low', knees: 'pads', wrists: 'tape', gear: '#16181e', trim: '#d9d9d6', bootc: '#16181e', mood: 'scowl' } },
  { name: 'Osric Vane', tag: 'Giant · Heel · Monster', pose: 'idle',
    look: { build: 'giant', skin: 0, hair: 'long', hc: 0, facial: 'beard', bottom: 'pants', boots: 'tall', entrance: 'robe', gear: '#3a2350', trim: '#9b7bd0', mood: 'scowl', paint: 'bars' } },
  { name: 'Ricky Shine', tag: 'Athletic · Face · Showman', pose: 'point',
    look: { build: 'athletic', skin: 2, hair: 'long', hc: 4, bottom: 'trunks', boots: 'tall', knees: 'pads', wrists: 'tape', gear: '#d4a321', trim: '#c6392c', mood: 'grin', entrance: 'jacket' } },
  { name: 'Dutch Kowalczyk', tag: 'Heavyweight · Tweener · Brawler', pose: 'idle',
    look: { build: 'heavy', skin: 1, hair: 'buzz', hc: 2, facial: 'stubble', bottom: 'pants', top: 'tee', boots: 'sneaks', wrists: 'bands', gear: '#2b4a7a', trim: '#e8e2cf', bootc: '#2a2c33', mood: 'neutral' } },
  { name: 'Maya Storm', tag: 'Athletic · Face · High flyer', pose: 'flex',
    look: { figure: 'f', build: 'athletic', skin: 5, hair: 'pony', hc: 1, bottom: 'tights', boots: 'tall', knees: 'pads', wrists: 'tape', gear: '#2fa8a0', trim: '#f4e8db', mood: 'grin' } },
  { name: 'Vera Knox', tag: 'Cruiserweight · Heel · Technician', pose: 'stance',
    look: { figure: 'f', build: 'cruiser', skin: 0, hair: 'slick', hc: 0, bottom: 'shorts', boots: 'low', knees: 'one', wrists: 'tape', gear: '#7a1c24', trim: '#16181e', mood: 'scowl', paint: 'bars' } },
  { name: 'Hana Kurosaki', tag: 'Cruiserweight · Face · Joshi ace', pose: 'point',
    look: { figure: 'f', build: 'cruiser', skin: 1, hair: 'topknot', hc: 0, bottom: 'singlet', boots: 'tall', knees: 'pads', gear: '#e05a8a', trim: '#f4e8db', mood: 'grin' } },
  { name: 'Marcus Reign', tag: 'Athletic · Face · World champion', pose: 'raise',
    look: { build: 'athletic', skin: 7, hair: 'short', hc: 0, facial: 'goatee', bottom: 'trunks', boots: 'tall', knees: 'pads', wrists: 'tape', gear: '#c6392c', trim: '#f4e8db', belt: 'waist', mood: 'grin' } },
  { name: 'Reza Haddad', tag: 'Athletic · Tweener · MMA crossover', pose: 'stance',
    look: { build: 'athletic', skin: 4, hair: 'buzz', hc: 0, facial: 'beard', bottom: 'shorts', boots: 'wraps', wrists: 'gloves', gear: '#23252d', trim: '#e0b341', mood: 'scowl', tattoo: 'chest' } },
  { name: 'Cal "Pops" Whitmore', tag: 'Heavyweight · Face · Veteran', pose: 'idle', age: 47,
    look: { build: 'heavy', skin: 2, hair: 'long', hc: 2, facial: 'beard', bottom: 'trunks', boots: 'tall', entrance: 'vest', wrists: 'tape', belt: 'shoulder', gear: '#8a5a2b', trim: '#e0b341', mood: 'neutral' } },
  { name: 'Jinx Malloy', tag: 'Athletic · Heel · Hardcore', pose: 'idle',
    look: { build: 'athletic', skin: 0, hair: 'mohawk', hc: 9, bottom: 'pants', boots: 'low', wrists: 'tape', tattoo: 'both', gear: '#2a2c33', trim: '#2fa86a', bootc: '#16181e', mood: 'grin' } },
  { name: 'The Revenant', tag: 'Heavyweight · Heel · Mystic', pose: 'idle',
    look: { build: 'heavy', skin: 1, hair: 'long', hc: 0, paint: 'skull', bottom: 'tights', boots: 'tall', entrance: 'cape', gear: '#1c1d24', trim: '#8f1c24', mood: 'neutral' } },
  { name: 'Lil Bopper', tag: 'Cruiserweight · Face · Comedy act', pose: 'point',
    look: { build: 'cruiser', skin: 6, hair: 'afro', hc: 0, bottom: 'shorts', top: 'tank', boots: 'sneaks', wrists: 'bands', gear: '#e05aa8', trim: '#f2d27a', mood: 'grin', shades: true } },
  { name: 'Tomas "Dread" Okoye', tag: 'Heavyweight · Face · Tag specialist', pose: 'flex',
    look: { build: 'heavy', skin: 8, hair: 'dreads', hc: 0, mask: 'half', bottom: 'tights', boots: 'kick', wrists: 'tape', gear: '#e0b341', trim: '#16181e', mood: 'neutral' } },
];
