/* ============================================================
   RunTheRopes: Build-A-Wrestler Mentors (v1)
   ------------------------------------------------------------
   Legends of each era are MENTORS, not a draft pool. As your
   career progresses you unlock the right to train under them
   (gated by reputation + the era you came up in). Completing a
   mentorship is a multi-week career investment that pays out:
     • attr: a permanent boost to their signature strengths
     • move: you are TAUGHT their signature move

   Nothing here is purchasable. Mentorships are earned by
   climbing the card, exactly like attributes and moves.

   Attributes (0-100): power(po), technique(te), aerial(ae),
   charisma(ch), psychology(ps), toughness(to), stamina(st).
   rarity drives the reputation required to get in the door.
   ============================================================ */
window.RTR_ERAS = [
  { id:'golden',   name:'Golden Age',        years:'1984-1992', blurb:'Cartoon larger-than-life spectacle. Big men, bigger crowds.', accent:'#e0b341' },
  { id:'hardcore', name:'Hardcore Era',      years:'1993-1999', blurb:'Blood, tables and attitude. Anything goes.',                accent:'#C6392C' },
  { id:'ruthless', name:'Ruthless Aggression',years:'2000-2008',blurb:'Athletic, intense, main-event workhorses.',                 accent:'#7f9cc0' },
  { id:'modern',   name:'Modern Era',        years:'2009-now',  blurb:'Workrate, indie crossovers and global stars.',              accent:'#5bb083' },
  { id:'puro',     name:'Puroresu',          years:'Japan',     blurb:'Strong style. Stiff strikes, epic long-form matches.',      accent:'#d2687a' },
  { id:'lucha',    name:'Lucha Libre',       years:'Mexico',    blurb:'Masks, flight and family legacy.',                          accent:'#c79320' },
];

// helper shorthand for bonus objects: {po,te,ae,ch,ps,to,st}
window.RTR_LEGENDS = [
  // ================= GOLDEN AGE =================
  { id:'l_hogan', name:'Hulk Hogan', era:'golden', rarity:'legendary',
    attr:{label:'Hulkamania', b:{ch:14,po:10,to:6}}, move:{name:'Leg Drop', kind:'finisher', dmg:82, pop:95, style:'power'} },
  { id:'l_savage', name:'Randy Savage', era:'golden', rarity:'legendary',
    attr:{label:'Macho Madness', b:{ch:12,ps:10,ae:8}}, move:{name:'Flying Elbow Drop', kind:'finisher', dmg:80, pop:92, style:'aerial'} },
  { id:'l_andre', name:'André the Giant', era:'golden', rarity:'legendary',
    attr:{label:'The Eighth Wonder', b:{po:18,to:12}}, move:{name:'Giant Splash', kind:'finisher', dmg:88, pop:84, style:'power'} },
  { id:'l_warrior', name:'Ultimate Warrior', era:'golden', rarity:'epic',
    attr:{label:'Warrior Intensity', b:{po:12,ch:10,st:6}}, move:{name:'Gorilla Press Slam', kind:'signature', dmg:70, pop:78, style:'power'} },
  { id:'l_piper', name:'Roddy Piper', era:'golden', rarity:'epic',
    attr:{label:'Hot Rod Mic Work', b:{ch:16,ps:8}}, move:{name:'Sleeper Hold', kind:'finisher', dmg:68, pop:74, style:'technical'} },
  { id:'l_steamboat', name:'Ricky Steamboat', era:'golden', rarity:'epic',
    attr:{label:'The Dragon', b:{te:12,ps:12,ae:6}}, move:{name:'Flying Crossbody', kind:'signature', dmg:66, pop:76, style:'aerial'} },
  { id:'l_flair', name:'Ric Flair', era:'golden', rarity:'legendary',
    attr:{label:'Nature Boy Ring IQ', b:{ps:18,ch:12,te:6}}, move:{name:'Figure-Four Leglock', kind:'finisher', dmg:72, pop:88, style:'technical'} },
  { id:'l_dibiase', name:'Ted DiBiase', era:'golden', rarity:'rare',
    attr:{label:'Million Dollar Heel', b:{ch:10,ps:8,te:5}}, move:{name:'Million Dollar Dream', kind:'finisher', dmg:70, pop:70, style:'technical'} },
  { id:'l_perfect', name:'Mr. Perfect', era:'golden', rarity:'rare',
    attr:{label:'Perfect Execution', b:{te:12,ps:7,st:5}}, move:{name:'Perfect-Plex', kind:'finisher', dmg:74, pop:72, style:'technical'} },
  { id:'l_jake', name:'Jake Roberts', era:'golden', rarity:'rare',
    attr:{label:'Psychology Master', b:{ps:16,ch:6}}, move:{name:'DDT', kind:'finisher', dmg:72, pop:80, style:'technical'} },
  { id:'l_bulldog', name:'British Bulldog', era:'golden', rarity:'rare',
    attr:{label:'Powerhouse Athlete', b:{po:11,st:7,te:5}}, move:{name:'Running Powerslam', kind:'finisher', dmg:74, pop:70, style:'power'} },
  { id:'l_demolition', name:'Demolition', era:'golden', rarity:'common',
    attr:{label:'Tag Team Brawler', b:{po:8,to:8}}, move:{name:'Decapitation Elbow', kind:'signature', dmg:62, pop:58, style:'power'} },

  // ================= HARDCORE ERA =================
  { id:'l_austin', name:'Stone Cold Steve Austin', era:'hardcore', rarity:'legendary',
    attr:{label:'Austin 3:16', b:{ch:18,to:10,ps:8}}, move:{name:'Stone Cold Stunner', kind:'finisher', dmg:84, pop:99, style:'brawl'} },
  { id:'l_rock', name:'The Rock', era:'hardcore', rarity:'legendary',
    attr:{label:'The Great One', b:{ch:20,ps:8,po:6}}, move:{name:'Rock Bottom', kind:'finisher', dmg:80, pop:96, style:'power'} },
  { id:'l_taker', name:'The Undertaker', era:'hardcore', rarity:'legendary',
    attr:{label:'The Deadman', b:{ps:14,po:12,to:10}}, move:{name:'Tombstone Piledriver', kind:'finisher', dmg:88, pop:94, style:'power'} },
  { id:'l_hbk', name:'Shawn Michaels', era:'hardcore', rarity:'legendary',
    attr:{label:'Mr. WrestleMania', b:{ps:14,te:10,ae:10,ch:6}}, move:{name:'Sweet Chin Music', kind:'finisher', dmg:82, pop:93, style:'strike'} },
  { id:'l_bret', name:'Bret Hart', era:'hardcore', rarity:'legendary',
    attr:{label:'Excellence of Execution', b:{te:18,ps:12}}, move:{name:'Sharpshooter', kind:'finisher', dmg:76, pop:88, style:'technical'} },
  { id:'l_foley', name:'Mick Foley', era:'hardcore', rarity:'epic',
    attr:{label:'Hardcore Legend', b:{to:20,ps:10,ch:6}}, move:{name:'Mandible Claw', kind:'finisher', dmg:70, pop:82, style:'brawl'} },
  { id:'l_hhh', name:'Triple H', era:'hardcore', rarity:'epic',
    attr:{label:'The Game', b:{ps:14,po:10,ch:8}}, move:{name:'Pedigree', kind:'finisher', dmg:80, pop:86, style:'technical'} },
  { id:'l_kane', name:'Kane', era:'hardcore', rarity:'epic',
    attr:{label:'Big Red Monster', b:{po:14,to:12}}, move:{name:'Chokeslam', kind:'finisher', dmg:82, pop:80, style:'power'} },
  { id:'l_rvd', name:'Rob Van Dam', era:'hardcore', rarity:'epic',
    attr:{label:'Mr. Monday Night', b:{ae:16,st:8,to:6}}, move:{name:'Five-Star Frog Splash', kind:'finisher', dmg:80, pop:86, style:'aerial'} },
  { id:'l_sabu', name:'Sabu', era:'hardcore', rarity:'rare',
    attr:{label:'Homicidal Daredevil', b:{ae:12,to:14}}, move:{name:'Arabian Facebuster', kind:'signature', dmg:68, pop:72, style:'aerial'} },
  { id:'l_dudleys', name:'The Dudley Boyz', era:'hardcore', rarity:'rare',
    attr:{label:'Table Enthusiasts', b:{po:9,to:9}}, move:{name:'3D (Dudley Death Drop)', kind:'finisher', dmg:76, pop:78, style:'power'} },
  { id:'l_benoit', name:'Dean Malenko', era:'hardcore', rarity:'rare',
    attr:{label:'Man of 1,000 Holds', b:{te:16,ps:6}}, move:{name:'Texas Cloverleaf', kind:'finisher', dmg:70, pop:64, style:'technical'} },

  // ================= RUTHLESS AGGRESSION =================
  { id:'l_cena', name:'John Cena', era:'ruthless', rarity:'legendary',
    attr:{label:'Never Give Up', b:{ch:16,po:12,st:8}}, move:{name:'Attitude Adjustment', kind:'finisher', dmg:82, pop:92, style:'power'} },
  { id:'l_orton', name:'Randy Orton', era:'ruthless', rarity:'legendary',
    attr:{label:'Viper Instinct', b:{ps:16,te:8,ch:8}}, move:{name:'RKO', kind:'finisher', dmg:84, pop:94, style:'strike'} },
  { id:'l_eddie', name:'Eddie Guerrero', era:'ruthless', rarity:'legendary',
    attr:{label:'Lie, Cheat & Steal', b:{ch:14,te:12,ps:10}}, move:{name:'Frog Splash', kind:'finisher', dmg:80, pop:92, style:'aerial'} },
  { id:'l_angle', name:'Kurt Angle', era:'ruthless', rarity:'legendary',
    attr:{label:'Olympic Credentials', b:{te:20,st:8,to:6}}, move:{name:'Ankle Lock', kind:'finisher', dmg:78, pop:86, style:'technical'} },
  { id:'l_batista', name:'Batista', era:'ruthless', rarity:'epic',
    attr:{label:'The Animal', b:{po:18,ch:6}}, move:{name:'Batista Bomb', kind:'finisher', dmg:84, pop:82, style:'power'} },
  { id:'l_edge', name:'Edge', era:'ruthless', rarity:'epic',
    attr:{label:'Ultimate Opportunist', b:{ps:12,ch:10,te:8}}, move:{name:'Spear', kind:'finisher', dmg:80, pop:86, style:'strike'} },
  { id:'l_jeff', name:'Jeff Hardy', era:'ruthless', rarity:'epic',
    attr:{label:'Charismatic Enigma', b:{ae:16,ch:10,to:8}}, move:{name:'Swanton Bomb', kind:'finisher', dmg:80, pop:88, style:'aerial'} },
  { id:'l_rey', name:'Rey Mysterio', era:'ruthless', rarity:'legendary',
    attr:{label:'Master of the 619', b:{ae:20,te:8,ch:8}}, move:{name:'619', kind:'finisher', dmg:74, pop:92, style:'aerial'} },
  { id:'l_shelton', name:'Shelton Benjamin', era:'ruthless', rarity:'rare',
    attr:{label:'Freak Athlete', b:{ae:10,te:10,st:6}}, move:{name:'T-Bone Suplex', kind:'signature', dmg:70, pop:66, style:'technical'} },
  { id:'l_booker', name:'Booker T', era:'ruthless', rarity:'rare',
    attr:{label:'Five-Time Champion', b:{ch:10,te:8,st:6}}, move:{name:'Scissors Kick', kind:'signature', dmg:68, pop:72, style:'strike'} },
  { id:'l_jbl', name:'JBL', era:'ruthless', rarity:'rare',
    attr:{label:'Wrestling God', b:{po:10,ch:9,ps:6}}, move:{name:'Clothesline From Hell', kind:'finisher', dmg:76, pop:74, style:'strike'} },
  { id:'l_cm', name:'CM Punk', era:'ruthless', rarity:'epic',
    attr:{label:'Straight Edge Pipebomb', b:{ch:14,ps:10,te:8}}, move:{name:'GTS', kind:'finisher', dmg:78, pop:88, style:'strike'} },

  // ================= MODERN =================
  { id:'l_bryan', name:'Daniel Bryan', era:'modern', rarity:'legendary',
    attr:{label:'YES! Movement', b:{te:18,ps:12,st:8}}, move:{name:'Running Knee', kind:'finisher', dmg:80, pop:92, style:'strike'} },
  { id:'l_seth', name:'Seth Rollins', era:'modern', rarity:'legendary',
    attr:{label:'Architect', b:{te:12,ae:12,ch:10}}, move:{name:'Stomp', kind:'finisher', dmg:82, pop:88, style:'strike'} },
  { id:'l_roman', name:'Roman Reigns', era:'modern', rarity:'legendary',
    attr:{label:'Tribal Chief', b:{ch:16,po:12,ps:10}}, move:{name:'Spear', kind:'finisher', dmg:84, pop:92, style:'power'} },
  { id:'l_becky', name:'Becky Lynch', era:'modern', rarity:'legendary',
    attr:{label:'The Man', b:{ch:16,te:10,ps:8}}, move:{name:'Dis-arm-her', kind:'finisher', dmg:74, pop:88, style:'technical'} },
  { id:'l_charlotte', name:'Charlotte Flair', era:'modern', rarity:'epic',
    attr:{label:'Genetically Superior', b:{te:12,po:10,ch:8}}, move:{name:'Natural Selection', kind:'finisher', dmg:76, pop:80, style:'technical'} },
  { id:'l_aj', name:'AJ Styles', era:'modern', rarity:'legendary',
    attr:{label:'Phenomenal', b:{te:14,ae:14,ps:8}}, move:{name:'Styles Clash', kind:'finisher', dmg:80, pop:86, style:'technical'} },
  { id:'l_omega', name:'Kenny Omega', era:'modern', rarity:'legendary',
    attr:{label:'The Cleaner', b:{ps:14,te:12,ae:10,st:8}}, move:{name:'One Winged Angel', kind:'finisher', dmg:88, pop:90, style:'power'} },
  { id:'l_mox', name:'Jon Moxley', era:'modern', rarity:'epic',
    attr:{label:'Unscripted Violence', b:{to:16,ch:10,ps:6}}, move:{name:'Death Rider', kind:'finisher', dmg:80, pop:82, style:'brawl'} },
  { id:'l_ospreay', name:'Will Ospreay', era:'modern', rarity:'legendary',
    attr:{label:'Aerial Assassin', b:{ae:22,te:10,st:8}}, move:{name:'Hidden Blade', kind:'finisher', dmg:84, pop:88, style:'strike'} },
  { id:'l_gunther', name:'Gunther', era:'modern', rarity:'epic',
    attr:{label:'The Ring General', b:{po:14,ps:12,to:8}}, move:{name:'Powerbomb', kind:'finisher', dmg:82, pop:80, style:'power'} },
  { id:'l_rhea', name:'Rhea Ripley', era:'modern', rarity:'epic',
    attr:{label:'Mami', b:{po:14,ch:10,to:8}}, move:{name:'Riptide', kind:'finisher', dmg:80, pop:84, style:'power'} },
  { id:'l_mjf', name:'MJF', era:'modern', rarity:'epic',
    attr:{label:'Generational Heat', b:{ch:20,ps:10}}, move:{name:'Heatseeker', kind:'finisher', dmg:74, pop:82, style:'technical'} },

  // ================= PURORESU =================
  { id:'l_misawa', name:'Mitsuharu Misawa', era:'puro', rarity:'legendary',
    attr:{label:'King\'s Road', b:{ps:18,to:12,st:10}}, move:{name:'Emerald Flowsion', kind:'finisher', dmg:86, pop:88, style:'power'} },
  { id:'l_kobashi', name:'Kenta Kobashi', era:'puro', rarity:'legendary',
    attr:{label:'Absolute Fighting Spirit', b:{to:18,po:12,st:10}}, move:{name:'Burning Hammer', kind:'finisher', dmg:92, pop:90, style:'power'} },
  { id:'l_inoki', name:'Antonio Inoki', era:'puro', rarity:'epic',
    attr:{label:'Strong Style Origin', b:{ps:14,te:12}}, move:{name:'Enzuigiri', kind:'signature', dmg:68, pop:74, style:'strike'} },
  { id:'l_tanahashi', name:'Hiroshi Tanahashi', era:'puro', rarity:'legendary',
    attr:{label:'Ace of the Universe', b:{ch:14,ps:14,te:10}}, move:{name:'High Fly Flow', kind:'finisher', dmg:80, pop:90, style:'aerial'} },
  { id:'l_okada', name:'Kazuchika Okada', era:'puro', rarity:'legendary',
    attr:{label:'Rainmaker', b:{ps:18,te:12,ch:8}}, move:{name:'Rainmaker', kind:'finisher', dmg:84, pop:92, style:'strike'} },
  { id:'l_naito', name:'Tetsuya Naito', era:'puro', rarity:'epic',
    attr:{label:'Tranquilo', b:{ch:14,ps:10,te:8}}, move:{name:'Destino', kind:'finisher', dmg:80, pop:84, style:'technical'} },
  { id:'l_shibata', name:'Katsuyori Shibata', era:'puro', rarity:'epic',
    attr:{label:'Stiff Striker', b:{to:16,te:10}}, move:{name:'PK (Penalty Kick)', kind:'finisher', dmg:78, pop:78, style:'strike'} },
  { id:'l_liger', name:'Jushin Thunder Liger', era:'puro', rarity:'epic',
    attr:{label:'Junior Heavyweight King', b:{ae:16,te:12}}, move:{name:'Shooting Star Press', kind:'finisher', dmg:78, pop:84, style:'aerial'} },
  { id:'l_zsj', name:'Zack Sabre Jr.', era:'puro', rarity:'epic',
    attr:{label:'Submission Technician', b:{te:20,ps:8}}, move:{name:'Zack Driver', kind:'finisher', dmg:76, pop:78, style:'technical'} },
  { id:'l_ishii', name:'Tomohiro Ishii', era:'puro', rarity:'rare',
    attr:{label:'Stone Pitbull', b:{to:18,po:8}}, move:{name:'Brainbuster', kind:'finisher', dmg:78, pop:76, style:'power'} },
  { id:'l_suzuki', name:'Minoru Suzuki', era:'puro', rarity:'epic',
    attr:{label:'King of Pancrase', b:{te:14,to:12,ps:8}}, move:{name:'Gotch-Style Piledriver', kind:'finisher', dmg:82, pop:80, style:'technical'} },
  { id:'l_hashimoto', name:'Shinya Hashimoto', era:'puro', rarity:'rare',
    attr:{label:'Destroyer Kicks', b:{po:10,to:12}}, move:{name:'Vertical Drop DDT', kind:'signature', dmg:72, pop:70, style:'strike'} },

  // ================= LUCHA LIBRE =================
  { id:'l_santo', name:'El Santo', era:'lucha', rarity:'legendary',
    attr:{label:'The Silver Mask', b:{ch:18,ps:12,te:8}}, move:{name:'La De a Caballo', kind:'finisher', dmg:74, pop:94, style:'technical'} },
  { id:'l_blueDemon', name:'Blue Demon', era:'lucha', rarity:'epic',
    attr:{label:'Lucha Icon', b:{ch:12,te:10,to:6}}, move:{name:'Tope Suicida', kind:'signature', dmg:66, pop:78, style:'aerial'} },
  { id:'l_perro', name:'Perro Aguayo', era:'lucha', rarity:'epic',
    attr:{label:'Rudo Brawler', b:{to:14,ch:10}}, move:{name:'Senton Bomb', kind:'finisher', dmg:74, pop:76, style:'aerial'} },
  { id:'l_atlantis', name:'Atlantis', era:'lucha', rarity:'rare',
    attr:{label:'Mask Hunter', b:{te:12,ps:8}}, move:{name:'La Atlantida', kind:'finisher', dmg:74, pop:76, style:'technical'} },
  { id:'l_mistico', name:'Mistico', era:'lucha', rarity:'legendary',
    attr:{label:'Flight of the Angel', b:{ae:22,ch:10,te:6}}, move:{name:'La Mistica', kind:'finisher', dmg:76, pop:88, style:'aerial'} },
  { id:'l_dragon', name:'Ultimo Dragon', era:'lucha', rarity:'epic',
    attr:{label:'Eight Belts', b:{te:14,ae:12}}, move:{name:'Asai Moonsault', kind:'signature', dmg:70, pop:78, style:'aerial'} },
  { id:'l_juvi', name:'Juventud Guerrera', era:'lucha', rarity:'rare',
    attr:{label:'Juice Is Loose', b:{ae:14,ch:8}}, move:{name:'450 Splash', kind:'finisher', dmg:76, pop:76, style:'aerial'} },
  { id:'l_psicosis', name:'Psicosis', era:'lucha', rarity:'rare',
    attr:{label:'Reckless Flyer', b:{ae:13,to:8}}, move:{name:'Guillotine Legdrop', kind:'signature', dmg:68, pop:68, style:'aerial'} },
  { id:'l_vikingo', name:'El Hijo del Vikingo', era:'lucha', rarity:'legendary',
    attr:{label:'Gravity Optional', b:{ae:24,st:8}}, move:{name:'630 Splash', kind:'finisher', dmg:82, pop:88, style:'aerial'} },
  { id:'l_penta', name:'Penta El Zero M', era:'lucha', rarity:'epic',
    attr:{label:'Cero Miedo', b:{ch:14,to:10,ae:8}}, move:{name:'Package Piledriver', kind:'finisher', dmg:80, pop:84, style:'power'} },
  { id:'l_fenix', name:'Rey Fenix', era:'lucha', rarity:'epic',
    attr:{label:'King of Flight', b:{ae:20,te:8}}, move:{name:'Fire Thunder Driver', kind:'finisher', dmg:78, pop:82, style:'power'} },
  { id:'l_dosCaras', name:'Dos Caras', era:'lucha', rarity:'rare',
    attr:{label:'Technical Lucha', b:{te:14,ps:6}}, move:{name:'Reverse Figure Four', kind:'signature', dmg:68, pop:66, style:'technical'} },
];
