window.RTR_ROSTER = [
 {
  "id": "w0001",
  "name": "Cody Rhodes",
  "promotion": "WWE",
  "tier": "elite",
  "align": "heel",
  "inRing": 84,
  "psych": 78,
  "ent": 93,
  "phys": 77,
  "overness": 85,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 22971
 },
 {
  "id": "w0002",
  "name": "Roman Reigns",
  "promotion": "WWE",
  "tier": "elite",
  "align": "heel",
  "inRing": 88,
  "psych": 80,
  "ent": 80,
  "phys": 75,
  "overness": 87,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 16215
 },
 {
  "id": "w0003",
  "name": "Seth Rollins",
  "promotion": "WWE",
  "tier": "elite",
  "align": "heel",
  "inRing": 87,
  "psych": 81,
  "ent": 88,
  "phys": 78,
  "overness": 92,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 13467
 },
 {
  "id": "w0004",
  "name": "CM Punk",
  "promotion": "WWE",
  "tier": "elite",
  "align": "heel",
  "inRing": 92,
  "psych": 82,
  "ent": 81,
  "phys": 74,
  "overness": 89,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 13091
 },
 {
  "id": "w0005",
  "name": "Gunther",
  "promotion": "WWE",
  "tier": "elite",
  "align": "face",
  "inRing": 84,
  "psych": 83,
  "ent": 90,
  "phys": 81,
  "overness": 85,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 17735
 },
 {
  "id": "w0006",
  "name": "Rhea Ripley",
  "promotion": "WWE",
  "tier": "elite",
  "align": "face",
  "inRing": 91,
  "psych": 81,
  "ent": 83,
  "phys": 80,
  "overness": 92,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 11592
 },
 {
  "id": "w0007",
  "name": "Bianca Belair",
  "promotion": "WWE",
  "tier": "elite",
  "align": "face",
  "inRing": 86,
  "psych": 83,
  "ent": 82,
  "phys": 74,
  "overness": 87,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 14907
 },
 {
  "id": "w0008",
  "name": "Jacob Fatu",
  "promotion": "WWE",
  "tier": "elite",
  "align": "heel",
  "inRing": 84,
  "psych": 86,
  "ent": 82,
  "phys": 79,
  "overness": 85,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 21507
 },
 {
  "id": "w0009",
  "name": "Jey Uso",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 78,
  "psych": 72,
  "ent": 69,
  "phys": 80,
  "overness": 82,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 20932
 },
 {
  "id": "w0010",
  "name": "Jimmy Uso",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 74,
  "psych": 73,
  "ent": 68,
  "phys": 78,
  "overness": 72,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 21185
 },
 {
  "id": "w0011",
  "name": "Damian Priest",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 76,
  "psych": 74,
  "ent": 71,
  "phys": 71,
  "overness": 80,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 24912
 },
 {
  "id": "w0012",
  "name": "Drew McIntyre",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 82,
  "psych": 72,
  "ent": 72,
  "phys": 74,
  "overness": 73,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 12450
 },
 {
  "id": "w0013",
  "name": "LA Knight",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 79,
  "psych": 70,
  "ent": 80,
  "phys": 72,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 24892
 },
 {
  "id": "w0014",
  "name": "Randy Orton",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 78,
  "psych": 76,
  "ent": 82,
  "phys": 72,
  "overness": 75,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 17496
 },
 {
  "id": "w0015",
  "name": "Liv Morgan",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 81,
  "psych": 78,
  "ent": 81,
  "phys": 74,
  "overness": 76,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 11950
 },
 {
  "id": "w0016",
  "name": "IYO SKY",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 75,
  "psych": 68,
  "ent": 77,
  "phys": 76,
  "overness": 72,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 22158
 },
 {
  "id": "w0017",
  "name": "Bron Breakker",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 73,
  "psych": 79,
  "ent": 68,
  "phys": 73,
  "overness": 74,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 24458
 },
 {
  "id": "w0018",
  "name": "Sami Zayn",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 75,
  "psych": 77,
  "ent": 70,
  "phys": 70,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 20794
 },
 {
  "id": "w0019",
  "name": "Finn Balor",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 79,
  "psych": 79,
  "ent": 79,
  "phys": 71,
  "overness": 80,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 20075
 },
 {
  "id": "w0020",
  "name": "Kevin Owens",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 83,
  "psych": 73,
  "ent": 83,
  "phys": 80,
  "overness": 79,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 22755
 },
 {
  "id": "w0021",
  "name": "Solo Sikoa",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 81,
  "psych": 78,
  "ent": 74,
  "phys": 71,
  "overness": 82,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 22025
 },
 {
  "id": "w0022",
  "name": "Dominik Mysterio",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 86,
  "psych": 68,
  "ent": 73,
  "phys": 83,
  "overness": 73,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 18066
 },
 {
  "id": "w0023",
  "name": "Rey Mysterio",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 76,
  "psych": 79,
  "ent": 69,
  "phys": 69,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 14342
 },
 {
  "id": "w0024",
  "name": "Bayley",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 82,
  "psych": 79,
  "ent": 73,
  "phys": 74,
  "overness": 80,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 20640
 },
 {
  "id": "w0025",
  "name": "Becky Lynch",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 83,
  "psych": 74,
  "ent": 70,
  "phys": 81,
  "overness": 74,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 16470
 },
 {
  "id": "w0026",
  "name": "Stephanie Vaquer",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 74,
  "psych": 70,
  "ent": 71,
  "phys": 76,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 22520
 },
 {
  "id": "w0027",
  "name": "Tiffany Stratton",
  "promotion": "WWE",
  "tier": "upper",
  "align": "face",
  "inRing": 74,
  "psych": 74,
  "ent": 82,
  "phys": 73,
  "overness": 73,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 19379
 },
 {
  "id": "w0028",
  "name": "Jade Cargill",
  "promotion": "WWE",
  "tier": "upper",
  "align": "heel",
  "inRing": 76,
  "psych": 72,
  "ent": 78,
  "phys": 77,
  "overness": 77,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 20703
 },
 {
  "id": "w0029",
  "name": "Austin Theory",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 69,
  "psych": 65,
  "ent": 67,
  "phys": 74,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 23822
 },
 {
  "id": "w0030",
  "name": "Bronson Reed",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 66,
  "psych": 59,
  "ent": 56,
  "phys": 69,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 24804
 },
 {
  "id": "w0031",
  "name": "Chad Gable",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 66,
  "ent": 65,
  "phys": 63,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 16877
 },
 {
  "id": "w0032",
  "name": "Dragon Lee",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 68,
  "psych": 58,
  "ent": 64,
  "phys": 66,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 11865
 },
 {
  "id": "w0033",
  "name": "Ethan Page",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 62,
  "psych": 59,
  "ent": 59,
  "phys": 67,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 17863
 },
 {
  "id": "w0034",
  "name": "Grayson Waller",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 60,
  "psych": 59,
  "ent": 61,
  "phys": 66,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 13424
 },
 {
  "id": "w0035",
  "name": "Ivar",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 64,
  "psych": 59,
  "ent": 68,
  "phys": 75,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 19653
 },
 {
  "id": "w0036",
  "name": "Erik",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 74,
  "psych": 62,
  "ent": 67,
  "phys": 74,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 12103
 },
 {
  "id": "w0037",
  "name": "JD McDonagh",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 67,
  "ent": 66,
  "phys": 69,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 17767
 },
 {
  "id": "w0038",
  "name": "Ludwig Kaiser",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 70,
  "psych": 58,
  "ent": 70,
  "phys": 65,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 21173
 },
 {
  "id": "w0039",
  "name": "Montez Ford",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 69,
  "psych": 60,
  "ent": 66,
  "phys": 63,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 23506
 },
 {
  "id": "w0040",
  "name": "Angelo Dawkins",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 63,
  "psych": 62,
  "ent": 57,
  "phys": 61,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 16096
 },
 {
  "id": "w0041",
  "name": "Oba Femi",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 63,
  "psych": 62,
  "ent": 64,
  "phys": 73,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 21765
 },
 {
  "id": "w0042",
  "name": "Otis",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 66,
  "psych": 64,
  "ent": 68,
  "phys": 74,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 19002
 },
 {
  "id": "w0043",
  "name": "Penta",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 67,
  "psych": 56,
  "ent": 57,
  "phys": 62,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 17033
 },
 {
  "id": "w0044",
  "name": "Rey Fenix",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 61,
  "psych": 63,
  "ent": 61,
  "phys": 72,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 21280
 },
 {
  "id": "w0045",
  "name": "Rusev",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 72,
  "psych": 68,
  "ent": 58,
  "phys": 68,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 25136
 },
 {
  "id": "w0046",
  "name": "Sheamus",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 70,
  "psych": 66,
  "ent": 57,
  "phys": 69,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 19520
 },
 {
  "id": "w0047",
  "name": "Tyler Bate",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 75,
  "psych": 57,
  "ent": 62,
  "phys": 64,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 15377
 },
 {
  "id": "w0048",
  "name": "Pete Dunne",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 70,
  "psych": 57,
  "ent": 65,
  "phys": 75,
  "overness": 60,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 23489
 },
 {
  "id": "w0049",
  "name": "Carmelo Hayes",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 71,
  "psych": 64,
  "ent": 59,
  "phys": 66,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 18590
 },
 {
  "id": "w0050",
  "name": "Ilja Dragunov",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 70,
  "psych": 65,
  "ent": 58,
  "phys": 75,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 24764
 },
 {
  "id": "w0051",
  "name": "Johnny Gargano",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 71,
  "psych": 65,
  "ent": 67,
  "phys": 74,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 16233
 },
 {
  "id": "w0052",
  "name": "The Miz",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 71,
  "psych": 65,
  "ent": 68,
  "phys": 74,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 18598
 },
 {
  "id": "w0053",
  "name": "R-Truth",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 72,
  "psych": 64,
  "ent": 69,
  "phys": 63,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 12693
 },
 {
  "id": "w0054",
  "name": "Shinsuke Nakamura",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 59,
  "ent": 61,
  "phys": 63,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 20780
 },
 {
  "id": "w0055",
  "name": "Trick Williams",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 60,
  "ent": 58,
  "phys": 63,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 15879
 },
 {
  "id": "w0056",
  "name": "Ricky Saints",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 72,
  "psych": 59,
  "ent": 60,
  "phys": 75,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 14803
 },
 {
  "id": "w0057",
  "name": "Nathan Frazer",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 75,
  "psych": 60,
  "ent": 65,
  "phys": 70,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 12280
 },
 {
  "id": "w0058",
  "name": "Axiom",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 72,
  "psych": 61,
  "ent": 72,
  "phys": 75,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 17864
 },
 {
  "id": "w0059",
  "name": "Alexa Bliss",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 60,
  "ent": 57,
  "phys": 63,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 11621
 },
 {
  "id": "w0060",
  "name": "Michin",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 69,
  "psych": 58,
  "ent": 59,
  "phys": 67,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 12506
 },
 {
  "id": "w0061",
  "name": "Nia Jax",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 72,
  "psych": 68,
  "ent": 63,
  "phys": 76,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 13877
 },
 {
  "id": "w0062",
  "name": "Piper Niven",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 69,
  "psych": 56,
  "ent": 60,
  "phys": 72,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 22581
 },
 {
  "id": "w0063",
  "name": "Chelsea Green",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 68,
  "psych": 63,
  "ent": 65,
  "phys": 74,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 15737
 },
 {
  "id": "w0064",
  "name": "Giulia",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 61,
  "psych": 62,
  "ent": 66,
  "phys": 61,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 17456
 },
 {
  "id": "w0065",
  "name": "Jordynne Grace",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 75,
  "psych": 59,
  "ent": 61,
  "phys": 76,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 24429
 },
 {
  "id": "w0066",
  "name": "Mariah May",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 62,
  "ent": 65,
  "phys": 73,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 16930
 },
 {
  "id": "w0067",
  "name": "Jacy Jayne",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 64,
  "psych": 63,
  "ent": 58,
  "phys": 60,
  "overness": 54,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 17619
 },
 {
  "id": "w0068",
  "name": "Fallon Henley",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 62,
  "psych": 67,
  "ent": 62,
  "phys": 70,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 15470
 },
 {
  "id": "w0069",
  "name": "Kiana James",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 65,
  "psych": 67,
  "ent": 60,
  "phys": 63,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 14575
 },
 {
  "id": "w0070",
  "name": "Natalya",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 67,
  "psych": 65,
  "ent": 56,
  "phys": 75,
  "overness": 64,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 13536
 },
 {
  "id": "w0071",
  "name": "Lyra Valkyria",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 71,
  "psych": 60,
  "ent": 66,
  "phys": 63,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 22656
 },
 {
  "id": "w0072",
  "name": "Maxxine Dupri",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 68,
  "ent": 68,
  "phys": 63,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 11600
 },
 {
  "id": "w0073",
  "name": "Roxanne Perez",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 61,
  "psych": 63,
  "ent": 69,
  "phys": 60,
  "overness": 54,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 22863
 },
 {
  "id": "w0074",
  "name": "Raquel Rodriguez",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 65,
  "psych": 61,
  "ent": 71,
  "phys": 73,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 22049
 },
 {
  "id": "w0075",
  "name": "Sol Ruca",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 56,
  "ent": 65,
  "phys": 69,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 12765
 },
 {
  "id": "w0076",
  "name": "Ivy Nile",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 62,
  "psych": 59,
  "ent": 66,
  "phys": 68,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 24089
 },
 {
  "id": "w0077",
  "name": "Brie Bella",
  "promotion": "WWE",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 64,
  "ent": 65,
  "phys": 60,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 15772
 },
 {
  "id": "w0078",
  "name": "Paige",
  "promotion": "WWE",
  "tier": "mid",
  "align": "face",
  "inRing": 72,
  "psych": 64,
  "ent": 71,
  "phys": 63,
  "overness": 52,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 24618
 },
 {
  "id": "w0079",
  "name": "Akira Tozawa",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 54,
  "psych": 51,
  "ent": 49,
  "phys": 57,
  "overness": 37,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 15367
 },
 {
  "id": "w0080",
  "name": "Bravo Americano",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 61,
  "psych": 47,
  "ent": 51,
  "phys": 70,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 17260
 },
 {
  "id": "w0081",
  "name": "El Grande Americano",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 56,
  "psych": 48,
  "ent": 47,
  "phys": 60,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 13422
 },
 {
  "id": "w0082",
  "name": "Rayo Americano",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 65,
  "psych": 50,
  "ent": 60,
  "phys": 62,
  "overness": 41,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 23231
 },
 {
  "id": "w0083",
  "name": "Cruz Del Toro",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 60,
  "psych": 49,
  "ent": 51,
  "phys": 64,
  "overness": 46,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 21997
 },
 {
  "id": "w0084",
  "name": "Joaquin Wilde",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 65,
  "psych": 46,
  "ent": 55,
  "phys": 54,
  "overness": 44,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 20921
 },
 {
  "id": "w0085",
  "name": "Je'Von Evans",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 54,
  "psych": 48,
  "ent": 60,
  "phys": 64,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 25168
 },
 {
  "id": "w0086",
  "name": "Julius Creed",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 50,
  "psych": 46,
  "ent": 52,
  "phys": 57,
  "overness": 39,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 12744
 },
 {
  "id": "w0087",
  "name": "Brutus Creed",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 56,
  "psych": 45,
  "ent": 53,
  "phys": 56,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 18264
 },
 {
  "id": "w0088",
  "name": "Joe Hendry",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 60,
  "psych": 53,
  "ent": 61,
  "phys": 62,
  "overness": 37,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 13567
 },
 {
  "id": "w0089",
  "name": "Angel",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 65,
  "psych": 51,
  "ent": 57,
  "phys": 65,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 16424
 },
 {
  "id": "w0090",
  "name": "Berto",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 65,
  "psych": 51,
  "ent": 47,
  "phys": 57,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 23281
 },
 {
  "id": "w0091",
  "name": "Danhausen",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 65,
  "psych": 49,
  "ent": 48,
  "phys": 69,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 10971
 },
 {
  "id": "w0092",
  "name": "Elton Prince",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 52,
  "psych": 46,
  "ent": 60,
  "phys": 54,
  "overness": 44,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 13453
 },
 {
  "id": "w0093",
  "name": "Kit Wilson",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 64,
  "psych": 46,
  "ent": 57,
  "phys": 57,
  "overness": 34,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 14082
 },
 {
  "id": "w0094",
  "name": "Matt Cardona",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 65,
  "psych": 52,
  "ent": 57,
  "phys": 58,
  "overness": 35,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 12980
 },
 {
  "id": "w0095",
  "name": "Royce Keys",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 62,
  "psych": 50,
  "ent": 54,
  "phys": 56,
  "overness": 43,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 17298
 },
 {
  "id": "w0096",
  "name": "Talla Tonga",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 59,
  "psych": 52,
  "ent": 52,
  "phys": 56,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 11218
 },
 {
  "id": "w0097",
  "name": "Tama Tonga",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 54,
  "psych": 56,
  "ent": 55,
  "phys": 63,
  "overness": 35,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 14112
 },
 {
  "id": "w0098",
  "name": "B-Fab",
  "promotion": "WWE",
  "tier": "lower",
  "align": "face",
  "inRing": 57,
  "psych": 50,
  "ent": 57,
  "phys": 59,
  "overness": 37,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 16829
 },
 {
  "id": "w0099",
  "name": "Candice LeRae",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 55,
  "psych": 47,
  "ent": 52,
  "phys": 61,
  "overness": 35,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 13610
 },
 {
  "id": "w0100",
  "name": "Kali Armstrong",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 58,
  "psych": 50,
  "ent": 55,
  "phys": 61,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 13047
 },
 {
  "id": "w0101",
  "name": "Lainey Reid",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 64,
  "psych": 55,
  "ent": 60,
  "phys": 65,
  "overness": 43,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 13705
 },
 {
  "id": "w0102",
  "name": "Lash Legend",
  "promotion": "WWE",
  "tier": "lower",
  "align": "heel",
  "inRing": 61,
  "psych": 44,
  "ent": 50,
  "phys": 61,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 19625
 },
 {
  "id": "w0103",
  "name": "Jon Moxley",
  "promotion": "AEW",
  "tier": "elite",
  "align": "heel",
  "inRing": 78,
  "psych": 86,
  "ent": 95,
  "phys": 79,
  "overness": 91,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 14690
 },
 {
  "id": "w0104",
  "name": "Will Ospreay",
  "promotion": "AEW",
  "tier": "elite",
  "align": "face",
  "inRing": 92,
  "psych": 83,
  "ent": 91,
  "phys": 72,
  "overness": 93,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 11594
 },
 {
  "id": "w0105",
  "name": "MJF",
  "promotion": "AEW",
  "tier": "elite",
  "align": "face",
  "inRing": 87,
  "psych": 89,
  "ent": 92,
  "phys": 81,
  "overness": 95,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 9103
 },
 {
  "id": "w0106",
  "name": "Bryan Danielson",
  "promotion": "AEW",
  "tier": "elite",
  "align": "heel",
  "inRing": 92,
  "psych": 84,
  "ent": 86,
  "phys": 86,
  "overness": 86,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 10645
 },
 {
  "id": "w0107",
  "name": "Kenny Omega",
  "promotion": "AEW",
  "tier": "elite",
  "align": "face",
  "inRing": 84,
  "psych": 88,
  "ent": 90,
  "phys": 77,
  "overness": 91,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 13828
 },
 {
  "id": "w0108",
  "name": "Swerve Strickland",
  "promotion": "AEW",
  "tier": "elite",
  "align": "face",
  "inRing": 91,
  "psych": 85,
  "ent": 83,
  "phys": 74,
  "overness": 88,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 12643
 },
 {
  "id": "w0109",
  "name": "Toni Storm",
  "promotion": "AEW",
  "tier": "elite",
  "align": "heel",
  "inRing": 91,
  "psych": 81,
  "ent": 84,
  "phys": 80,
  "overness": 91,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 16109
 },
 {
  "id": "w0110",
  "name": "Mercedes Mone",
  "promotion": "AEW",
  "tier": "elite",
  "align": "heel",
  "inRing": 84,
  "psych": 84,
  "ent": 81,
  "phys": 81,
  "overness": 92,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 9465
 },
 {
  "id": "w0111",
  "name": "Adam Copeland",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 84,
  "psych": 68,
  "ent": 80,
  "phys": 71,
  "overness": 73,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 19384
 },
 {
  "id": "w0112",
  "name": "Hangman Page",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 86,
  "psych": 76,
  "ent": 79,
  "phys": 80,
  "overness": 74,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 16590
 },
 {
  "id": "w0113",
  "name": "Chris Jericho",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 82,
  "psych": 78,
  "ent": 76,
  "phys": 83,
  "overness": 78,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 12936
 },
 {
  "id": "w0114",
  "name": "Christian Cage",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 72,
  "psych": 68,
  "ent": 77,
  "phys": 77,
  "overness": 77,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 11732
 },
 {
  "id": "w0115",
  "name": "Claudio Castagnoli",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 76,
  "psych": 80,
  "ent": 81,
  "phys": 78,
  "overness": 78,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 11461
 },
 {
  "id": "w0116",
  "name": "Darby Allin",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 75,
  "psych": 71,
  "ent": 70,
  "phys": 72,
  "overness": 78,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 16065
 },
 {
  "id": "w0117",
  "name": "Samoa Joe",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 73,
  "psych": 70,
  "ent": 73,
  "phys": 74,
  "overness": 76,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 17653
 },
 {
  "id": "w0118",
  "name": "Kazuchika Okada",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 73,
  "psych": 78,
  "ent": 71,
  "phys": 74,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 9416
 },
 {
  "id": "w0119",
  "name": "Konosuke Takeshita",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 81,
  "psych": 80,
  "ent": 78,
  "phys": 80,
  "overness": 74,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 10018
 },
 {
  "id": "w0120",
  "name": "Jay White",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 76,
  "psych": 70,
  "ent": 76,
  "phys": 81,
  "overness": 82,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 18757
 },
 {
  "id": "w0121",
  "name": "Ricochet",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 83,
  "psych": 69,
  "ent": 69,
  "phys": 75,
  "overness": 76,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 19878
 },
 {
  "id": "w0122",
  "name": "Athena",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 82,
  "psych": 78,
  "ent": 80,
  "phys": 83,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 11321
 },
 {
  "id": "w0123",
  "name": "Hikaru Shida",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 80,
  "psych": 69,
  "ent": 72,
  "phys": 70,
  "overness": 76,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 13177
 },
 {
  "id": "w0124",
  "name": "Jamie Hayter",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 75,
  "psych": 71,
  "ent": 76,
  "phys": 83,
  "overness": 70,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 11060
 },
 {
  "id": "w0125",
  "name": "Julia Hart",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 81,
  "psych": 80,
  "ent": 73,
  "phys": 71,
  "overness": 71,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 18496
 },
 {
  "id": "w0126",
  "name": "Kris Statlander",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 79,
  "psych": 80,
  "ent": 74,
  "phys": 77,
  "overness": 71,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 10901
 },
 {
  "id": "w0127",
  "name": "Willow Nightingale",
  "promotion": "AEW",
  "tier": "upper",
  "align": "face",
  "inRing": 78,
  "psych": 73,
  "ent": 69,
  "phys": 72,
  "overness": 76,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 15352
 },
 {
  "id": "w0128",
  "name": "Britt Baker",
  "promotion": "AEW",
  "tier": "upper",
  "align": "heel",
  "inRing": 75,
  "psych": 70,
  "ent": 74,
  "phys": 70,
  "overness": 77,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 13854
 },
 {
  "id": "w0129",
  "name": "Adam Cole",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 61,
  "psych": 67,
  "ent": 61,
  "phys": 67,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 11303
 },
 {
  "id": "w0130",
  "name": "Andrade El Idolo",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 62,
  "ent": 58,
  "phys": 62,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 9077
 },
 {
  "id": "w0131",
  "name": "Bandido",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 65,
  "psych": 65,
  "ent": 64,
  "phys": 66,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 13731
 },
 {
  "id": "w0132",
  "name": "Brody King",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 65,
  "ent": 61,
  "phys": 65,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 16726
 },
 {
  "id": "w0133",
  "name": "Buddy Matthews",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 63,
  "ent": 60,
  "phys": 72,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 11751
 },
 {
  "id": "w0134",
  "name": "Cash Wheeler",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 67,
  "psych": 64,
  "ent": 58,
  "phys": 75,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 11401
 },
 {
  "id": "w0135",
  "name": "Dax Harwood",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 56,
  "ent": 64,
  "phys": 69,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 14100
 },
 {
  "id": "w0136",
  "name": "Daniel Garcia",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 61,
  "psych": 62,
  "ent": 64,
  "phys": 61,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 10811
 },
 {
  "id": "w0137",
  "name": "Eddie Kingston",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 70,
  "psych": 67,
  "ent": 60,
  "phys": 73,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 16441
 },
 {
  "id": "w0138",
  "name": "Jack Perry",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 63,
  "ent": 57,
  "phys": 76,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 17071
 },
 {
  "id": "w0139",
  "name": "Kyle Fletcher",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 74,
  "psych": 64,
  "ent": 69,
  "phys": 66,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 13533
 },
 {
  "id": "w0140",
  "name": "Lance Archer",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 66,
  "psych": 60,
  "ent": 56,
  "phys": 74,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 18814
 },
 {
  "id": "w0141",
  "name": "Josh Alexander",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 70,
  "psych": 59,
  "ent": 68,
  "phys": 69,
  "overness": 60,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 16413
 },
 {
  "id": "w0142",
  "name": "PAC",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 68,
  "psych": 62,
  "ent": 60,
  "phys": 69,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 10146
 },
 {
  "id": "w0143",
  "name": "Rocky Romero",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 66,
  "psych": 60,
  "ent": 69,
  "phys": 62,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 17067
 },
 {
  "id": "w0144",
  "name": "Trent Beretta",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 66,
  "ent": 59,
  "phys": 70,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 16342
 },
 {
  "id": "w0145",
  "name": "Wardlow",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 73,
  "psych": 61,
  "ent": 58,
  "phys": 70,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 12101
 },
 {
  "id": "w0146",
  "name": "Roderick Strong",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 74,
  "psych": 58,
  "ent": 59,
  "phys": 71,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 20636
 },
 {
  "id": "w0147",
  "name": "Wheeler Yuta",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 66,
  "psych": 56,
  "ent": 58,
  "phys": 71,
  "overness": 52,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 15788
 },
 {
  "id": "w0148",
  "name": "Mike Bailey",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 70,
  "psych": 58,
  "ent": 71,
  "phys": 63,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 11226
 },
 {
  "id": "w0149",
  "name": "Komander",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 71,
  "psych": 56,
  "ent": 70,
  "phys": 62,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 19968
 },
 {
  "id": "w0150",
  "name": "Orange Cassidy",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 73,
  "psych": 66,
  "ent": 65,
  "phys": 66,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 17689
 },
 {
  "id": "w0151",
  "name": "Matthew Jackson",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 62,
  "psych": 66,
  "ent": 68,
  "phys": 71,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 20695
 },
 {
  "id": "w0152",
  "name": "Nicholas Jackson",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 74,
  "psych": 58,
  "ent": 69,
  "phys": 61,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 13188
 },
 {
  "id": "w0153",
  "name": "Marshall Von Erich",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 57,
  "ent": 62,
  "phys": 72,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 20552
 },
 {
  "id": "w0154",
  "name": "Ross Von Erich",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 66,
  "psych": 64,
  "ent": 69,
  "phys": 65,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 20254
 },
 {
  "id": "w0155",
  "name": "Deonna Purrazzo",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 68,
  "psych": 67,
  "ent": 69,
  "phys": 61,
  "overness": 60,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 19299
 },
 {
  "id": "w0156",
  "name": "Riho",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 64,
  "psych": 56,
  "ent": 71,
  "phys": 74,
  "overness": 54,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 12216
 },
 {
  "id": "w0157",
  "name": "Ruby Soho",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 71,
  "psych": 67,
  "ent": 61,
  "phys": 65,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 18324
 },
 {
  "id": "w0158",
  "name": "Serena Deeb",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 61,
  "psych": 61,
  "ent": 62,
  "phys": 68,
  "overness": 52,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 12266
 },
 {
  "id": "w0159",
  "name": "Skye Blue",
  "promotion": "AEW",
  "tier": "mid",
  "align": "heel",
  "inRing": 72,
  "psych": 63,
  "ent": 69,
  "phys": 66,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 12635
 },
 {
  "id": "w0160",
  "name": "Thunder Rosa",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 74,
  "psych": 62,
  "ent": 70,
  "phys": 68,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 20462
 },
 {
  "id": "w0161",
  "name": "Yuka Sakazaki",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 61,
  "psych": 62,
  "ent": 67,
  "phys": 68,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 11378
 },
 {
  "id": "w0162",
  "name": "Mina Shirakawa",
  "promotion": "AEW",
  "tier": "mid",
  "align": "face",
  "inRing": 70,
  "psych": 64,
  "ent": 63,
  "phys": 69,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 12690
 },
 {
  "id": "w0163",
  "name": "Big Bill",
  "promotion": "AEW",
  "tier": "lower",
  "align": "face",
  "inRing": 54,
  "psych": 56,
  "ent": 54,
  "phys": 56,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 13713
 },
 {
  "id": "w0164",
  "name": "Billy Gunn",
  "promotion": "AEW",
  "tier": "lower",
  "align": "heel",
  "inRing": 63,
  "psych": 46,
  "ent": 57,
  "phys": 58,
  "overness": 40,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 11461
 },
 {
  "id": "w0165",
  "name": "Bobby Lashley",
  "promotion": "AEW",
  "tier": "lower",
  "align": "heel",
  "inRing": 51,
  "psych": 49,
  "ent": 62,
  "phys": 65,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 17064
 },
 {
  "id": "w0166",
  "name": "Brian Cage",
  "promotion": "AEW",
  "tier": "lower",
  "align": "face",
  "inRing": 60,
  "psych": 46,
  "ent": 52,
  "phys": 58,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 17541
 },
 {
  "id": "w0167",
  "name": "MVP",
  "promotion": "AEW",
  "tier": "lower",
  "align": "heel",
  "inRing": 53,
  "psych": 45,
  "ent": 54,
  "phys": 56,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 16451
 },
 {
  "id": "w0168",
  "name": "Shelton Benjamin",
  "promotion": "AEW",
  "tier": "lower",
  "align": "heel",
  "inRing": 51,
  "psych": 53,
  "ent": 59,
  "phys": 61,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 13466
 },
 {
  "id": "w0169",
  "name": "Hook",
  "promotion": "AEW",
  "tier": "lower",
  "align": "heel",
  "inRing": 60,
  "psych": 53,
  "ent": 58,
  "phys": 69,
  "overness": 44,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 10759
 },
 {
  "id": "w0170",
  "name": "Kevin Knight",
  "promotion": "AEW",
  "tier": "lower",
  "align": "face",
  "inRing": 58,
  "psych": 55,
  "ent": 55,
  "phys": 65,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 16842
 },
 {
  "id": "w0171",
  "name": "Moose",
  "promotion": "TNA",
  "tier": "upper",
  "align": "heel",
  "inRing": 78,
  "psych": 68,
  "ent": 75,
  "phys": 78,
  "overness": 71,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 7990
 },
 {
  "id": "w0172",
  "name": "Nic Nemeth",
  "promotion": "TNA",
  "tier": "upper",
  "align": "heel",
  "inRing": 75,
  "psych": 68,
  "ent": 74,
  "phys": 69,
  "overness": 82,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 8948
 },
 {
  "id": "w0173",
  "name": "Mike Santana",
  "promotion": "TNA",
  "tier": "upper",
  "align": "face",
  "inRing": 82,
  "psych": 70,
  "ent": 69,
  "phys": 71,
  "overness": 75,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 8913
 },
 {
  "id": "w0174",
  "name": "Jordynne Grace",
  "promotion": "TNA",
  "tier": "upper",
  "align": "face",
  "inRing": 85,
  "psych": 71,
  "ent": 73,
  "phys": 84,
  "overness": 80,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 10857
 },
 {
  "id": "w0175",
  "name": "A.J. Francis",
  "promotion": "TNA",
  "tier": "mid",
  "align": "face",
  "inRing": 70,
  "psych": 63,
  "ent": 64,
  "phys": 67,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 10917
 },
 {
  "id": "w0176",
  "name": "Eddie Edwards",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 66,
  "psych": 64,
  "ent": 57,
  "phys": 71,
  "overness": 52,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 6169
 },
 {
  "id": "w0177",
  "name": "Frankie Kazarian",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 59,
  "ent": 71,
  "phys": 69,
  "overness": 60,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 6426
 },
 {
  "id": "w0178",
  "name": "Jeff Hardy",
  "promotion": "TNA",
  "tier": "mid",
  "align": "face",
  "inRing": 73,
  "psych": 60,
  "ent": 59,
  "phys": 65,
  "overness": 54,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 5142
 },
 {
  "id": "w0179",
  "name": "Matt Hardy",
  "promotion": "TNA",
  "tier": "mid",
  "align": "face",
  "inRing": 63,
  "psych": 64,
  "ent": 62,
  "phys": 75,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 10790
 },
 {
  "id": "w0180",
  "name": "Mustafa Ali",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 68,
  "psych": 65,
  "ent": 59,
  "phys": 71,
  "overness": 54,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 6076
 },
 {
  "id": "w0181",
  "name": "Rich Swann",
  "promotion": "TNA",
  "tier": "mid",
  "align": "face",
  "inRing": 71,
  "psych": 59,
  "ent": 59,
  "phys": 63,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 5000
 },
 {
  "id": "w0182",
  "name": "Leon Slater",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 75,
  "psych": 67,
  "ent": 64,
  "phys": 66,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 7422
 },
 {
  "id": "w0183",
  "name": "Alisha Edwards",
  "promotion": "TNA",
  "tier": "mid",
  "align": "face",
  "inRing": 71,
  "psych": 64,
  "ent": 66,
  "phys": 64,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 6547
 },
 {
  "id": "w0184",
  "name": "Masha Slamovich",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 75,
  "psych": 58,
  "ent": 62,
  "phys": 65,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 6147
 },
 {
  "id": "w0185",
  "name": "Tasha Steelz",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 73,
  "psych": 66,
  "ent": 71,
  "phys": 62,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 7284
 },
 {
  "id": "w0186",
  "name": "Xia Brookside",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 71,
  "psych": 67,
  "ent": 67,
  "phys": 71,
  "overness": 54,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 5287
 },
 {
  "id": "w0187",
  "name": "Jody Threat",
  "promotion": "TNA",
  "tier": "mid",
  "align": "heel",
  "inRing": 70,
  "psych": 59,
  "ent": 71,
  "phys": 73,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 6615
 },
 {
  "id": "w0188",
  "name": "BDE",
  "promotion": "TNA",
  "tier": "lower",
  "align": "heel",
  "inRing": 52,
  "psych": 49,
  "ent": 58,
  "phys": 57,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 6516
 },
 {
  "id": "w0189",
  "name": "Brian Myers",
  "promotion": "TNA",
  "tier": "lower",
  "align": "face",
  "inRing": 62,
  "psych": 50,
  "ent": 60,
  "phys": 67,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 7570
 },
 {
  "id": "w0190",
  "name": "Cedric Alexander",
  "promotion": "TNA",
  "tier": "lower",
  "align": "heel",
  "inRing": 61,
  "psych": 47,
  "ent": 49,
  "phys": 54,
  "overness": 39,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 9842
 },
 {
  "id": "w0191",
  "name": "Ricky Sosa",
  "promotion": "TNA",
  "tier": "lower",
  "align": "face",
  "inRing": 63,
  "psych": 54,
  "ent": 53,
  "phys": 69,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 4960
 },
 {
  "id": "w0192",
  "name": "Ash by Elegance",
  "promotion": "TNA",
  "tier": "lower",
  "align": "face",
  "inRing": 55,
  "psych": 47,
  "ent": 60,
  "phys": 55,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 5669
 },
 {
  "id": "w0193",
  "name": "Allie",
  "promotion": "TNA",
  "tier": "lower",
  "align": "heel",
  "inRing": 52,
  "psych": 54,
  "ent": 47,
  "phys": 65,
  "overness": 40,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 6176
 },
 {
  "id": "w0194",
  "name": "Indi Hartwell",
  "promotion": "TNA",
  "tier": "lower",
  "align": "face",
  "inRing": 51,
  "psych": 54,
  "ent": 46,
  "phys": 58,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 5991
 },
 {
  "id": "w0195",
  "name": "Mara Sade",
  "promotion": "TNA",
  "tier": "lower",
  "align": "heel",
  "inRing": 61,
  "psych": 53,
  "ent": 51,
  "phys": 65,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 5280
 },
 {
  "id": "w0196",
  "name": "Rosemary",
  "promotion": "TNA",
  "tier": "lower",
  "align": "face",
  "inRing": 56,
  "psych": 55,
  "ent": 50,
  "phys": 69,
  "overness": 35,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 5128
 },
 {
  "id": "w0197",
  "name": "KiLynn King",
  "promotion": "TNA",
  "tier": "lower",
  "align": "heel",
  "inRing": 51,
  "psych": 45,
  "ent": 50,
  "phys": 60,
  "overness": 41,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 8075
 },
 {
  "id": "w0198",
  "name": "Lei Ying Lee",
  "promotion": "TNA",
  "tier": "lower",
  "align": "face",
  "inRing": 51,
  "psych": 47,
  "ent": 50,
  "phys": 67,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 5877
 },
 {
  "id": "w0199",
  "name": "El Hijo del Vikingo",
  "promotion": "AAA",
  "tier": "upper",
  "align": "heel",
  "inRing": 72,
  "psych": 74,
  "ent": 82,
  "phys": 71,
  "overness": 72,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 9787
 },
 {
  "id": "w0200",
  "name": "Dominik Mysterio",
  "promotion": "AAA",
  "tier": "upper",
  "align": "face",
  "inRing": 86,
  "psych": 68,
  "ent": 73,
  "phys": 83,
  "overness": 73,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 7025
 },
 {
  "id": "w0201",
  "name": "Chavo Guerrero Jr.",
  "promotion": "AAA",
  "tier": "upper",
  "align": "heel",
  "inRing": 85,
  "psych": 71,
  "ent": 70,
  "phys": 73,
  "overness": 72,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 4895
 },
 {
  "id": "w0202",
  "name": "El Hijo de Dr. Wagner Jr.",
  "promotion": "AAA",
  "tier": "mid",
  "align": "heel",
  "inRing": 74,
  "psych": 64,
  "ent": 70,
  "phys": 66,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 8828
 },
 {
  "id": "w0203",
  "name": "El Texano Jr.",
  "promotion": "AAA",
  "tier": "mid",
  "align": "face",
  "inRing": 62,
  "psych": 61,
  "ent": 64,
  "phys": 71,
  "overness": 53,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 7014
 },
 {
  "id": "w0204",
  "name": "Octagon Jr.",
  "promotion": "AAA",
  "tier": "mid",
  "align": "face",
  "inRing": 75,
  "psych": 60,
  "ent": 64,
  "phys": 70,
  "overness": 54,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 9124
 },
 {
  "id": "w0205",
  "name": "Psycho Clown",
  "promotion": "AAA",
  "tier": "mid",
  "align": "face",
  "inRing": 62,
  "psych": 63,
  "ent": 67,
  "phys": 69,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 7304
 },
 {
  "id": "w0206",
  "name": "Pagano",
  "promotion": "AAA",
  "tier": "mid",
  "align": "face",
  "inRing": 66,
  "psych": 58,
  "ent": 66,
  "phys": 76,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 6893
 },
 {
  "id": "w0207",
  "name": "Laredo Kid",
  "promotion": "AAA",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 60,
  "ent": 70,
  "phys": 60,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 8049
 },
 {
  "id": "w0208",
  "name": "Drago",
  "promotion": "AAA",
  "tier": "mid",
  "align": "heel",
  "inRing": 73,
  "psych": 57,
  "ent": 71,
  "phys": 73,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 8602
 },
 {
  "id": "w0209",
  "name": "Myzteziz Jr.",
  "promotion": "AAA",
  "tier": "lower",
  "align": "heel",
  "inRing": 60,
  "psych": 53,
  "ent": 52,
  "phys": 61,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 4959
 },
 {
  "id": "w0210",
  "name": "Abismo Negro Jr.",
  "promotion": "AAA",
  "tier": "lower",
  "align": "heel",
  "inRing": 62,
  "psych": 45,
  "ent": 57,
  "phys": 64,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 4329
 },
 {
  "id": "w0211",
  "name": "Andy Panda Jr.",
  "promotion": "AAA",
  "tier": "lower",
  "align": "face",
  "inRing": 62,
  "psych": 44,
  "ent": 55,
  "phys": 65,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 8698
 },
 {
  "id": "w0212",
  "name": "Mr. Iguana",
  "promotion": "AAA",
  "tier": "lower",
  "align": "face",
  "inRing": 53,
  "psych": 50,
  "ent": 47,
  "phys": 59,
  "overness": 35,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 8646
 },
 {
  "id": "w0213",
  "name": "Kali Armstrong AAA",
  "promotion": "AAA",
  "tier": "lower",
  "align": "face",
  "inRing": 63,
  "psych": 47,
  "ent": 47,
  "phys": 60,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 6824
 },
 {
  "id": "w0214",
  "name": "Myka Lockwood",
  "promotion": "AAA",
  "tier": "lower",
  "align": "face",
  "inRing": 58,
  "psych": 50,
  "ent": 61,
  "phys": 69,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 5965
 },
 {
  "id": "w0215",
  "name": "Tavion Heights",
  "promotion": "AAA",
  "tier": "lower",
  "align": "face",
  "inRing": 50,
  "psych": 50,
  "ent": 56,
  "phys": 59,
  "overness": 37,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 7311
 },
 {
  "id": "w0216",
  "name": "Tate Wilder",
  "promotion": "AAA",
  "tier": "lower",
  "align": "heel",
  "inRing": 52,
  "psych": 49,
  "ent": 59,
  "phys": 68,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 7513
 },
 {
  "id": "w0217",
  "name": "NWA Gretta",
  "promotion": "AAA",
  "tier": "lower",
  "align": "face",
  "inRing": 56,
  "psych": 46,
  "ent": 56,
  "phys": 54,
  "overness": 34,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 7324
 },
 {
  "id": "w0218",
  "name": "Dalton Castle",
  "promotion": "ROH",
  "tier": "upper",
  "align": "face",
  "inRing": 75,
  "psych": 80,
  "ent": 69,
  "phys": 83,
  "overness": 70,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 3282
 },
 {
  "id": "w0219",
  "name": "Mercedes Martinez",
  "promotion": "ROH",
  "tier": "upper",
  "align": "face",
  "inRing": 74,
  "psych": 79,
  "ent": 84,
  "phys": 78,
  "overness": 79,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 4280
 },
 {
  "id": "w0220",
  "name": "Matt Taven",
  "promotion": "ROH",
  "tier": "mid",
  "align": "heel",
  "inRing": 69,
  "psych": 64,
  "ent": 66,
  "phys": 73,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 35,
  "salary": 3003
 },
 {
  "id": "w0221",
  "name": "Anthony Henry",
  "promotion": "ROH",
  "tier": "mid",
  "align": "heel",
  "inRing": 67,
  "psych": 68,
  "ent": 57,
  "phys": 72,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 4405
 },
 {
  "id": "w0222",
  "name": "Red Velvet",
  "promotion": "ROH",
  "tier": "mid",
  "align": "heel",
  "inRing": 72,
  "psych": 60,
  "ent": 66,
  "phys": 64,
  "overness": 60,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 6171
 },
 {
  "id": "w0223",
  "name": "Lady Frost",
  "promotion": "ROH",
  "tier": "mid",
  "align": "face",
  "inRing": 74,
  "psych": 68,
  "ent": 58,
  "phys": 70,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 5582
 },
 {
  "id": "w0224",
  "name": "Christyan Reid",
  "promotion": "ROH",
  "tier": "lower",
  "align": "heel",
  "inRing": 58,
  "psych": 48,
  "ent": 61,
  "phys": 57,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 4492
 },
 {
  "id": "w0225",
  "name": "Trish Adora",
  "promotion": "ROH",
  "tier": "lower",
  "align": "face",
  "inRing": 56,
  "psych": 50,
  "ent": 52,
  "phys": 57,
  "overness": 39,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 5259
 },
 {
  "id": "w0226",
  "name": "Charlette Renegade",
  "promotion": "ROH",
  "tier": "lower",
  "align": "heel",
  "inRing": 60,
  "psych": 45,
  "ent": 55,
  "phys": 57,
  "overness": 37,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 4068
 },
 {
  "id": "w0227",
  "name": "Robyn Renegade",
  "promotion": "ROH",
  "tier": "lower",
  "align": "heel",
  "inRing": 61,
  "psych": 54,
  "ent": 51,
  "phys": 59,
  "overness": 35,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 32,
  "salary": 3115
 },
 {
  "id": "w0228",
  "name": "Jacked Jameson",
  "promotion": "ROH",
  "tier": "lower",
  "align": "face",
  "inRing": 61,
  "psych": 48,
  "ent": 50,
  "phys": 64,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 6665
 },
 {
  "id": "w0229",
  "name": "Zack Sabre Jr.",
  "promotion": "NJPW",
  "tier": "elite",
  "align": "face",
  "inRing": 90,
  "psych": 88,
  "ent": 81,
  "phys": 87,
  "overness": 87,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 10333
 },
 {
  "id": "w0230",
  "name": "Hiroshi Tanahashi",
  "promotion": "NJPW",
  "tier": "elite",
  "align": "face",
  "inRing": 86,
  "psych": 80,
  "ent": 81,
  "phys": 73,
  "overness": 84,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 5811
 },
 {
  "id": "w0231",
  "name": "SANADA",
  "promotion": "NJPW",
  "tier": "upper",
  "align": "heel",
  "inRing": 72,
  "psych": 75,
  "ent": 84,
  "phys": 81,
  "overness": 79,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 11015
 },
 {
  "id": "w0232",
  "name": "EVIL",
  "promotion": "NJPW",
  "tier": "upper",
  "align": "heel",
  "inRing": 73,
  "psych": 79,
  "ent": 74,
  "phys": 69,
  "overness": 73,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 12211
 },
 {
  "id": "w0233",
  "name": "Tomohiro Ishii",
  "promotion": "NJPW",
  "tier": "upper",
  "align": "heel",
  "inRing": 80,
  "psych": 70,
  "ent": 79,
  "phys": 70,
  "overness": 77,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 9795
 },
 {
  "id": "w0234",
  "name": "El Phantasmo",
  "promotion": "NJPW",
  "tier": "upper",
  "align": "heel",
  "inRing": 81,
  "psych": 73,
  "ent": 69,
  "phys": 74,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 8921
 },
 {
  "id": "w0235",
  "name": "Hirooki Goto",
  "promotion": "NJPW",
  "tier": "upper",
  "align": "heel",
  "inRing": 83,
  "psych": 73,
  "ent": 80,
  "phys": 74,
  "overness": 77,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 8107
 },
 {
  "id": "w0236",
  "name": "Shota Umino",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 66,
  "ent": 59,
  "phys": 75,
  "overness": 60,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 7272
 },
 {
  "id": "w0237",
  "name": "Yota Tsuji",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 65,
  "psych": 59,
  "ent": 63,
  "phys": 64,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 8983
 },
 {
  "id": "w0238",
  "name": "Great-O-Kharn",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 65,
  "psych": 63,
  "ent": 62,
  "phys": 72,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 9444
 },
 {
  "id": "w0239",
  "name": "Taichi",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 69,
  "psych": 61,
  "ent": 61,
  "phys": 70,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 9433
 },
 {
  "id": "w0240",
  "name": "Douki",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 60,
  "psych": 58,
  "ent": 68,
  "phys": 65,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 11255
 },
 {
  "id": "w0241",
  "name": "Hikuleo",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "heel",
  "inRing": 62,
  "psych": 68,
  "ent": 67,
  "phys": 76,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 27,
  "salary": 11338
 },
 {
  "id": "w0242",
  "name": "Robbie Eagles",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "heel",
  "inRing": 60,
  "psych": 59,
  "ent": 68,
  "phys": 70,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 7946
 },
 {
  "id": "w0243",
  "name": "YOSHI-HASHI",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 61,
  "ent": 64,
  "phys": 75,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 7631
 },
 {
  "id": "w0244",
  "name": "Toru Yano",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 74,
  "psych": 61,
  "ent": 66,
  "phys": 73,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 11755
 },
 {
  "id": "w0245",
  "name": "Taiji Ishimori",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "heel",
  "inRing": 74,
  "psych": 62,
  "ent": 57,
  "phys": 69,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 6080
 },
 {
  "id": "w0246",
  "name": "TAKA Michinoku",
  "promotion": "NJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 74,
  "psych": 67,
  "ent": 69,
  "phys": 62,
  "overness": 57,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 12312
 },
 {
  "id": "w0247",
  "name": "Yuya Uemura",
  "promotion": "NJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 64,
  "psych": 55,
  "ent": 48,
  "phys": 70,
  "overness": 44,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 10705
 },
 {
  "id": "w0248",
  "name": "Ren Narita",
  "promotion": "NJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 53,
  "psych": 52,
  "ent": 61,
  "phys": 67,
  "overness": 43,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 34,
  "salary": 7533
 },
 {
  "id": "w0249",
  "name": "Kosei Fujita",
  "promotion": "NJPW",
  "tier": "lower",
  "align": "face",
  "inRing": 56,
  "psych": 56,
  "ent": 60,
  "phys": 68,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 6652
 },
 {
  "id": "w0250",
  "name": "Master Wato",
  "promotion": "NJPW",
  "tier": "lower",
  "align": "face",
  "inRing": 54,
  "psych": 44,
  "ent": 51,
  "phys": 61,
  "overness": 43,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 12029
 },
 {
  "id": "w0251",
  "name": "Titan",
  "promotion": "NJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 58,
  "psych": 48,
  "ent": 47,
  "phys": 62,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 8689
 },
 {
  "id": "w0252",
  "name": "Atlantis Jr.",
  "promotion": "NJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 56,
  "psych": 46,
  "ent": 56,
  "phys": 55,
  "overness": 43,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 7841
 },
 {
  "id": "w0253",
  "name": "Mayu Iwatani",
  "promotion": "Stardom",
  "tier": "elite",
  "align": "heel",
  "inRing": 92,
  "psych": 79,
  "ent": 80,
  "phys": 83,
  "overness": 91,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 5503
 },
 {
  "id": "w0254",
  "name": "Momo Watanabe",
  "promotion": "Stardom",
  "tier": "upper",
  "align": "face",
  "inRing": 78,
  "psych": 72,
  "ent": 69,
  "phys": 74,
  "overness": 74,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 5443
 },
 {
  "id": "w0255",
  "name": "Saya Kamitani",
  "promotion": "Stardom",
  "tier": "upper",
  "align": "heel",
  "inRing": 72,
  "psych": 76,
  "ent": 77,
  "phys": 79,
  "overness": 81,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 6739
 },
 {
  "id": "w0256",
  "name": "Suzu Suzuki",
  "promotion": "Stardom",
  "tier": "upper",
  "align": "face",
  "inRing": 86,
  "psych": 72,
  "ent": 82,
  "phys": 76,
  "overness": 82,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 8067
 },
 {
  "id": "w0257",
  "name": "Ami Sohrei",
  "promotion": "Stardom",
  "tier": "mid",
  "align": "heel",
  "inRing": 70,
  "psych": 66,
  "ent": 68,
  "phys": 70,
  "overness": 55,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 40,
  "salary": 6576
 },
 {
  "id": "w0258",
  "name": "Koguma",
  "promotion": "Stardom",
  "tier": "mid",
  "align": "face",
  "inRing": 75,
  "psych": 57,
  "ent": 67,
  "phys": 61,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 4473
 },
 {
  "id": "w0259",
  "name": "Natsupoi",
  "promotion": "Stardom",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 56,
  "ent": 64,
  "phys": 67,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 7433
 },
 {
  "id": "w0260",
  "name": "Starlight Kid",
  "promotion": "Stardom",
  "tier": "mid",
  "align": "face",
  "inRing": 72,
  "psych": 66,
  "ent": 66,
  "phys": 67,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 6920
 },
 {
  "id": "w0261",
  "name": "AZM",
  "promotion": "Stardom",
  "tier": "mid",
  "align": "face",
  "inRing": 72,
  "psych": 59,
  "ent": 64,
  "phys": 63,
  "overness": 61,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 29,
  "salary": 4251
 },
 {
  "id": "w0262",
  "name": "Hanan",
  "promotion": "Stardom",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 58,
  "ent": 61,
  "phys": 68,
  "overness": 62,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 37,
  "salary": 4078
 },
 {
  "id": "w0263",
  "name": "Saori Anou",
  "promotion": "Stardom",
  "tier": "lower",
  "align": "heel",
  "inRing": 59,
  "psych": 50,
  "ent": 57,
  "phys": 62,
  "overness": 37,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 5236
 },
 {
  "id": "w0264",
  "name": "Rina",
  "promotion": "Stardom",
  "tier": "lower",
  "align": "face",
  "inRing": 63,
  "psych": 51,
  "ent": 48,
  "phys": 67,
  "overness": 43,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 42,
  "salary": 4049
 },
 {
  "id": "w0265",
  "name": "Konami",
  "promotion": "Stardom",
  "tier": "lower",
  "align": "face",
  "inRing": 57,
  "psych": 52,
  "ent": 48,
  "phys": 56,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 7139
 },
 {
  "id": "w0266",
  "name": "Waka Tsukiyama",
  "promotion": "Stardom",
  "tier": "lower",
  "align": "face",
  "inRing": 59,
  "psych": 50,
  "ent": 58,
  "phys": 67,
  "overness": 44,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 33,
  "salary": 3643
 },
 {
  "id": "w0267",
  "name": "Yuna Mizumori",
  "promotion": "Stardom",
  "tier": "lower",
  "align": "heel",
  "inRing": 59,
  "psych": 47,
  "ent": 50,
  "phys": 58,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 7690
 },
 {
  "id": "w0268",
  "name": "Miyu Yamashita",
  "promotion": "TJPW",
  "tier": "elite",
  "align": "face",
  "inRing": 87,
  "psych": 84,
  "ent": 91,
  "phys": 87,
  "overness": 92,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 38,
  "salary": 4002
 },
 {
  "id": "w0269",
  "name": "Shoko Nakajima",
  "promotion": "TJPW",
  "tier": "upper",
  "align": "heel",
  "inRing": 80,
  "psych": 70,
  "ent": 75,
  "phys": 80,
  "overness": 70,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 2744
 },
 {
  "id": "w0270",
  "name": "Rika Tatsumi",
  "promotion": "TJPW",
  "tier": "upper",
  "align": "face",
  "inRing": 72,
  "psych": 78,
  "ent": 83,
  "phys": 76,
  "overness": 75,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 28,
  "salary": 3688
 },
 {
  "id": "w0271",
  "name": "Mizuki",
  "promotion": "TJPW",
  "tier": "upper",
  "align": "heel",
  "inRing": 84,
  "psych": 75,
  "ent": 78,
  "phys": 69,
  "overness": 74,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 2874
 },
 {
  "id": "w0272",
  "name": "Yuka Sakazaki",
  "promotion": "TJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 61,
  "psych": 62,
  "ent": 67,
  "phys": 68,
  "overness": 56,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 3034
 },
 {
  "id": "w0273",
  "name": "Miu Watanabe",
  "promotion": "TJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 59,
  "ent": 58,
  "phys": 64,
  "overness": 59,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 44,
  "salary": 4016
 },
 {
  "id": "w0274",
  "name": "Yuki Kamifuku",
  "promotion": "TJPW",
  "tier": "mid",
  "align": "heel",
  "inRing": 60,
  "psych": 62,
  "ent": 66,
  "phys": 71,
  "overness": 52,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 3899
 },
 {
  "id": "w0275",
  "name": "Wakana Uehara",
  "promotion": "TJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 64,
  "psych": 66,
  "ent": 70,
  "phys": 63,
  "overness": 63,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 43,
  "salary": 5077
 },
 {
  "id": "w0276",
  "name": "Hyper Misao",
  "promotion": "TJPW",
  "tier": "mid",
  "align": "face",
  "inRing": 66,
  "psych": 64,
  "ent": 59,
  "phys": 71,
  "overness": 52,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 5212
 },
 {
  "id": "w0277",
  "name": "Suzume",
  "promotion": "TJPW",
  "tier": "mid",
  "align": "heel",
  "inRing": 63,
  "psych": 65,
  "ent": 63,
  "phys": 68,
  "overness": 58,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 3375
 },
 {
  "id": "w0278",
  "name": "Raku",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "face",
  "inRing": 50,
  "psych": 54,
  "ent": 56,
  "phys": 62,
  "overness": 44,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 41,
  "salary": 3301
 },
 {
  "id": "w0279",
  "name": "Yuki Aino",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 62,
  "psych": 46,
  "ent": 49,
  "phys": 59,
  "overness": 40,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 25,
  "salary": 2647
 },
 {
  "id": "w0280",
  "name": "Pom Harajuku",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "face",
  "inRing": 55,
  "psych": 47,
  "ent": 55,
  "phys": 60,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 45,
  "salary": 4716
 },
 {
  "id": "w0281",
  "name": "Yuki Arai",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 60,
  "psych": 56,
  "ent": 55,
  "phys": 58,
  "overness": 38,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 31,
  "salary": 4196
 },
 {
  "id": "w0282",
  "name": "Kaya Toribami",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "face",
  "inRing": 58,
  "psych": 48,
  "ent": 55,
  "phys": 68,
  "overness": 37,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 30,
  "salary": 3391
 },
 {
  "id": "w0283",
  "name": "Shino Suzuki",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 54,
  "psych": 50,
  "ent": 62,
  "phys": 61,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 26,
  "salary": 4667
 },
 {
  "id": "w0284",
  "name": "HIMAWARI",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 55,
  "psych": 46,
  "ent": 55,
  "phys": 63,
  "overness": 45,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 24,
  "salary": 3868
 },
 {
  "id": "w0285",
  "name": "Toga",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 54,
  "psych": 49,
  "ent": 55,
  "phys": 60,
  "overness": 42,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 36,
  "salary": 4879
 },
 {
  "id": "w0286",
  "name": "Uta Takami",
  "promotion": "TJPW",
  "tier": "lower",
  "align": "heel",
  "inRing": 64,
  "psych": 46,
  "ent": 59,
  "phys": 60,
  "overness": 36,
  "momentum": 55,
  "condition": 90,
  "morale": 75,
  "age": 39,
  "salary": 4062
 }
];
