/* ============================================================
   RunTheRopes: The World (v1)
   ------------------------------------------------------------
   A wholly fictional wrestling universe: leagues you climb and
   characters you'll come to love or hate.

   Every character carries voice lines, a gimmick, traits and an
   authored pixel look, and tracks a RELATIONSHIP with you
   (respect + heat) that evolves across your career.

   tiers: indie → regional → national → global
   ============================================================ */
window.RTR_PROMOS = [
  { id:'gcw',    short:'GCW',  name:'Grit City Wrestling',            tier:'indie',    region:'Rust Belt, USA',
    color:'#a8602c', product:'Hardcore / Deathmatch',
    blurb:'A converted bingo hall, three hundred screaming lunatics, and absolutely no guardrails.' },
  { id:'cdp',    short:'CDP',  name:'Cellar Door Pro',                tier:'indie',    region:'Pacific Northwest, USA',
    color:'#5e7f8a', product:'Workrate Indie',
    blurb:'Art-school wrestling in a basement venue. Half the crowd are wrestlers themselves.' },
  { id:'sbcw',   short:'SBCW', name:'Steel Belt Championship Wrestling', tier:'regional', region:'Midwest, USA',
    color:'#7a6a4a', product:'Old-School Territory',
    blurb:'Armories, county fairs and a forty-year-old lineage. They still call it rasslin\' here.' },
  { id:'scw',    short:'SCW',  name:'Sunset Coast Wrestling',         tier:'regional', region:'California, USA',
    color:'#d2687a', product:'Flash & Spectacle',
    blurb:'Beachfront shows, neon lights and more cameras than seats. Style over substance, usually.' },
  { id:'rose',   short:'CR',   name:'Crimson Rose',                   tier:'regional', region:'Osaka, Japan',
    color:'#c0455f', product:'Joshi',
    blurb:'Fierce, fast and unforgiving. The toughest women\'s wrestling on the planet, run out of a converted cinema.' },
  { id:'acw',    short:'ACW',  name:'Apex Championship Wrestling',    tier:'national', region:'National TV, USA',
    color:'#3f7fbf', product:'Sports-Based Competition',
    blurb:'The credible alternative. Wins and losses matter, rankings are real, and the locker room is stacked.' },
  { id:'kaiju',  short:'KJP',  name:'Kaiju Puroresu',                 tier:'national', region:'Tokyo, Japan',
    color:'#4a8f76', product:'Strong Style',
    blurb:'Stiff, brutal and reverent. Thirty-minute wars in near silence until the crowd decides you\'ve earned noise.' },
  { id:'eterna', short:'LE',   name:'Lucha Eterna',                   tier:'national', region:'Mexico City, Mexico',
    color:'#d99a2b', product:'Lucha Libre',
    blurb:'Masks, legacy and flight. Losing your mask here means losing your name.' },
  { id:'cwf',    short:'CWF',  name:'Colossus Wrestling Federation',  tier:'global',   region:'Worldwide',
    color:'#c0392b', product:'Global Sports-Entertainment',
    blurb:'The giant. Stadium shows, private jets, and a machine that\'ll make you a god or chew you up.' },
];

/* look shorthand keys mirror the pixel renderer */
const L=(skin,hair,gear,trim,o)=>Object.assign({skin,hair,gear,trim},o||{});

window.RTR_CHARS = [
  // ================= GRIT CITY WRESTLING (indie) =================
  { id:'c_slade', name:'Deacon Slade', nick:'The Gravedigger of Grit City', promo:'gcw', align:'heel', over:44,
    style:'brawler', attrs:{po:62,te:44,ae:30,ch:58,ps:66,to:88,st:60}, finisher:'The Last Rites',
    gimmick:'A soft-spoken deathmatch preacher who treats every match as a sermon and every weapon as scripture.',
    traits:['fearless','respected','violent'],
    look:L('#b2764a','#241a12','#4a2f1b','#8a5533',{hairStyle:'long',face:'beard',attire:'trunks',boots:'tall',acc:'elbow',build:'heavy'}),
    lines:{ taunt:['You came to Grit City. Nobody comes here by accident.','I have bled in this building for eleven years. You\'ve been here eleven minutes.'],
            win:['Sermon over. Go home.'], lose:['Huh. The kid can take it.'],
            respect:['You didn\'t quit. Round here, that\'s the whole religion.'] } },

  { id:'c_trash', name:'Trina Mackey', nick:'Trash', promo:'gcw', align:'heel', over:38,
    style:'brawler', attrs:{po:54,te:48,ae:38,ch:64,ps:50,to:74,st:62}, finisher:'Bin Lid Bomb',
    gimmick:'Foul-mouthed scrapper who brings a literal trash can full of weapons and an encyclopedic vocabulary of insults.',
    traits:['loudmouth','chaotic'],
    look:L('#e8bd95','#b03a2e','#1a1a1a','#C6392C',{hairStyle:'mullet',attire:'tank',boots:'sneak',acc:'wrist',pattern:'stripe'}),
    lines:{ taunt:['Oh look, a HAIRCUT with a gym membership.','I\'ve been thrown off a balcony by a man twice your size. You don\'t scare me, sweetheart.'],
            win:['Put THAT on your little highlight reel.'], lose:['Lucky. Absolute fluke. Rematch.'],
            respect:['Alright. You aren\'t completely useless. Don\'t let it go to your head.'] } },

  { id:'c_cutler', name:'Big Country Cutler', nick:'The Friendliest Man Alive', promo:'gcw', align:'face', over:40,
    style:'powerhouse', attrs:{po:78,te:40,ae:22,ch:66,ps:48,to:72,st:54}, finisher:'The Hay Bale',
    gimmick:'A genuinely lovely 6\'8" farm boy who apologizes after every powerbomb and means it.',
    traits:['beloved','gentle','strong'],
    look:L('#f3d3b3','#c99b3d','#5bb083','#F4E8DB',{hairStyle:'short',face:'beard',attire:'singlet',boots:'short',build:'heavy'}),
    lines:{ taunt:['Now I don\'t want no trouble, but I\'m gonna have to slam ya.','Real sorry about this in advance, friend.'],
            win:['You okay? Here, take my hand.'], lose:['Well shoot. Good on ya!'],
            respect:['You\'re alright, you are. Come get a burger with us after.'] } },

  { id:'c_vex', name:'Vex', nick:'The Question Mark', promo:'gcw', align:'tweener', over:42,
    style:'highflyer', attrs:{po:44,te:64,ae:78,ch:52,ps:58,to:50,st:70}, finisher:'Riddle Me This',
    gimmick:'Never speaks, never unmasks, never explains. Communicates entirely through a small whiteboard.',
    traits:['mysterious','silent','agile'],
    look:L('#d29b6e','#241a12','#7a3f9d','#e0b341',{mask:'lucha',attire:'tights',boots:'tall',pattern:'split'}),
    lines:{ taunt:['[holds up whiteboard: "YOU AREN\'T READY"]','[whiteboard: "I HAVE WATCHED ALL 14 OF YOUR MATCHES"]'],
            win:['[whiteboard: "TOLD YOU"]'], lose:['[whiteboard, slowly: "...HUH"]'],
            respect:['[whiteboard: "GOOD. FINALLY. SOMEONE GOOD."]'] } },

  // ================= CELLAR DOOR PRO (indie) =================
  { id:'c_pip', name:'Pip Nakamura', nick:'Pocket Rocket', promo:'cdp', align:'face', over:41,
    style:'highflyer', attrs:{po:36,te:70,ae:84,ch:60,ps:56,to:46,st:78}, finisher:'Pip Drop',
    gimmick:'5\'2" and completely without fear. Will dive off anything that\'ll hold her weight, and some things that won\'t.',
    traits:['fearless','beloved','agile'],
    look:L('#e8bd95','#22c2a8','#2fbfa8','#F4E8DB',{hairStyle:'pony',attire:'tights',boots:'sneak',acc:'elbow',pattern:'stars'}),
    lines:{ taunt:['I\'m going to jump off something stupid and you can\'t stop me!','Everyone always says I\'m too small. Everyone is always wrong.'],
            win:['THAT\'s what I\'m talking about!'], lose:['Okay. OKAY. Noted. Next time.'],
            respect:['You kept up with me. Nobody keeps up with me!'] } },

  { id:'c_ravi', name:'Ravi Chandra', nick:'The Serpent', promo:'cdp', align:'heel', over:46,
    style:'technician', attrs:{po:48,te:84,ae:52,ch:62,ps:78,to:54,st:66}, finisher:'Coil',
    gimmick:'A cold, patient submission specialist who publicly rates every opponent out of ten and never gives above a four.',
    traits:['technical','condescending','patient'],
    look:L('#8a5533','#241a12','#5bb083','#e0b341',{hairStyle:'topknot',face:'goatee',attire:'tights',boots:'tall',pattern:'gold'}),
    lines:{ taunt:['I\'ve watched your tape. Generously, a three out of ten.','You wrestle like someone described wrestling to you over the phone.'],
            win:['I have revised my score. You\'re a two.'], lose:['...I\'ll be revising my notes.'],
            respect:['Seven out of ten. I\'ve never given a seven. Don\'t ask again.'] } },

  { id:'c_hoyt', name:'August Hoyt', nick:'The Adjunct Professor', promo:'cdp', align:'tweener', over:39,
    style:'technician', attrs:{po:44,te:76,ae:44,ch:70,ps:74,to:48,st:58}, finisher:'The Thesis',
    gimmick:'Teaches medieval literature by day. Cuts twenty-minute promos with footnotes. The crowd adores him ironically, then sincerely.',
    traits:['clever','cult-favorite'],
    look:L('#f3d3b3','#8a5a2b','#3b6ea5','#F4E8DB',{hairStyle:'short',face:'stache',attire:'singlet',boots:'short',acc:'shades'}),
    lines:{ taunt:['Your offense has no thesis. It\'s a series of unrelated assertions.','I\'ll be grading this match, and I do grade harshly.'],
            win:['A charitable C-minus. See me after class.'], lose:['Well argued. I concede the point.'],
            respect:['You have a real argument in there. I\'d like to see you defend it.'] } },

  // ================= STEEL BELT (regional) =================
  { id:'c_tank', name:'Tank Malone', nick:'The Last Territory Man', promo:'sbcw', align:'face', over:54,
    style:'brawler', attrs:{po:72,te:62,ae:24,ch:70,ps:84,to:82,st:56}, finisher:'Malone Driver',
    gimmick:'Twenty-six years in, one knee, zero patience for shortcuts. The measuring stick every young wrestler has to get past.',
    traits:['veteran','gatekeeper','respected','stubborn'],
    look:L('#d29b6e','#e8dcc0','#8a1c1c','#F4E8DB',{hairStyle:'short',face:'beard',attire:'trunks',boots:'tall',acc:'wrist',build:'heavy'}),
    lines:{ taunt:['I have forgotten more than you have learned, kid.','Everybody wants the spot. Nobody wants the twenty-six years.'],
            win:['Come back when you\'ve paid for it.'], lose:['...Well. There it is. Somebody finally took it.'],
            respect:['You listen. That\'s rarer than talent. Stick around, I\'ll show you some things.'] } },

  { id:'c_cassidy', name:'Cassidy Vale', nick:'The Sweetheart Assassin', promo:'sbcw', align:'heel', over:56,
    style:'technician', attrs:{po:52,te:80,ae:58,ch:82,ps:76,to:58,st:68}, finisher:'Kiss Goodnight',
    gimmick:'Beams at the crowd, signs every autograph, and will absolutely break your arm while apologizing sweetly.',
    traits:['manipulative','charismatic','technical'],
    look:L('#f3d3b3','#c99b3d','#d2687a','#F4E8DB',{hairStyle:'long',attire:'tights',boots:'tall',acc:'wrist',pattern:'stars'}),
    lines:{ taunt:['Oh, you\'re ADORABLE. Genuinely. I mean that.','I\'m going to be so nice to you right up until I\'m not.'],
            win:['No hard feelings! Truly. Get that looked at.'], lose:['Hm. That\'s going to bother me for a while.'],
            respect:['Okay. You\'re the real thing. That\'s annoying of you.'] } },

  { id:'c_tulley', name:'Hank Tulley', nick:'Two-Ton', promo:'sbcw', align:'face', over:50,
    style:'powerhouse', attrs:{po:84,te:44,ae:18,ch:74,ps:60,to:80,st:48}, finisher:'The Tulley Drop',
    gimmick:'Four hundred pounds of dad jokes. Dances badly, eats constantly, and hits like a collapsing building.',
    traits:['beloved','comedy','immovable'],
    look:L('#e8bd95','#4a2f1b','#e07b39','#1a1a1a',{hairStyle:'buzz',face:'beard',attire:'singlet',boots:'short',build:'heavy'}),
    lines:{ taunt:['I skipped lunch for this. Don\'t make me regret it.','They say I\'m out of shape. Round IS a shape, friend.'],
            win:['Whew! Somebody get me a sandwich.'], lose:['Ah, ya got me! Good hustle, kid.'],
            respect:['You\'re good people. I don\'t say that about many.'] } },

  { id:'c_roxy', name:'Roxy Riot', nick:'Three Chords And The Truth', promo:'sbcw', align:'tweener', over:52,
    style:'brawler', attrs:{po:60,te:56,ae:62,ch:78,ps:58,to:70,st:72}, finisher:'Feedback',
    gimmick:'Fronts a genuinely terrible punk band. Wrestles like the songs sound: fast, loud, slightly out of tune.',
    traits:['chaotic','loudmouth','beloved'],
    look:L('#e8bd95','#7a3f9d','#1a1a1a','#22c2a8',{hairStyle:'mohawk',attire:'tank',boots:'sneak',acc:'elbow',pattern:'split'}),
    lines:{ taunt:['We\'re opening for ourselves tonight and the set is YOU.','I have played to four people in a laundromat. A crowd doesn\'t rattle me.'],
            win:['THANK YOU GOODNIGHT!'], lose:['Ugh. Off-key. My fault.'],
            respect:['You\'ve got the noise in you. I respect the noise.'] } },

  // ================= SUNSET COAST (regional) =================
  { id:'c_kip', name:'Kip Sterling', nick:'The Golden Boy', promo:'scw', align:'heel', over:58,
    style:'showman', attrs:{po:58,te:66,ae:60,ch:86,ps:62,to:52,st:66}, finisher:'Sterling Silver',
    gimmick:'Impossibly handsome, relentlessly sponsored, and convinced the business owes him a favor. Can\'t stop looking at himself.',
    traits:['vain','connected','entitled'],
    look:L('#f3d3b3','#e8dcc0','#e0b341','#F4E8DB',{hairStyle:'swoop',attire:'tights',boots:'tall',acc:'shades',pattern:'gold'}),
    lines:{ taunt:['Do you know how many followers I have? Do you know how many YOU have?','I didn\'t come up through the indies. I was DISCOVERED. There\'s a difference.'],
            win:['Somebody get this on the socials. The lighting is perfect.'], lose:['That was the LIGHTING. That wasn\'t me.'],
            respect:['Ugh. Fine. You\'re marketable. I hate that you\'re marketable.'] } },

  { id:'c_dizzy', name:'Dizzy Dominguez', nick:'The Sunset Kid', promo:'scw', align:'face', over:55,
    style:'highflyer', attrs:{po:44,te:70,ae:88,ch:72,ps:60,to:52,st:82}, finisher:'Golden Hour',
    gimmick:'Grew up in the parking lot of this building selling churros. Now he headlines it. The crowd would die for him.',
    traits:['beloved','hometown','agile'],
    look:L('#b2764a','#241a12','#e07b39','#e0b341',{hairStyle:'spiky',attire:'tights',boots:'sneak',pattern:'flame'}),
    lines:{ taunt:['I sold churros in this parking lot. This building is MINE.','Everybody flies out here, hermano. Not everybody LANDS.'],
            win:['For the parking lot!'], lose:['Ay. Okay. You earned that one.'],
            respect:['You get it. You actually get it. Respect, hermano.'] } },

  { id:'c_mimi', name:'Mimi Sunshine', nick:'Relentlessly Positive', promo:'scw', align:'heel', over:53,
    style:'technician', attrs:{po:50,te:74,ae:56,ch:80,ps:70,to:56,st:60}, finisher:'Have A Nice Day',
    gimmick:'Smiles constantly. Has never once blinked on camera. Something is deeply wrong and everybody can feel it.',
    traits:['unsettling','manipulative'],
    look:L('#f3d3b3','#e8dcc0','#2fbfa8','#d2687a',{hairStyle:'pony',face:'warrior',attire:'tights',boots:'tall',pattern:'stars'}),
    lines:{ taunt:['I\'m SO happy you\'re here! I\'ve been thinking about you constantly!','Don\'t be nervous! I\'ll make it quick. Probably!'],
            win:['See? That was FUN! Say it was fun.'], lose:['...I\'m still smiling. Look. Look at me.'],
            respect:['I like you. I really, really like you. That should worry you.'] } },

  // ================= CRIMSON ROSE (regional, joshi) =================
  { id:'c_arashi', name:'Yuki Arashi', nick:'The Storm', promo:'rose', align:'face', over:60,
    style:'brawler', attrs:{po:66,te:78,ae:60,ch:64,ps:80,to:84,st:74}, finisher:'Typhoon Lariat',
    gimmick:'The ace of Crimson Rose. Chops so hard the front row flinches. Has never asked for a night off.',
    traits:['ace','stoic','respected','iron'],
    look:L('#e8bd95','#241a12','#c0455f','#F4E8DB',{hairStyle:'long',attire:'singlet',boots:'tall',acc:'wrist'}),
    lines:{ taunt:['Show me. Words are cheap here.','If you aren\'t going to hit me properly, don\'t hit me at all.'],
            win:['Not yet. Come back when you\'re ready.'], lose:['Good. The next generation is supposed to take it.'],
            respect:['You stood up. Again and again. That\'s the whole art.'] } },

  { id:'c_hoshi', name:'Hoshi', nick:'Idol Of The Ring', promo:'rose', align:'face', over:51,
    style:'highflyer', attrs:{po:40,te:68,ae:80,ch:88,ps:56,to:48,st:76}, finisher:'Encore',
    gimmick:'A genuine pop idol who wrestles between tours. Half the crowd came for the singing and stayed for the shooting star press.',
    traits:['beloved','showbiz','agile'],
    look:L('#f3d3b3','#e0e0e0','#d2687a','#F4E8DB',{hairStyle:'pony',attire:'tights',boots:'sneak',acc:'cape',pattern:'stars'}),
    lines:{ taunt:['Everyone always thinks I\'m just the singer. Everyone is always surprised.','I do two shows a night. This is the easy one.'],
            win:['Thank you all so much! Please buy the album!'], lose:['Ah! Okay! I\'ll train harder, I promise!'],
            respect:['You treated me like a wrestler. Not like a novelty. Thank you.'] } },

  // ================= APEX (national) =================
  { id:'c_jolene', name:'Jolene Rush', nick:'Ruthless', promo:'acw', align:'heel', over:70,
    style:'technician', attrs:{po:62,te:86,ae:64,ch:76,ps:84,to:66,st:74}, finisher:'The Rush Hour',
    gimmick:'Openly, unapologetically ambitious. Keeps a written list of everyone standing between her and the title and crosses names off on camera.',
    traits:['ambitious','ruthless','technical'],
    look:L('#d29b6e','#b03a2e','#3f7fbf','#e0b341',{hairStyle:'pony',attire:'singlet',boots:'tall',acc:'elbow',pattern:'stripe'}),
    lines:{ taunt:['You\'re number nine on my list. That isn\'t an insult. It\'s a schedule.','Nothing personal. Everything professional.'],
            win:['Crossed off. Next.'], lose:['You just moved up the list. Congratulations, I suppose.'],
            respect:['I\'m taking your name off the list. Not because you beat me, but because I\'d rather have you beside me.'] } },

  { id:'c_osei', name:'Prince Osei', nick:'The Crown', promo:'acw', align:'face', over:72,
    style:'powerhouse', attrs:{po:88,te:64,ae:48,ch:80,ps:70,to:80,st:70}, finisher:'Coronation Slam',
    gimmick:'Carries himself like actual royalty because he genuinely is: a deposed heir who chose the ring over the palace.',
    traits:['regal','powerful','beloved'],
    look:L('#5d3a22','#241a12','#e0b341','#7a3f9d',{hairStyle:'short',face:'beard',attire:'trunks',boots:'tall',acc:'cape',pattern:'gold',build:'heavy'}),
    lines:{ taunt:['I gave up a throne for this ring. Understand what that means.','Kneeling is optional. Falling isn\'t.'],
            win:['Rise. There\'s no shame in losing to a king.'], lose:['A crown is only borrowed. Wear it well.'],
            respect:['You have the bearing of someone who will matter. I have an eye for it.'] } },

  { id:'c_buzz', name:'Buzzsaw Bailey', nick:'The Human Circular Saw', promo:'acw', align:'heel', over:66,
    style:'brawler', attrs:{po:74,te:52,ae:40,ch:60,ps:58,to:92,st:68}, finisher:'The Wood Chipper',
    gimmick:'Genuinely doesn\'t appear to feel pain and is visibly delighted about it. Laughs during chair shots. His own.',
    traits:['unhinged','iron','violent'],
    look:L('#e8bd95','#241a12','#8a1c1c','#1a1a1a',{hairStyle:'bald',face:'skull',attire:'trunks',boots:'tall',acc:'elbow',build:'heavy'}),
    lines:{ taunt:['Hit me. No, HARDER. I\'m not joking, I want you to.','They took my license in two states. Two! Guess which ones!'],
            win:['That\'s IT? That\'s all you had?'], lose:['HA! HA HA! Do it again!'],
            respect:['You hit me properly. Nobody hits me properly anymore.'] } },

  { id:'c_kroll', name:'Warden Kroll', nick:'The Correctional Officer', promo:'acw', align:'heel', over:68,
    style:'technician', attrs:{po:70,te:80,ae:34,ch:66,ps:82,to:74,st:62}, finisher:'Solitary',
    gimmick:'A former prison guard who treats the ring as his yard and every opponent as an inmate with a sentence to serve.',
    traits:['sadistic','methodical','authority'],
    look:L('#d29b6e','#e8dcc0','#5e7f8a','#1a1a1a',{hairStyle:'buzz',face:'stache',attire:'singlet',boots:'pads',acc:'chain'}),
    lines:{ taunt:['I have processed nine hundred men. You aren\'t special, you\'re next.','Lights out is whenever I decide it is.'],
            win:['Sentence served. Don\'t reoffend.'], lose:['...Escape doesn\'t happen twice.'],
            respect:['You did your time and you didn\'t break. Noted. Genuinely.'] } },

  // ================= KAIJU PURORESU (national) =================
  { id:'c_ryu', name:'Ryu Kanazawa', nick:'The Thunder God', promo:'kaiju', align:'face', over:74,
    style:'brawler', attrs:{po:80,te:76,ae:44,ch:66,ps:86,to:90,st:78}, finisher:'Raijin Lariat',
    gimmick:'The ace of Kaiju. Fights every match like it is the last one anyone will ever see. Has main-evented with a broken orbital bone.',
    traits:['ace','iron','respected','stoic'],
    look:L('#e8bd95','#241a12','#4a8f76','#F4E8DB',{hairStyle:'short',attire:'trunks',boots:'tall',acc:'wrist',build:'heavy'}),
    lines:{ taunt:['Thirty minutes. If you\'re still standing, we\'ll talk.','I don\'t care who you are. I care what you do in the last five minutes.'],
            win:['Not enough. Train. Come back.'], lose:['...Then it\'s your time. Don\'t waste it.'],
            respect:['You went the distance with me. From tonight, you\'re somebody.'] } },

  { id:'c_sora', name:'Sora Takahashi', nick:'The Young Lion', promo:'kaiju', align:'face', over:48,
    style:'technician', attrs:{po:54,te:74,ae:56,ch:48,ps:62,to:70,st:80}, finisher:'Rising Sun Suplex',
    gimmick:'Two years into a brutal apprenticeship. Bows to everyone, sweeps the ring himself, and is quietly becoming terrifying.',
    traits:['humble','rising','disciplined'],
    look:L('#f3d3b3','#241a12','#1a1a1a','#F4E8DB',{hairStyle:'short',attire:'trunks',boots:'tall',build:'lean'}),
    lines:{ taunt:['Please. Don\'t hold back. I need to know where I am.','I\'m not ready. I\'m going anyway.'],
            win:['...Thank you. I learned something.'], lose:['I\'ll be better. I promise you I\'ll be better.'],
            respect:['You treated me as an equal before I earned it. I won\'t forget that.'] } },

  { id:'c_mori', name:'Kenji Mori', nick:'Iron Blossom', promo:'kaiju', align:'heel', over:65,
    style:'technician', attrs:{po:64,te:88,ae:38,ch:58,ps:84,to:76,st:70}, finisher:'Chrysanthemum Lock',
    gimmick:'A shooter with an arrangement of fresh flowers at ringside. Bows, then dismantles a limb with clinical patience.',
    traits:['technical','cold','patient'],
    look:L('#e8bd95','#241a12','#7a3f9d','#e8dcc0',{hairStyle:'topknot',attire:'tights',boots:'short',pattern:'split'}),
    lines:{ taunt:['I have chosen which of your joints we\'re discussing tonight.','Beauty and cruelty are the same discipline. Both require patience.'],
            win:['Your elbow will remember me longer than you will.'], lose:['Interesting. I mis-measured you.'],
            respect:['You defended well. Very few understand defense.'] } },

  // ================= LUCHA ETERNA (national) =================
  { id:'c_relampago', name:'El Relámpago', nick:'The Lightning', promo:'eterna', align:'face', over:71,
    style:'highflyer', attrs:{po:52,te:80,ae:94,ch:78,ps:72,to:56,st:86}, finisher:'Rayo Eterno',
    gimmick:'Third-generation luchador under a mask his grandfather bled in. Moves like the building has no ceiling.',
    traits:['legacy','beloved','agile'],
    look:L('#b2764a','#241a12','#e0b341','#c0392b',{mask:'lucha',attire:'tights',boots:'tall',acc:'cape',pattern:'gold'}),
    lines:{ taunt:['My grandfather wore this mask. My father wore this mask. You won\'t take it.','In this building we don\'t walk. We fly.'],
            win:['The mask stays. It always stays.'], lose:['You were magnificent. The mask stays, but you were magnificent.'],
            respect:['You honor the tradition. Come, fly with us.'] } },

  { id:'c_sangre', name:'Sangre Nueva', nick:'New Blood', promo:'eterna', align:'heel', over:57,
    style:'highflyer', attrs:{po:50,te:70,ae:86,ch:68,ps:54,to:58,st:80}, finisher:'Sangre Sunset',
    gimmick:'A masked rudo who thinks tradition is a cage. Deliberately disrespects the legends and the crowd loathes him for it.',
    traits:['arrogant','agile','disrespectful'],
    look:L('#d29b6e','#241a12','#8a1c1c','#1a1a1a',{mask:'lucha',attire:'tights',boots:'sneak',pattern:'flame'}),
    lines:{ taunt:['Tradition? Tradition is what old men call being slow.','I\'ll take your mask AND your spot. In that order.'],
            win:['New blood. Old blood on the mat.'], lose:['...This isn\'t over. This is nowhere near over.'],
            respect:['You aren\'t old. You aren\'t slow. Fine. FINE. You\'re worth my time.'] } },

  { id:'c_muerte', name:'La Señora Muerte', nick:'The Lady In The Mask', promo:'eterna', align:'heel', over:69,
    style:'brawler', attrs:{po:70,te:72,ae:62,ch:84,ps:78,to:80,st:66}, finisher:'Final Rest',
    gimmick:'Never speaks above a whisper. Carries a hand-painted skull mask she says belonged to someone who wronged her.',
    traits:['terrifying','mysterious','violent'],
    look:L('#8a5533','#241a12','#1a1a1a','#e0b341',{mask:'demon',attire:'duster',boots:'tall',acc:'chain'}),
    lines:{ taunt:['I\'ve already seen how this ends. I saw it last night.','Don\'t be afraid. Be ready. There\'s a difference and you have neither.'],
            win:['Sleep now.'], lose:['...You aren\'t on my list. Yet.'],
            respect:['You looked at me and didn\'t look away. Nobody does that.'] } },

  // ================= COLOSSUS (global) =================
  { id:'c_kaiser', name:'Duke Kaiser', nick:'The Kingmaker', promo:'cwf', align:'heel', over:92,
    style:'technician', attrs:{po:76,te:92,ae:52,ch:90,ps:94,to:74,st:78}, finisher:'The Coronation',
    gimmick:'Nine-time world champion who genuinely believes he doesn\'t beat opponents. He DECIDES which of them get to matter.',
    traits:['elite','political','arrogant','ace'],
    look:L('#f3d3b3','#e8dcc0','#c0392b','#e0b341',{hairStyle:'swoop',face:'goatee',attire:'duster',boots:'tall',acc:'belt',pattern:'gold'}),
    lines:{ taunt:['You should be thanking me for the exposure. Most people pay for this.','I don\'t beat people. I decide who matters. Tonight I\'ve decided you don\'t.'],
            win:['Another name in the ledger. Nobody will remember which line.'], lose:['Enjoy it. It\'s the last thing I\'ll ever give you for free.'],
            respect:['...You have it. The thing you can\'t teach. Don\'t let this business take it from you.'] } },

  { id:'c_amara', name:'Saint Amara', nick:'The Conscience Of The Business', promo:'cwf', align:'face', over:90,
    style:'technician', attrs:{po:70,te:90,ae:70,ch:88,ps:92,to:78,st:80}, finisher:'Absolution',
    gimmick:'The moral center of the locker room. Wrestles cleanly, speaks softly, and has quietly carried the company for a decade.',
    traits:['ace','respected','principled','beloved'],
    look:L('#8a5533','#241a12','#F4E8DB','#e0b341',{hairStyle:'topknot',attire:'singlet',boots:'tall',acc:'wrist',pattern:'gold'}),
    lines:{ taunt:['I\'m not here to humble you. I\'m here to find out what you are.','Wrestle me clean. You may not get the chance again.'],
            win:['Get up. You belong here, you just aren\'t finished.'], lose:['Then it\'s yours. Carry it better than I did.'],
            respect:['I\'ve been waiting a long time for someone to hand this to. Don\'t make me regret it.'] } },

  { id:'c_ozzy', name:'Ozzy Vance', nick:'The People\'s Migraine', promo:'cwf', align:'heel', over:84,
    style:'showman', attrs:{po:64,te:70,ae:58,ch:96,ps:80,to:62,st:70}, finisher:'The Last Word',
    gimmick:'The most annoying man alive and fully aware of it. Talks for twelve straight minutes. The boos are deafening and he drinks them like water.',
    traits:['loudmouth','charismatic','shameless'],
    look:L('#e8bd95','#b03a2e','#e07b39','#7a3f9d',{hairStyle:'spiky',face:'goatee',attire:'jacket',boots:'sneak',acc:'shades',pattern:'flame'}),
    lines:{ taunt:['I\'ve been talking for eleven minutes and you haven\'t said one interesting thing.','They aren\'t booing you. Don\'t flatter yourself. They\'re booing ME. That\'s a SKILL.'],
            win:['And THAT\'s why they pay me to talk.'], lose:['Okay. OKAY. Shutting up. Briefly.'],
            respect:['You made me stop talking. Do you know how hard that is?'] } },

  { id:'c_marla', name:'Mad Marla Kane', nick:'The Banshee', promo:'cwf', align:'heel', over:86,
    style:'brawler', attrs:{po:82,te:66,ae:56,ch:82,ps:74,to:94,st:76}, finisher:'The Wailing',
    gimmick:'Screams. Constantly. Has bitten a referee. Somehow also the locker room\'s most reliable veteran and a devoted mother of three.',
    traits:['unhinged','iron','violent','veteran'],
    look:L('#f3d3b3','#b03a2e','#8a1c1c','#1a1a1a',{hairStyle:'long',face:'tribal',attire:'tank',boots:'pads',acc:'elbow'}),
    lines:{ taunt:['I can hear your heartbeat from here and I don\'t like the rhythm.','They put me in a cage once. ONCE. Ask them how it went.'],
            win:['SHHHH. It\'s over. Shhh.'], lose:['...Good. GOOD! Finally somebody worth screaming at!'],
            respect:['You aren\'t scared of me. Everyone is scared of me. I like you.'] } },

  { id:'c_titus', name:'Titus Vault', nick:'The Human Skyscraper', promo:'cwf', align:'heel', over:82,
    style:'powerhouse', attrs:{po:98,te:44,ae:16,ch:64,ps:60,to:92,st:58}, finisher:'The Ground Floor',
    gimmick:'Seven foot four. Has never been legally lifted by another human being. Speaks perhaps once a year, and it\'s always terrifying.',
    traits:['monster','immovable','silent'],
    look:L('#d29b6e','#1a1a1a','#5e7f8a','#1a1a1a',{hairStyle:'bald',face:'none',attire:'trunks',boots:'tall',build:'heavy'}),
    lines:{ taunt:['...','You\'re standing in my building.'],
            win:['...'], lose:['[he simply looks at you, for a long time]'],
            respect:['[he nods once. In eleven years, he has done this four times.]'] } },

  { id:'c_rico', name:'Rico Delacroix', nick:'Last Call', promo:'cwf', align:'heel', over:78,
    style:'showman', attrs:{po:66,te:74,ae:62,ch:90,ps:76,to:64,st:66}, finisher:'Closing Time',
    gimmick:'Arrives with an entourage and a drink he never finishes. Insists he\'s only in this for the nightlife, and is lying.',
    traits:['charismatic','sleazy','underestimated'],
    look:L('#d29b6e','#241a12','#7a3f9d','#e0b341',{hairStyle:'swoop',face:'stache',attire:'jacket',boots:'sneak',acc:'chain',pattern:'gold'}),
    lines:{ taunt:['I\'ve been up since Thursday, friend, and I\'ll still out-wrestle you.','Don\'t take this personally. I don\'t take anything personally.'],
            win:['Last call. Go home.'], lose:['Ha! Beautiful. Drinks are on me. Genuinely.'],
            respect:['You\'re alright. Come out with us. I insist, and I never insist.'] } },

  { id:'c_nadia', name:'Nadia Volkov', nick:'The Iron Curtain', promo:'cwf', align:'heel', over:80,
    style:'powerhouse', attrs:{po:88,te:78,ae:40,ch:60,ps:80,to:88,st:72}, finisher:'Curtain Call',
    gimmick:'Trained in a system that produced exactly four survivors. Displays no emotion whatsoever, including when winning.',
    traits:['cold','powerful','disciplined'],
    look:L('#f3d3b3','#e8dcc0','#8a1c1c','#F4E8DB',{hairStyle:'pony',attire:'singlet',boots:'pads',acc:'elbow',pattern:'stripe'}),
    lines:{ taunt:['Eleven of us started. Four finished. I don\'t lose to people like you.','Emotion is a tax on performance. You pay it. I don\'t.'],
            win:['As expected.'], lose:['...Recalculating.'],
            respect:['You didn\'t flinch. In eleven years, three people haven\'t flinched.'] } },

  { id:'c_grange', name:'Bishop Grange', nick:'The Gatekeeper', promo:'cwf', align:'tweener', over:76,
    style:'technician', attrs:{po:68,te:86,ae:40,ch:74,ps:90,to:72,st:64}, finisher:'The Verdict',
    gimmick:'Never won the big one and never will. His entire purpose is deciding who\'s ready, and he\'s brutally, famously honest about it.',
    traits:['veteran','gatekeeper','honest','respected'],
    look:L('#5d3a22','#e8dcc0','#5e7f8a','#F4E8DB',{hairStyle:'short',face:'beard',attire:'singlet',boots:'tall',acc:'wrist'}),
    lines:{ taunt:['Everybody has to come through me. Nobody has ever liked it.','I\'m not the mountain, kid. I\'m the door. And it\'s shut.'],
            win:['Not yet. And I\'ll tell anyone who asks exactly why.'], lose:['...Door is open. Go on. Don\'t look back at me.'],
            respect:['I have sent home four hundred people. I\'m telling the office about you tonight.'] } },

  // ================= SECOND ROW: bodies for the small rooms =================
  // The indie and regional promotions had three people in them, so a first
  // year was the same two opponents forty times. Nine more, written to the
  // same schema, so a debut has somebody to be against who is not a champion.
  { id:'c_moth', name:'Bea Mothersole', nick:'The Moth', promo:'cdp', align:'tweener', over:38,
    style:'technician', attrs:{po:34,te:66,ae:58,ch:48,ps:62,to:44,st:70}, finisher:'Lights Out',
    gimmick:'Wrestles like she\'s solving a puzzle nobody else can see. Drawn to the brightest thing in the room, then takes it apart.',
    traits:['calculating','patient','overlooked'],
    look:L('#f3d3b3','#7a3f9d','#1a1a1a','#e0b341',{hairStyle:'buzz',attire:'singlet',boots:'short',acc:'wrist',pattern:'split'}),
    lines:{ taunt:['I\'ve already counted your moves. Eleven. I\'ll need four.','Don\'t rush. It won\'t help you.'],
            win:['Four.'], lose:['Interesting. A variable I didn\'t have.'],
            respect:['You aren\'t a solved problem. That\'s rare.'] } },

  { id:'c_dutch', name:'Dutch Halloran', nick:'The Understudy', promo:'cdp', align:'face', over:36,
    style:'brawler', attrs:{po:52,te:44,ae:30,ch:56,ps:40,to:70,st:64}, finisher:'Curtain Call',
    gimmick:'Failed actor, working stagehand, and the most enthusiastic man in the building. Has read every wrestling book ever printed.',
    traits:['beloved','workhorse','kind'],
    look:L('#e8bd95','#8a5a2b','#2f7fbf','#F4E8DB',{hairStyle:'mullet',face:'stache',attire:'trunks',boots:'pads',acc:'elbow',pattern:'stripe'}),
    lines:{ taunt:['I waited three years for a spot on this card. I\'m not giving it back.','Every night is opening night.'],
            win:['Thank you. Thank you. Really.'], lose:['Notes. I\'ll take notes.'],
            respect:['You made me look good out there. That\'s the whole job.'] } },

  { id:'c_shiv', name:'Shiv Danko', nick:'The Fork', promo:'gcw', align:'heel', over:40,
    style:'brawler', attrs:{po:50,te:36,ae:26,ch:60,ps:44,to:84,st:58}, finisher:'Table Manners',
    gimmick:'Deathmatch lifer. Counts scars the way other people count title reigns. Smiles the whole time.',
    traits:['violent','chaotic','loudmouth'],
    look:L('#d29b6e','#b03a2e','#1a1a1a','#C6392C',{hairStyle:'spiky',face:'beard',attire:'tank',boots:'short',acc:'chain',pattern:'flame'}),
    lines:{ taunt:['You bleed? Good. We can be friends.','I\'ve been stapled, sawed and set on fire. You\'re a Tuesday.'],
            win:['Cleanup on aisle you.'], lose:['Ha! HA! Again. Do it again.'],
            respect:['You took the light tube. You\'re one of us now.'] } },

  { id:'c_mabel', name:'Mabel Okonkwo', nick:'The Landlord', promo:'gcw', align:'face', over:43,
    style:'powerhouse', attrs:{po:80,te:42,ae:24,ch:62,ps:52,to:70,st:56}, finisher:'Eviction Notice',
    gimmick:'Owns the building GCW runs in. Wrestles because somebody has to keep the tenants in line.',
    traits:['strong','respected','stoic'],
    look:L('#5d3a22','#241a12','#e07b39','#1a1a1a',{hairStyle:'short',attire:'singlet',boots:'tall',acc:'belt',pattern:'solid'}),
    lines:{ taunt:['Rent is due.','I don\'t throw people out. I throw them through.'],
            win:['Out.'], lose:['You can stay. For now.'],
            respect:['Lease renewed. Don\'t make me regret it.'] } },

  { id:'c_lux', name:'Lux Delgado', nick:'Golden Hour', promo:'scw', align:'face', over:50,
    style:'highflyer', attrs:{po:42,te:58,ae:82,ch:78,ps:50,to:46,st:72}, finisher:'Sunset Flip Bomb',
    gimmick:'Skater, model, part-time stuntman. Every move is timed to the lighting rig.',
    traits:['showman','agile','cocky'],
    look:L('#d29b6e','#c99b3d','#d2687a','#F4E8DB',{hairStyle:'swoop',attire:'tights',boots:'sneak',acc:'shades',pattern:'gold'}),
    lines:{ taunt:['Golden hour is in twelve minutes. I\'ll be done by then.','Smile. You\'re in the background of my highlight.'],
            win:['Print it.'], lose:['Bad angle. Bad light. Bad night.'],
            respect:['You\'d look good in the reel. I mean that.'] } },

  { id:'c_rocco', name:'Rocco Santangelo', nick:'The Bouncer', promo:'scw', align:'heel', over:47,
    style:'powerhouse', attrs:{po:74,te:44,ae:28,ch:58,ps:56,to:76,st:52}, finisher:'Last Orders',
    gimmick:'Worked the door at every club on the strip. Wrestles like a man ending a night out.',
    traits:['ruthless','disciplined','veteran'],
    look:L('#e8bd95','#241a12','#1a1a1a','#e0b341',{hairStyle:'bald',face:'beard',attire:'trunks',boots:'tall',acc:'wrist',pattern:'solid'}),
    lines:{ taunt:['You aren\'t on the list.','I have thrown out bigger men for less.'],
            win:['Out you go.'], lose:['Alright. You\'re on the list.'],
            respect:['You can come in. Don\'t make it a habit.'] } },

  { id:'c_kaede', name:'Kaede Sato', nick:'Second Year', promo:'rose', align:'face', over:44,
    style:'technician', attrs:{po:44,te:70,ae:62,ch:54,ps:58,to:60,st:78}, finisher:'Sato Special',
    gimmick:'Second year in. Still bows to the ring on the way out. Will chop you until her hand goes numb.',
    traits:['disciplined','workhorse','loyal'],
    look:L('#f3d3b3','#241a12','#c0455f','#F4E8DB',{hairStyle:'short',attire:'singlet',boots:'pads',acc:'wrist',pattern:'stripe'}),
    lines:{ taunt:['Please. Teach me something.','I won\'t stay down. It\'s the only thing I\'m good at.'],
            win:['Thank you for the match!'], lose:['Again. Please. Again.'],
            respect:['You didn\'t go easy. That\'s respect.'] } },

  { id:'c_ren', name:'Ren Kurosawa', nick:'The Black Rose', promo:'rose', align:'heel', over:55,
    style:'technician', attrs:{po:52,te:82,ae:56,ch:70,ps:78,to:64,st:70}, finisher:'Thorn',
    gimmick:'Left the company once and came back colder. Treats every match as a debt being collected.',
    traits:['ruthless','calculating','resentful'],
    look:L('#e8bd95','#1a1a1a','#1a1a1a','#C6392C',{hairStyle:'long',attire:'tights',boots:'tall',acc:'cape',pattern:'split'}),
    lines:{ taunt:['This company forgot me. I didn\'t forget it.','You\'re in my way. It isn\'t personal. It\'s exactly personal.'],
            win:['Paid.'], lose:['A delay. Not a cancellation.'],
            respect:['You fought like it mattered. Few here do.'] } },

  { id:'c_momo', name:'Momo Hayashi', nick:'The Comet', promo:'rose', align:'face', over:40,
    style:'highflyer', attrs:{po:36,te:56,ae:80,ch:66,ps:44,to:42,st:80}, finisher:'Comet Tail',
    gimmick:'Youngest on the roster. Runs everywhere, including into things. The crowd adores her for it.',
    traits:['reckless','beloved','agile'],
    look:L('#f3d3b3','#e0e0e0','#2fbfa8','#F4E8DB',{hairStyle:'pony',attire:'tights',boots:'sneak',acc:'elbow',pattern:'stars'}),
    lines:{ taunt:['Faster! Everything is better faster!','I\'m going to jump. I don\'t know where yet.'],
            win:['Did you SEE that?!'], lose:['Ow. Okay. Ow.'],
            respect:['You caught me! Nobody catches me!'] } },

];

/* Every character starts neutral with you; the career mutates this. */
window.RTR_REL_DEFAULT = { respect:0, heat:0, matches:0, wins:0, losses:0, met:false };

/* ============================================================
   FACTIONS: the groups that run each locker room
   ------------------------------------------------------------
   You can be recruited into one once its leader respects you.
   Membership brings allies (who interfere on your behalf), a
   reputation share, and enemies you inherit whether you like it
   or not. You can also betray them, which nobody forgets.
   ============================================================ */
window.RTR_FACTIONS = [
  { id:'f_court', name:"The Kingmaker's Court", promo:'cwf', color:'#e0b341', align:'heel',
    leader:'c_kaiser', members:['c_nadia','c_titus'], rivals:['f_gate'],
    blurb:'Duke Kaiser doesn\'t have friends. He has assets, and they\'re the most protected people in the business.',
    perk:'Ally interference swings close matches your way, and reputation flows to you faster.',
    bonus:{ interfere:0.34, rep:1.22, heat:6 } },

  { id:'f_family', name:'The Grit City Family', promo:'gcw', color:'#a8602c', align:'tweener',
    leader:'c_slade', members:['c_trash','c_cutler'], rivals:['f_syndicate'],
    blurb:'Not a stable so much as a congregation. They bled in the same bingo hall and they don\'t forget who showed up.',
    perk:'Your people have your back in the ugly matches, and you take less punishment.',
    bonus:{ interfere:0.26, tough:0.88, rep:1.08 } },

  { id:'f_syndicate', name:'The Sunset Syndicate', promo:'scw', color:'#d2687a', align:'heel',
    leader:'c_kip', members:['c_mimi'], rivals:['f_family'],
    blurb:'Matching jackets, a publicist, and a shared belief that the spotlight is a finite resource.',
    perk:'Constant camera time: popularity climbs much faster while you\'re with them.',
    bonus:{ interfere:0.22, pop:1.45 } },

  { id:'f_dojo', name:'The Iron Blossom Dojo', promo:'kaiju', color:'#4a8f76', align:'face',
    leader:'c_ryu', members:['c_sora','c_mori'], rivals:['f_court'],
    blurb:'A training hall first and a faction second. You aren\'t recruited so much as accepted.',
    perk:'Relentless drilling: you build move mastery considerably faster.',
    bonus:{ mastery:1.4, rep:1.1 } },

  { id:'f_eternos', name:'Los Eternos', promo:'eterna', color:'#d99a2b', align:'face',
    leader:'c_relampago', members:['c_sangre'], rivals:[],
    blurb:'Three generations of masks under one banner. The lineage matters more than any single member.',
    perk:'The crowd adopts you as one of their own, and big spots land more often.',
    bonus:{ pop:1.28, risk:0.10 } },

  { id:'f_gate', name:'The Gatekeepers', promo:'acw', color:'#5e7f8a', align:'tweener',
    leader:'c_grange', members:['c_tank'], rivals:['f_court'],
    blurb:'Two men who never won the big one and decide, quietly, who gets to. The most powerful people nobody books.',
    perk:'Veteran counsel: training points go further and your ring psychology grows faster.',
    bonus:{ tp:0.35, psy:1.5 } },
];
