/* GENERATED by scripts/fetch-awards.mjs. Do not edit. Elite awards
 * keyed by sport|normalized-name; data.js merges these onto matching
 * corpus entities so game gates can surface real credentials. */
window.RTG_AWARDS = {"updated":"2026-08-09","count":0,"players":{}};
