/* GENERATED by scripts/fetch-rosterstats.mjs. Do not edit by hand.
 * Placeholder until the arcade-stats CI job runs and fills it with career
 * NBA (stats.nba.com) + MLB (statsapi) counting stats for every corpus player.
 * Merged OVER stats.js/hlstats.js inside High Low only. */
window.RTG_ROSTERSTATS = { updated: null, asof: {}, activeIds: {}, stats: {} };
